import { rng, pick, hashSeed } from "./random.ts";

export const ARENA_FAMILIES=["sentinel-manufactory","rootbound-crown","shattered-observatory","drowned-relay-rim","biomechanical-aperture","ruined-fortress-court","ash-amphitheater","alien-vault"];
const FAMILY_RULES={
 "sentinel-manufactory":{floor:"metal",hazard:"assembly-vents",boss:"voidSentinel"},"rootbound-crown":{floor:"rootFloor",hazard:"root-eruptions",boss:"rootBrute"},"shattered-observatory":{floor:"glassFloor",hazard:"brittle-panels",boss:"gravitantBell"},"drowned-relay-rim":{floor:"stone",hazard:"bounded-water",boss:"coilStalker"},"biomechanical-aperture":{floor:"apertureFloor",hazard:"pulse-nodes",boss:"gateRevenant"},"ruined-fortress-court":{floor:"fortressFloor",hazard:"falling-masonry",boss:"hollowMarshal"},"ash-amphitheater":{floor:"ashFloor",hazard:"ember-vents",boss:"riftColossus"},"alien-vault":{floor:"vaultFloor",hazard:"phase-lines",boss:"knifeChoir"}
};
const layouts=["ring-bridge","cross-court","offset-vault"];
function carve(tiles,w,x,y,kind){if(x>0&&y>0&&x<w-1&&y<tiles.length/w-1)tiles[y*w+x]={x,y,kind,blocked:false}}
function reachable(map,a,b){const w=map.width,h=map.height,q=[a],seen=new Set([`${a.x},${a.y}`]);while(q.length){const p=q.shift();if(p.x===b.x&&p.y===b.y)return true;for(const[dX,dY]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dX,y=p.y+dY,k=`${x},${y}`;if(x<0||y<0||x>=w||y>=h||seen.has(k)||map.tiles[y*w+x]?.blocked)continue;seen.add(k);q.push({x,y})}}return false}
export function arenaEligible(seed,rx,ry,kind="persistent"){return hashSeed(`${seed}:arena-cadence:${kind}:${rx}:${ry}`)%1000<(kind==="temporary"?18:7)}
export function generateBespokeArena(seed,id,{kind="persistent",family=null,cleared=false}={}){const r=rng(`${seed}:arena:v1:${id}`),f=family||pick(r,ARENA_FAMILIES),rule=FAMILY_RULES[f],layout=pick(r,layouts),width=36,height=30,tiles=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++)tiles.push({x,y,kind:"void",blocked:true});const room=(x0,y0,x1,y1)=>{for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)carve(tiles,width,x,y,rule.floor)};room(14,23,21,28);room(8,8,27,21);if(layout==="ring-bridge"){room(4,11,31,16);room(15,4,20,25)}else if(layout==="cross-court"){room(3,13,32,17);room(16,3,20,26)}else{room(5,7,16,18);room(19,11,30,22);room(14,14,22,18)}for(let y=18;y<=24;y++)room(16,y,19,y);const entry={x:18,y:27},objective={x:18,y:11},exit={x:18,y:27},map={seed,id,recipe:"bespoke-arena",arena:true,arenaKind:kind,family,arenaFamily:f,name:f.replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase()),identity:`${kind} bespoke arena`,width,height,tiles,entry,objective,exit,layout,objects:[{id:"arena-exit",kind:"exit",x:exit.x,y:exit.y,state:"open",actions:["exit"]},{id:"arena-recovery",kind:"deepAnchor",x:entry.x+2,y:entry.y,state:"active",actions:["recover"]}],enemySpawns:cleared?[]:[{id:`${id}:boss`,kind:rule.boss,x:objective.x,y:objective.y,boss:true,worldBoss:true,arenaId:id}],diagnostic:{family:f,layout,size:"bounded",hazardPackage:rule.hazard,reachable:false,kind}};map.diagnostic.reachable=reachable(map,entry,objective)&&reachable(map,objective,exit);return map}
export function arenaDescriptor(map){return{family:map.arenaFamily,layout:map.layout,size:`${map.width}x${map.height}`,hazardPackage:map.diagnostic?.hazardPackage,lifecycle:map.arenaKind,traversalValidation:map.diagnostic?.reachable===true?"pass":"fail"}}

const GRAMMARS={hollow:["cross","loop","offset","hub"],cistern:["reservoir-ring","split-bridge","offset-channel","hub"],kiln:["heat-lanes","furnace-loop","offset-forge","cross-vents"]};
function line(tiles,w,x0,y0,x1,y1,kind="floor"){for(let y=Math.min(y0,y1);y<=Math.max(y0,y1);y++)for(let x=Math.min(x0,x1);x<=Math.max(x0,x1);x++)carve(tiles,w,x,y,kind)}
export function generateVariedDungeon(seed,id,recipe="hollow"){const r=rng(`${seed}:ordinary-v3:${id}`),width=28,height=28,tiles=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++)tiles.push({x,y,kind:"wall",blocked:true,detail:(x+y)%4});const grammar=pick(r,GRAMMARS[recipe]||GRAMMARS.hollow),entry={x:4,y:23},exit=entry,guardian={x:22,y:5};line(tiles,width,3,21,8,25);line(tiles,width,5,5,9,23);line(tiles,width,7,5,guardian.x,9);if(grammar.includes("loop")||grammar.includes("ring")){line(tiles,width,9,16,22,20);line(tiles,width,20,7,24,20);line(tiles,width,8,16,22,18)}else if(grammar.includes("hub")||grammar.includes("cross")){line(tiles,width,8,13,23,17);line(tiles,width,14,7,18,23)}else if(grammar.includes("split")){line(tiles,width,8,12,22,15);line(tiles,width,8,18,22,21);line(tiles,width,20,12,24,21)}else{line(tiles,width,10,10,17,14);line(tiles,width,15,10,19,23);line(tiles,width,17,6,24,11)}line(tiles,width,guardian.x-2,guardian.y-2,guardian.x+2,guardian.y+2);const open=tiles.filter(t=>!t.blocked),at=n=>open[Math.min(open.length-1,Math.floor(n*open.length))],branchCount=grammar.includes("hub")?3:grammar.includes("split")||grammar.includes("offset")?2:1,loopCount=grammar.includes("loop")||grammar.includes("ring")?1:0,hazard=recipe==="kiln"?"vent-chain":recipe==="cistern"?"bounded-channel":"signal-spikes",objects=[{id:"dungeon-exit",kind:"exit",x:entry.x,y:entry.y,state:"open",actions:["exit"]},{id:"dungeon-chest",kind:"chest",x:guardian.x-2,y:guardian.y,state:"closed",actions:["open"],rewardSource:`${recipe}-cache`}];if(recipe==="kiln")objects.push({id:"kiln-vent",kind:"trap",trapType:"fire",x:at(.55).x,y:at(.55).y,dirX:1,dirY:0,phase:"armed",timer:0,hits:{},clue:"scorch"});else objects.push({id:`${recipe}-trap`,kind:"trap",trapType:"spikes",x:at(.55).x,y:at(.55).y,phase:"armed",timer:0,hits:{},clue:"seams"});const map={seed,id,recipe,name:{hollow:"Hollow Relay",cistern:"Root-Sunk Cistern",kiln:"Glass Kiln"}[recipe],identity:"ordinary crossing",danger:"measured",width,height,tiles,entry,objects,enemySpawns:[{kind:"ashling",x:at(.22).x,y:at(.22).y},{kind:recipe==="kiln"?"sparkWarden":"rootBrute",x:at(.7).x,y:at(.7).y},{id:"ordinary-guardian",kind:"hollowMarshal",x:guardian.x,y:guardian.y,boss:true}],diagnostic:{family:recipe,layoutGrammar:grammar,sizeCategory:grammar.includes("loop")?"extended":grammar.includes("hub")?"medium":"short",branchCount,loopCount,hazardPackage:hazard,guardianPackage:"marshal",shortcutType:loopCount?"return-loop":"none",traversalValidation:"pending"}};map.diagnostic.traversalValidation=reachable(map,entry,guardian)?"pass":"fail";return map}
