import{eliteDefinition,eliteVariant}from'./elites.ts';
export const CREATURE_TRAITS={plated:{name:'Plated',text:'Thicker shell; more vitality.',hp:1.4},feral:{name:'Feral',text:'Greater damage with a frailer body.',hp:.85,damage:1.35},swift:{name:'Swift',text:'Moves considerably faster.',speed:1.35},farcasting:{name:'Far-casting',text:'Threatens from farther away.',range:1.5},vital:{name:'Vital',text:'Dense living structure; increased vitality.',hp:1.22},keen:{name:'Keen',text:'A more dangerous, disciplined strike.',damage:1.2},orbital:{name:'Orbital',text:'Carries a visible rotating ward beyond its body.'}};
export const CREATURE_FORMS={ashling:{scale:.9},glassMite:{scale:.7},sparkWarden:{scale:1.05},ashenHound:{scale:.92},veilMoth:{scale:.82},rootBrute:{scale:1.32},coilStalker:{scale:1.12,segments:3,segmentSpacing:.31},cinderWisp:{scale:.72},voidSentinel:{scale:1.28,tentacles:7},hollowMarshal:{scale:1.62},riftColossus:{scale:2.18,segments:4,segmentSpacing:.36},mossGrazer:{scale:.88},lanternDoe:{scale:.92},hushling:{scale:.62},gateRevenant:{scale:1.85,tentacles:8},vesperwing:{scale:1.72},gravitantBell:{scale:1.82,tentacles:6},mireApostle:{scale:1.9},knifeChoir:{scale:1.7,segments:4,segmentSpacing:.3,tentacles:6}};
export const MELEE_PATTERNS={longReach:{id:'longReach',name:'Long Reach',range:2.15,telegraph:1,recovery:2.1},lunge:{id:'lunge',name:'Lunge',range:3.4,telegraph:.8,recovery:2.3,dash:1.35},zigzag:{id:'zigzag',name:'Zigzag Assault',range:4,telegraph:.95,recovery:2.8,dash:1.05,stages:2},hop:{id:'hop',name:'Hop',range:4.4,telegraph:1.05,recovery:2.7,dash:1.7,hop:true},slam:{id:'slam',name:'Heavy Slam',range:2.4,telegraph:1.25,recovery:3.2,radius:1.8}};
export function meleePatternsFor(kind,boss=false,traits=[]){const table={ashling:['lunge'],glassMite:['hop'],ashenHound:['zigzag'],rootBrute:['slam'],hollowMarshal:['longReach','lunge'],riftColossus:['slam','longReach'],mireApostle:['slam'],knifeChoir:['zigzag','longReach']},ids=[...(table[kind]||['longReach'])];if(traits.includes('swift')&&!ids.includes('lunge'))ids.push('lunge');if(boss&&!ids.includes('slam'))ids.push('slam');return ids.slice(0,boss?2:1)}
export function enemyBodyRadius(enemy){return Math.max(.28,Number(enemy?.bodyRadius)||.38)}
export function createCombatant(kind,x,y,boss=false,traits=[]){const defs={ashling:[24,5,0],glassMite:[18,4,0],sparkWarden:[30,7,5],ashenHound:[28,7,0],veilMoth:[20,5,4],rootBrute:[48,9,0],coilStalker:[34,8,2],cinderWisp:[16,6,5],voidSentinel:[58,10,6],hollowMarshal:[85,10,0],riftColossus:[180,15,3],vesperwing:[230,18,6],gravitantBell:[285,20,4.8],mireApostle:[310,19,5.5],knifeChoir:[260,17,4]},base=defs[kind]||defs.ashling,form=CREATURE_FORMS[kind]||CREATURE_FORMS.ashling,elite=eliteDefinition(kind),ev=elite&&eliteVariant('combat',kind);let hp=base[0],damage=base[1],range=base[2],speedMultiplier=1;for(const id of traits){const t=CREATURE_TRAITS[id];if(!t)continue;hp*=t.hp||1;damage*=t.damage||1;range*=t.range||1;speedMultiplier*=t.speed||1}hp=Math.round(hp);damage=Math.round(damage);range=Math.round(range*10)/10;const sizeMultiplier=traits.includes('vital')?1.08:traits.includes('plated')?1.06:1,scale=form.scale*sizeMultiplier,bodyRadius=.38+Math.max(0,scale-1)*.3,variantId=ev?.variantId||`${kind}:${traits.join('+')||'common'}`,isBoss=boss||!!elite;return{id:`${kind}-${x}-${y}`,kind,x,y,hp,maxHp:hp,damage,range,boss:isBoss,eliteId:elite?.id||null,eliteName:elite?.name||null,eliteModules:[...(ev?.modules||[])],eliteVariantModules:[...(ev?.variantModules||[])],threatCost:elite?.threatCost||0,traits:[...traits],variantId,speedMultiplier,scale,bodyRadius,segments:form.segments||1,segmentSpacing:form.segmentSpacing||0,tentacles:form.tentacles||0,meleePatterns:range<2.5?meleePatternsFor(kind,isBoss,traits):[],meleePatternIndex:0,meleePhase:null,instantStrike:kind==='veilMoth',cooldown:0,telegraph:0,eliteCooldown:0,dead:false}}
export function dodge(player,now,x=0,y=0){if(player.stamina<15)return{ok:false,reason:'stamina'};let m=Math.hypot(x,y);if(m<.15){const q=player.lastMoveVector||{x:0,y:1};x=Number(q.x)||0;y=Number(q.y)||0;m=Math.hypot(x,y)||1}player.dodgeX=x/m;player.dodgeY=y/m;player.lastMoveVector={x:player.dodgeX,y:player.dodgeY};player.stamina-=15;player.invulnerableUntil=now+420;player.dodgeUntil=now+260;return{ok:true}}
export function playerAttack(player,enemies,now){if(now<(player.attackReadyAt||0))return null;player.attackReadyAt=now+420;let best=null,dist=1.65;for(const e of enemies){const d=Math.hypot(e.x-player.x,e.y-player.y);if(!e.dead&&d<dist){best=e;dist=d}}if(best){best.hp-=7+(player.stats.Might*2)+(player.weaponLevel*3);best.hitFlash=.18;best.recoil=.14;if(best.hp<=0)best.dead=true}return best}
