import{hashSeed}from'./random.js?v=73';
export const ELITE_DEFINITIONS={
 vesperwing:{id:'vesperwing',name:'Vesperwing',epithet:'The Ashen Meridian',baseForm:'veilMoth',movement:'hover',stableModules:['dive','ranged'],variantModules:['swift','farcasting','orbital'],threatCost:8,context:'marked',reward:{marks:35,xp:55,material:'weaponSphere'},lore:'Its ruined wings measure the Corridor by the shadows they erase.'},
 gravitantBell:{id:'gravitantBell',name:'Gravitant Bell',epithet:'The Weight Below',baseForm:'rootBrute',movement:'hover',stableModules:['gravity','radialPulse'],variantModules:['plated','orbital','stun'],threatCost:10,context:'guardian',reward:{marks:42,xp:60,material:'armorSphere'},lore:'A fallen transit bell still calls every loose thing toward its mouth.'},
 mireApostle:{id:'mireApostle',name:'Mire Apostle',epithet:'Saint of the Low Water',baseForm:'rootBrute',movement:'ooze',stableModules:['oozePool','poison','trail'],variantModules:['plated','summon','farcasting'],threatCost:11,context:'world',reward:{marks:48,xp:65,material:'armorSphere',consumable:'clearrootAmpoule'},lore:'It carries a drowned chapel on its back and blesses the ground with venom.'},
 knifeChoir:{id:'knifeChoir',name:'Choir of Knives',epithet:'The Divided Cantor',baseForm:'coilStalker',movement:'skitter',stableModules:['summon','split'],variantModules:['swift','orbital','ranged'],threatCost:12,context:'portal',reward:{marks:55,xp:70,material:'weaponSphere'},lore:'Each orbiting shard sings one missing part of the body at its center.'}
};
export const ELITE_KINDS=new Set(Object.keys(ELITE_DEFINITIONS));
export function eliteDefinition(id){return ELITE_DEFINITIONS[id]||null}
export function eliteVariant(seed,id,area='world'){const d=eliteDefinition(id);if(!d)return null;const n=hashSeed(`${seed}:elite:${id}:${area}`),pool=d.variantModules||[],count=1+(n%3===0?1:0),variants=[];for(let i=0;i<count&&i<pool.length;i++){const q=pool[(n+i*5)%pool.length];if(!variants.includes(q))variants.push(q)}return{...d,modules:[...d.stableModules,...variants],variantModules:variants,visualSeed:n,variantId:`elite:${id}:${n%997}`,phase:n%2?'restless':'watchful'}}
export function eliteThreat(def,depth=0,arena=0,count=1){const d=typeof def==='string'?eliteDefinition(def):def;if(!d)return 0;return Math.round((d.threatCost+Math.max(0,depth)*.35+Math.max(0,arena))*Math.max(1,count)*10)/10}
export function freshEliteState(){return{contracts:{vesperwing:{state:'available',progress:0,goal:1,rewarded:false},knifeChoir:{state:'locked',progress:0,goal:4,rewarded:false}},defeated:{},encounters:{},status:{poison:0,poisonTick:0,stun:0,stunGuard:0}}}
export function ensureEliteState(save){const base=freshEliteState(),old=save.elites||{};save.elites={...base,...old,contracts:{...base.contracts,...old.contracts},defeated:{...old.defeated},encounters:{...old.encounters},status:{...base.status,...old.status}};return save.elites}
export function acceptContract(save,id){const s=ensureEliteState(save),c=s.contracts[id];if(!c||!['available','locked'].includes(c.state))return false;if(id==='knifeChoir'&&c.progress<c.goal)return false;c.state='accepted';return true}
export function recordPortalPrey(save,kind){const s=ensureEliteState(save),c=s.contracts.knifeChoir;if(c.state==='resolved'||!['ashling','glassMite'].includes(kind))return c.progress;c.progress=Math.min(c.goal,c.progress+1);if(c.progress>=c.goal&&c.state==='locked')c.state='available';return c.progress}
export function applyPoison(status,duration=8){status.poison=Math.max(Number(status.poison)||0,duration);status.poisonTick=Math.min(Number(status.poisonTick)||1,1);return status}
export function tickEliteStatus(status,dt,onDamage=()=>{}){status.poison=Math.max(0,(Number(status.poison)||0)-dt);status.stun=Math.max(0,(Number(status.stun)||0)-dt);status.stunGuard=Math.max(0,(Number(status.stunGuard)||0)-dt);if(status.poison>0){status.poisonTick-=dt;while(status.poisonTick<=0){onDamage(2);status.poisonTick+=1}}else status.poisonTick=0;return status}
export function cleansePoison(save){const s=ensureEliteState(save);if(!(save.consumables.clearrootAmpoule>0)||!(s.status.poison>0))return false;save.consumables.clearrootAmpoule--;s.status.poison=s.status.poisonTick=0;return true}
export function gravityPull(player,source,dt,force=1.5,radius=5){const dx=source.x-player.x,dy=source.y-player.y,d=Math.hypot(dx,dy);if(!d||d>radius)return false;const step=Math.min(force*dt,Math.max(0,d-1.15));player.x+=dx/d*step;player.y+=dy/d*step;return true}
export function addEliteHazard(hazards,hazard,cap=8){const same=hazards.filter(h=>h.owner===hazard.owner&&h.kind===hazard.kind);if(same.length>=cap){const oldest=same.sort((a,b)=>(a.life||0)-(b.life||0))[0],i=hazards.indexOf(oldest);if(i>=0)hazards.splice(i,1)}hazards.push({...hazard,hits:{...(hazard.hits||{})}});return hazards}
export function tickEliteHazards(hazards,dt){for(const h of hazards)h.life-=dt;return hazards.filter(h=>h.life>0)}
export function completeElite(save,id){const d=eliteDefinition(id),s=ensureEliteState(save);if(!d||s.defeated[id])return null;s.defeated[id]=true;const c=s.contracts[id];if(c)c.state='rewardAvailable';save.currency+=d.reward.marks;save.materials[d.reward.material]=(save.materials[d.reward.material]||0)+1;if(d.reward.consumable)save.consumables[d.reward.consumable]=(save.consumables[d.reward.consumable]||0)+1;if(c){c.state='resolved';c.rewarded=true}return d.reward}
