import{hashSeed}from'./random.ts';
export const CREATURE_FOUNDRY_SCHEMA='creature-foundry/1.0.0';
const bodies=['quadruped','floating','segmented','tentacled','geometric','biomechanical'],movements=['stalking','hopping','hovering','orbiting','retreating'],attacks=['meleeSwipe','straightBolt','threeShotCone','arcBurst','sweepingBeam'],weaknesses=['turnLock','postAttackCore','breakableArmor','closeRangeBlindspot','interruptibleWindup'],ecologies=['relayScavenger','breachMigrant','ruinNester','lumenGrazer','archiveGuardian'],prefix=['Pale','Canting','Riven','Lantern','Hollow','Violet'],suffix=['Strider','Bell','Maw','Pilgrim','Lattice','Witness'];
export function foundryCandidate(seed,rx,ry,generation=1){const n=hashSeed(`${seed}:foundry:v1:g${generation}:${rx}:${ry}`),boss=n%17===0,passive=!boss&&n%5===0,role=boss?'boss':passive?'passive':'hostile',baseKind=boss?'archiveBehemoth':passive?'riftGrazer':'latticeHunter',id=`foundry-v1-${(n>>>0).toString(36)}-${rx}-${ry}`,attack=passive?'none':attacks[(n>>>7)%attacks.length],body=bodies[(n>>>3)%bodies.length],movement=movements[(n>>>5)%movements.length],weakness=weaknesses[(n>>>11)%weaknesses.length],ecology=ecologies[(n>>>13)%ecologies.length],name=`${prefix[(n>>>17)%prefix.length]} ${suffix[(n>>>21)%suffix.length]}`;return{schema:CREATURE_FOUNDRY_SCHEMA,id,name,role,baseKind,body,movement,attack,weakness,ecology,visualSeed:n>>>0,palette:(n>>>9)%5,retirable:true,stable:true}}
export function foundryEncounter(seed,rx,ry,generation=1){const depth=Math.abs(rx)+Math.abs(ry),roll=hashSeed(`${seed}:foundry-channel:v1:g${generation}:${rx}:${ry}`)%10000;if(depth<5||roll>=85)return null;const c=foundryCandidate(seed,rx,ry,generation),x=6+hashSeed(c.id+':x')%20,y=6+hashSeed(c.id+':y')%20;return{...c,x,y,kind:c.baseKind,boss:c.role==='boss',ambient:c.role==='passive',passiveBehavior:c.role==='passive'?'graze':null,foundryId:c.id,foundryName:c.name,foundryRole:c.role,foundryModules:[c.body,c.movement,c.attack,c.weakness,c.ecology]}}
export function validateFoundryCandidate(c){if(!c||c.schema!==CREATURE_FOUNDRY_SCHEMA||!['passive','hostile','boss'].includes(c.role))return{ok:false,reason:'schema'};if(c.role==='passive'&&c.attack!=='none')return{ok:false,reason:'passive-attack'};if(c.role!=='passive'&&c.attack==='none')return{ok:false,reason:'missing-counterplay'};if(!weaknesses.includes(c.weakness)||!bodies.includes(c.body)||!movements.includes(c.movement))return{ok:false,reason:'unsupported-module'};return{ok:true,threatBudget:c.role==='boss'?38:c.role==='hostile'?10:0}}

export const VIEWPORT_SCHEMA='viewport/1.0.0';
const copy=(value)=>JSON.parse(JSON.stringify(value));
export function viewportContracts(seed='CINDER-VERGE-47'){
 const n=hashSeed(`${seed}:viewport:v1`),sx=n&1?1:-1,sy=n&2?1:-1,frontier={rx:sx*(6+n%3),ry:sy*(5+(n>>>3)%3)},trial={rx:-sx*(7+(n>>>6)%2),ry:sy*(6+(n>>>8)%2)};
 return[
  {id:'viewport-direct-vesperwing',kind:'direct',title:'The Ashen Meridian',summary:'A Vesperwing circles an exposed crossing five sections east and two north.',status:'available',target:{rx:5,ry:-2},targetKind:'vesperwing',reward:{marks:35,weaponSphere:1},lifecycle:'persistent'},
  {id:'viewport-tracking-lattice',kind:'tracking',title:'Tracks in the Lattice',summary:'Three traces can reconcile into the route of a plated hunter.',status:'available',target:{rx:frontier.rx,ry:frontier.ry},targetKind:'latticeHunter',stages:['range','hunt','guardian'],reward:{marks:30,draughts:2},lifecycle:'persistent'},
  {id:'viewport-frontier-manufactory',kind:'frontier',title:'Sentinel Manufactory',summary:'Repeated Sentinel signals describe a production field beyond the charted Verge.',status:'available',target:frontier,targetKind:'voidSentinel',domain:'sentinel-manufactory',reward:{marks:55,armorSphere:1},lifecycle:'transformed-after-completion'},
  {id:'viewport-foundry-trial',kind:'trial',title:'Uncatalogued Manifestation',summary:'Viewport can hold one consequential Foundry lifeform inside a recoverable aperture.',status:'available',target:trial,targetKind:'archiveBehemoth',reward:{marks:45,weaponSphere:1},lifecycle:'persistent'}
 ];
}
export function freshViewportState(seed){return{schema:VIEWPORT_SCHEMA,read:false,activeHuntId:null,contracts:Object.fromEntries(viewportContracts(seed).map(q=>[q.id,copy(q)])),recent:[],archive:[]}}
export function ensureViewportState(save){const base=freshViewportState(save?.seed),old=save.viewport||{};save.viewport={...base,...old,contracts:{...base.contracts,...old.contracts},recent:[...(old.recent||[])].slice(-24),archive:[...(old.archive||[])].slice(-24)};for(const q of Object.values(save.viewport.contracts)){q.status||='available';q.progress||={};q.lifecycle||='persistent'}return save.viewport}
export function viewportContract(save,id){return ensureViewportState(save).contracts[id]||null}
export function activeViewportHunt(save){const v=ensureViewportState(save);return v.activeHuntId?v.contracts[v.activeHuntId]||null:null}
export function acceptViewportHunt(save,id){const v=ensureViewportState(save),q=v.contracts[id];if(!q||!['available','deferred','accepted','tracking','target-located'].includes(q.status))return{ok:false,message:'That Viewport record cannot be accepted.'};if(v.activeHuntId&&v.activeHuntId!==id){const prior=v.contracts[v.activeHuntId];if(prior&&['accepted','tracking','target-located'].includes(prior.status))prior.status='deferred'}v.activeHuntId=id;q.status=q.kind==='tracking'?'tracking':'accepted';q.acceptedAt=Object.keys(save.explored||{}).length;save.waypoint={...q.target,name:q.title,source:'viewport',huntId:id};return{ok:true,message:`${q.title} accepted. Viewport has marked the ${q.kind==='tracking'?'first search region':'known approach'} on the Atlas.`,contract:q}}
export function deferViewportHunt(save,id){const v=ensureViewportState(save),q=v.contracts[id];if(!q)return false;q.status='deferred';if(v.activeHuntId===id)v.activeHuntId=null;if(save.waypoint?.huntId===id)save.waypoint=null;return true}
export function archiveViewportHunt(save,id){const v=ensureViewportState(save),q=v.contracts[id];if(!q||q.status==='completed')return false;q.status='archived';if(!v.archive.includes(id))v.archive.push(id);if(v.activeHuntId===id)v.activeHuntId=null;if(save.waypoint?.huntId===id)save.waypoint=null;return true}
export function completeViewportHunt(save,id){const v=ensureViewportState(save),q=v.contracts[id];if(!q||q.status==='completed')return false;q.status='completed';q.completedAt=Object.keys(save.explored||{}).length;if(v.activeHuntId===id)v.activeHuntId=null;if(save.waypoint?.huntId===id)save.waypoint=null;save.currency+=(q.reward?.marks||0);save.materials.weaponSphere=(save.materials.weaponSphere||0)+(q.reward?.weaponSphere||0);save.materials.armorSphere=(save.materials.armorSphere||0)+(q.reward?.armorSphere||0);save.consumables.restorativeDraught=(save.consumables.restorativeDraught||0)+(q.reward?.draughts||0);v.recent.push({id:`complete:${id}`,title:q.title,text:'Hunt completed and recorded by Viewport.',kind:'hunt'});return true}
export function recordViewportArrival(save,entry){const v=ensureViewportState(save);if(v.recent.some(q=>q.id===entry.id))return false;v.recent.push({...entry});v.recent=v.recent.slice(-24);return true}
export function foundryTrialDecision(save,id,decision){const q=viewportContract(save,id);if(!q||q.kind!=='trial'||q.status!=='completed')return false;q.decision=decision;if(decision==='corridor')save.worldFlags[`foundry-admitted:${id}`]=true;else if(decision==='rare')save.worldFlags[`foundry-rare:${id}`]=true;else if(decision==='dungeon')save.worldFlags[`foundry-dungeon:${id}`]=true;else if(decision==='rework')q.status='deferred';else if(decision==='archive')archiveViewportHunt(save,id);return true}
