import{REFUGE_NPCS,ensurePerception}from'./types.js?v=84';import{dungeonId,apertureTier,perceived}from'./world.js?v=84';
import{hashSeed}from'./random.js?v=84';import{ensureEliteState,acceptContract}from'./elites.js?v=84';export const NARRATIVE_SCHEMA='infinite-corridor-narrative/1.0.0';
import{recordRevelationLead,completeRevelationArc}from'./story.js?v=84';
export const CONTENT_PACK={schema:NARRATIVE_SCHEMA,id:'cinder-verge-core',provenance:{source:'original',author:'Infinite Corridor prototype'},entities:[{id:'vela',kind:'person',name:'Vela Quen'},{id:'quiet-array',kind:'place',name:'Quiet Array'}],records:[{id:'crossing-beacon',targets:['checkpoint'],actions:['activate'],variants:['The beacon speaks your name before you touch it. “Wayfarer: crossing incomplete.”'],effects:[{type:'fact',key:'crossing.beacon',value:true}],journal:'The beacon knew me before I arrived. It called the crossing incomplete.',once:true,globalUnique:true},{id:'vela-objective',targets:['npc'],actions:['speak'],variants:['Vela lowers her voice. “Three signal sites point beneath the Relay. Find them; cancel whatever is learning our crossings.”'],effects:[{type:'fact',key:'crossing.objective',value:true}],journal:'Vela sent me to trace the signal sites and cancel the mechanism below the Relay.',once:true,globalUnique:true},{id:'array-objective',targets:['shrine'],actions:['inspect'],variants:['The Array resolves three fixed signal sites, then a buried command: CANCEL CROSSING.'],effects:[{type:'fact',key:'crossing.objective',value:true},{type:'fact',key:'array.heard',value:true}],journal:'The Array marked three signal sites and a cancellation mechanism beneath the Relay.',once:true,globalUnique:true},{id:'signal-site',targets:['ruinMarker'],actions:['inspect'],variants:['A scorched receiver repeats one coordinate. The signal is deliberate, not a haunting.'],effects:[{type:'fact',key:'crossing.signal',value:true}],journal:'A signal site confirmed that the buried transmission is deliberate.',once:true,globalUnique:true},{id:'relay-restored',targets:['chest'],actions:['open'],when:{fact:'crossing.marshal',equals:true},variants:['The cancellation teeth lock. Power returns to the Relay — and something distant notices.'],effects:[{type:'fact',key:'crossing.restored',value:true}],journal:'I cancelled the mechanism and restored the Hollow Relay.',once:true,globalUnique:true},{id:'crossing-warning',targets:['exit'],actions:['exit'],when:{fact:'crossing.restored',equals:true},variants:['A distant voice crosses the restored line: “Don’t let it learn your way home.”'],effects:[{type:'fact',key:'crossing.complete',value:true}],journal:'A distant voice warned: “Don’t let it learn your way home.”',once:true,globalUnique:true},{id:'relay-door',targets:['door'],actions:['open','force'],variants:['The relay door exhales iron dust and reveals a dark receiving hall.'],effects:[{type:'fact',key:'relay.open',value:true}],journal:'The abandoned relay opened onto a silent receiving hall.',once:true}]};
export function validateContentPack(pack){if(pack?.schema!==NARRATIVE_SCHEMA||!Array.isArray(pack.records)||!pack.provenance)return false;const ids=new Set;return pack.records.every(r=>typeof r.id==='string'&&!ids.has(r.id)&&ids.add(r.id)&&Array.isArray(r.targets)&&Array.isArray(r.actions)&&Array.isArray(r.variants)&&r.variants.length&&r.effects.every(e=>['fact','flag','heal','currency','material'].includes(e.type)))}
export function selectRecordVariant(record,instanceKey,save){const chosen=save.narrative.selectedVariants;if(!(instanceKey in chosen))chosen[instanceKey]=hashSeed(`${save.seed}:${record.id}:${instanceKey}`)%record.variants.length;return record.variants[chosen[instanceKey]]}
export function preconditionsMet(record,save){const w=record.when||{};return(!w.fact||save.narrative.facts[w.fact]===w.equals)&&(!w.factAbsent||!(w.factAbsent in save.narrative.facts))&&(!w.flag||save.worldFlags[w.flag]===w.equals)}
export function applyNarrative(object,action,save,instanceKey=`${object.id}:${action}`){if(object.kind==='npc'&&object.id!=='vendor-vela')return null;if(object.kind==='chest'||object.kind==='exit')return null;const record=CONTENT_PACK.records.find(r=>r.targets.includes(object.kind)&&r.actions.includes(action)&&preconditionsMet(r,save));if(!record)return null;const dedupe=record.globalUnique?`record:${record.id}`:instanceKey,already=!!save.narrative.appliedInstanceKeys[dedupe],text=selectRecordVariant(record,dedupe,save);if(record.once&&already)return{ok:true,message:text,record,duplicate:true};for(const e of record.effects){if(e.type==='fact')save.narrative.facts[e.key]=e.value;if(e.type==='flag')save.worldFlags[e.key]=e.value;if(e.type==='heal')save.hp=Math.min(save.maxHp,save.hp+e.amount);if(e.type==='currency')save.currency+=e.amount;if(e.type==='material')save.materials[e.key]=(save.materials[e.key]||0)+e.amount}save.narrative.appliedInstanceKeys[dedupe]=true;if(record.journal&&!save.narrative.journal.some(j=>j.recordId===record.id))save.narrative.journal.push({recordId:record.id,instanceKey:dedupe,title:'The Missing Crossing',text:record.journal,provenance:CONTENT_PACK.provenance.source});return{ok:true,message:text,record}}

export function currentObjective(save){
 const f=save.narrative.facts,c=save.consequences.choices.relay;
 const leads=f['leads.active']&&!f['leads.complete']?' · Leads: '+(f['lead.distance']?'✓ range':'reach range 4')+', '+(f['lead.hunt']?'✓ hunt':(save.worldFlags['lead.hunt.count']||0)+'/5 creatures')+', '+(f['lead.guardian']?'✓ guardian':'crossing guardian'):'';
 if(c)return'The Missing Crossing resolved — '+(c==='restore'?'Relay restored':'Relay severed')+'. Explore further crossings.';
 if(f['crossing.marshal'])return'The Missing Crossing — choose Restore or Sever at the Relay terminal';
 if(f['crossing.objective'])return'The Missing Crossing — find the Hollow Marshal'+leads;if(save.worldFlags['vendor-vela:dead'])return'The Missing Crossing — follow the solitary Array route to the Hollow Marshal'+leads;
 return'The Missing Crossing — question Vela or inspect the Signal Ledger'+leads;
}
export function progressLead(s,type){const f=s.narrative.facts;if(!f['leads.active']||f['lead.'+type])return false;f['lead.'+type]=true;journalOnce(s,'lead-'+type,'A Signal Ledger lead is complete: '+type+'.','Signal Ledger');if(f['lead.distance']&&f['lead.hunt']&&f['lead.guardian']&&!f['leads.complete']){f['leads.complete']=true;s.currency+=30;s.consumables.restorativeDraught+=2;journalOnce(s,'leads-complete','All three signals reconcile. The ledger releases 30 marks and two restorative draughts, then prints: THE CORRIDOR IS MAPPING YOU.','Signal Ledger — reconciled')}return true}
export function gainAperture(s,amount,source,message='Your Aperture widens.'){ensurePerception(s);if(s.perception.awarded[source])return 0;s.perception.awarded[source]=true;const before=apertureTier(s.perception.aperture);s.perception.aperture+=Math.max(0,Math.floor(amount));const after=apertureTier(s.perception.aperture);if(after>before){s.perception.announcedTier=after;journalOnce(s,'aperture-tier:'+after,message+' Hidden structure now answers your attention.','Aperture')}return amount}
export function journalOnce(s,id,text,title='Consequences'){if(s.narrative.journal.some(j=>j.recordId===id))return;s.narrative.journal.push({recordId:id,instanceKey:'record:'+id,title,text,provenance:'original'});}
export function resolveThread(s,id,ending){const prior=s.consequences.threads[id];if(prior?.status==='resolved')return prior.ending===ending;s.consequences.threads[id]={status:'resolved',ending};return true;}
export function npcState(s,id){return s.consequences.npcs[id];}
export function recordNpcDamage(s,o,amount,cause='attack',intent='deliberate'){
 const n=npcState(s,o.id);if(!n||n.status==='dead'||amount<=0)return false;const settlement=o.settlement||'ember-refuge';
 n.hp=Math.max(0,n.hp-amount);n.disposition='hostile';
 if(n.hp===0){Object.assign(n,{status:'dead',deathCause:cause,playerCaused:true,intent});o.state='dead';s.worldFlags[o.id+':dead']=true;if(s.consequences.settlements[settlement])s.consequences.settlements[settlement].reputation-=1;journalOnce(s,'death:'+o.id,(o.name||o.id)+' died '+(intent==='collateral'?'in the path of your attack.':'by your hand.')+' Their absence persists in '+settlement+'.');
 if(settlement==='ember-refuge'&&REFUGE_NPCS.every(q=>npcState(s,q.id).status==='dead')){s.consequences.settlements['ember-refuge'].status='fallen';resolveThread(s,'ember-refuge','fallen');journalOnce(s,'refuge-fallen','With its last resident gone, Ember Refuge fell. Monsters occupy its abandoned streets; its ruined beacon still offers a place to recover. This chapter of the refuge is closed; the solitary Array route remains open.');}}
 return true;
}
export function dungeonHistory(s,id){return s.consequences.dungeons[id]||=( {discovered:true,bypassed:false,visits:0,abandoned:0,guardianDefeated:false,resolved:false,visitOpen:false});}
export function abandonDungeon(s,id){const d=s.consequences.dungeons[id];if(!d?.visitOpen)return;d.visitOpen=false;if(!d.resolved){d.abandoned++;journalOnce(s,'abandon:'+id+':'+d.visits,'You left '+(id===dungeonId(s.seed,s.worldGeneration)?'the Hollow Relay':'a buried crossing')+' unresolved. Its progress remains; you can return.','Crossings');}}
export function commitRelay(s,choice,context){const id=dungeonId(s.seed,s.worldGeneration);if(context!==id||!s.narrative.facts['crossing.marshal']||!['restore','sever'].includes(choice))return{ok:false,message:'The Relay cannot be changed here yet.'};if(s.consequences.choices.relay)return{ok:false,message:'The Relay choice is permanent: '+s.consequences.choices.relay+'.'};if(!resolveThread(s,'missing-crossing',choice))return{ok:false,message:'This chapter already has a different ending.'};s.consequences.choices.relay=choice;Object.assign(dungeonHistory(s,id),{resolved:true,guardianDefeated:true});s.narrative.facts['crossing.complete']=true;s.narrative.facts[choice==='restore'?'crossing.restored':'crossing.severed']=true;if(choice==='restore')s.consumables.restorativeDraught+=2;else s.materials.lumenDust+=3;const message=choice==='restore'?'The Relay carries the crossing again. Its reserve yields two draughts. A voice warns: “Don’t let it learn your way home.”':'The Relay falls silent. You recover three lumen dust; the line will never learn your way home.';const aftermath=s.consequences.settlements['ember-refuge'].status==='fallen'?' The refuge is gone, but your solitary crossing continues.':' The refuge remains behind you; further crossings await.';journalOnce(s,'relay-choice',message+aftermath+' The Missing Crossing is resolved; the world remains open.','The Missing Crossing — resolved');return{ok:true,message:message+aftermath,transition:'relay'};}
export function validActions(o,s){
 if(!perceived(o,s))return[];
 if(o.kind==='npc'){const n=npcState(s,o.id);if(n?.status==='dead'||s.worldFlags[o.id+':dead'])return[];return(o.actions||[]).filter(a=>a!=='standDown'||n?.disposition==='hostile');}
 if(o.kind==='relayTerminal')return s.consequences.choices.relay?[]:s.narrative.facts['crossing.marshal']?['restore','sever']:['inspect'];
 if(o.kind==='elitePortal'){const c=ensureEliteState(s).contracts.knifeChoir;return c.state==='available'||c.state==='accepted'?['inspect','enter']:['inspect'];}
 if(o.kind==='tree'&&o.state!=='standing')return[];
 if(o.kind==='rock'&&o.state==='sealed')return s.stats.Might>=3?['move','break']:[];
 if(o.kind==='cache'&&o.state==='hidden'&&!s.worldFlags['rock-1:opened'])return[];
 return(o.actions||[]).filter(a=>!(o.state==='used'&&!['enter','exit','bypass'].includes(a)));
}
export function applyInteraction(o,a,s,context='global'){
 if(o.kind==='storyEcho'&&a==='inspect')return completeRevelationArc(s);
 if(o.kind==='elitePortal'){const c=ensureEliteState(s).contracts.knifeChoir;if(a==='inspect')return{ok:true,message:c.progress<c.goal?`The threshold needs four shard-echoes: ${c.progress}/${c.goal} ash-born creatures defeated.`:'Four shard-echoes answer. The Cantor Threshold can be entered.',transition:'eliteClue'};if(a==='enter'&&acceptContract(s,'knifeChoir'))return{ok:true,message:'The threshold opens onto a divided choir.',transition:'elitePortal'};return{ok:false,message:'The threshold remains sealed.'}}
 if(o.kind==='questBoard'&&a==='inspect'&&s.narrative.facts['leads.complete']&&ensureEliteState(s).contracts.vesperwing.state==='available'){acceptContract(s,'vesperwing');journalOnce(s,'elite-contract:vesperwing','Glasshaven marked the Vesperwing five sections east and two north of Ember Refuge. Reward: one weapon sphere and 35 marks.','Elite contract — The Ashen Meridian');return{ok:true,message:'ELITE CONTRACT: Vesperwing · seek section 5,-2 · weapon sphere and 35 marks.',transition:'quest'}}
 if(o.kind==='shelterMerchant'){if(a==='speak')return{ok:true,message:(o.name||'The merchant')+': “I only set my table where the Corridor forgets to look.”'};if(a==='trade')return{ok:true,message:'A small, improbable stock is unfolded.',transition:'trade'}}
 if(o.kind==='shelterCreature'&&a==='commune'){const key='shelter-gift:'+context+':'+o.id;if(s.worldFlags[key])return{ok:true,message:(o.name||'The creature')+' remembers you, but offers nothing twice.'};s.worldFlags[key]=true;o.state='befriended';if(o.gift==='aperture'){gainAperture(s,2,key,'A quiet creature teaches your Aperture a new contour.');return{ok:true,message:'It shares a wordless memory. Aperture +2.'}}if(o.gift==='lumen'){s.materials.lumenDust=(s.materials.lumenDust||0)+1;return{ok:true,message:'It leaves one lumen dust in your palm.'}}s.currency+=8;return{ok:true,message:'It nudges eight old marks from beneath the floorboards.'}}
 if(o.kind==='displacementDevice'&&a==='enter')return{ok:true,message:'The threshold folds the room into somewhere else.',transition:'displacement'};
 if(o.kind==='shelterHazard'&&a==='inspect'){journalOnce(s,'shelter-hazard:'+o.hazardType,`${o.name||'A shelter mechanism'} bears a repeatable warning pattern. Crossing its marked floor while armed will wound the Wayfarer once.`, 'Shelter hazards');return{ok:true,message:`${o.name}: the floor mark warns of a one-shot ${o.hazardType}. Step around it.`}}
 if(!validActions(o,s).includes(a))return{ok:false,message:'That action is not available.'};
 if(o.kind==='questBoard'&&a==='inspect'){if(!s.narrative.facts['leads.active']){s.narrative.facts['leads.active']=true;journalOnce(s,'signal-ledger','Three live leads remain: reach a section four steps from refuge; defeat five roaming creatures; and silence any crossing guardian. Reward: 30 marks and two draughts.','Signal Ledger');return{ok:true,message:'SIGNAL LEDGER: reach range four · defeat five creatures · silence one crossing guardian.',transition:'quest'}}return{ok:true,message:currentObjective(s),transition:'quest'}}
 if((o.kind==='shrine'||o.kind==='ruinMarker')&&a==='inspect'){gainAperture(s,2,'signal:'+context+':'+o.id,'A signal site teaches you how to notice what the world hides.');recordRevelationLead(s,'signal',context+':'+o.id)}
 if(o.kind==='apertureMemory'){o.state='used';gainAperture(s,3,'memory:'+context,'A buried memory resolves into language.');s.perception.discoveries.memories++;return{ok:true,message:'The inscription remembers a corridor that has not happened yet. Aperture +3.',transition:'aperture'};}
 if(o.kind==='apertureDoor')return{ok:true,message:'The unseen crossing opens into a sharper, stranger annex.',transition:'apertureDoor'};
 if(o.kind==='apertureRelic'){o.state='used';gainAperture(s,3,'relic:'+context,'The Deep Lattice accepts your attention.');s.perception.discoveries.relics++;return{ok:true,message:'Fine structures flare across stone and flesh. Aperture +3.',transition:'aperture'};}
 if(o.kind==='npc'){
 const n=npcState(s,o.id);
 if(a==='attack'){recordNpcDamage(s,o,18);return{ok:true,message:n.status==='dead'?(o.name||'Vela')+' falls. The refuge remembers.':(o.name||'Vela')+' is wounded. You can stand down.',transition:'npc'};}
 if(a==='standDown'){if(n)n.disposition='spared';journalOnce(s,'spared:'+o.id,'You stood down and spared '+(o.name||o.id)+'. They remember the encounter.');return{ok:true,message:'You lower your weapon. '+(o.name||o.id)+' lives.',transition:'npc'};}
 if(a==='trade'&&(n?.disposition==='hostile'||s.consequences.settlements[o.settlement||'ember-refuge']?.status==='fallen'))return{ok:false,message:'Trade is unavailable while this resident is hostile or their settlement has fallen.'};
 if(a==='speak'&&o.id!=='vendor-vela')return{ok:true,message:o.id==='warden-oren'?'Oren: “One loss leaves a scar. Lose all three of us and nothing keeps the creatures out.”':o.id==='keeper-sela'?'Sela: “The ruined beacon will endure, even if we do not. At the Relay, restoring or severing the line is your choice.”':(o.name||'The resident')+': “Roads keep changing, but the wayglass remembers every traveler.”'};
 }
 if(o.kind==='relayTerminal'){if(a==='inspect')return{ok:true,message:'The Hollow Marshal guards this terminal. Defeat it, then choose whether to restore or sever the line.'};return commitRelay(s,a,context);}
 if(o.kind==='dungeon'&&a==='bypass'){const id=dungeonId(s.seed,s.worldGeneration,s.session.rx,s.session.ry,o.id);dungeonHistory(s,id).bypassed=true;journalOnce(s,'bypass:'+id,'You chose to leave this crossing unexplored. It remains open to a later return.','Crossings');return{ok:true,message:'Crossing left unexplored. You may return.',transition:'bypass'};}
 if((o.kind==='supplyCache'||o.kind==='weaponCache')&&a==='collect'){o.state='used';if(o.supplyType==='secondary'){const item={id:'secondary-lumen-spindle',name:'Lumen Spindle',slot:'secondary',power:4,property:'focus'};if(!s.inventory.some(i=>i.id===item.id))s.inventory.push(item);return{ok:true,message:'A Lumen Spindle joins your pack.',transition:'supply'}}s.consumables[o.supplyType]=(s.consumables[o.supplyType]||0)+1;return{ok:true,message:'Recovered '+o.supplyType+'.',transition:'supply'}}
 if(o.kind==='chest'&&a==='open'){o.state='used';return{ok:true,message:'The cache opens. Its contents are yours.',transition:'chest'};}
 if(o.kind==='shack'&&a==='inspect'){o.state='searched';const family=o.family||'timber',theme=o.theme||'roadside';s.codex.features.shelterFamilies||={};s.codex.features.shelterFamilies[family]={family,theme,name:o.name,shape:o.shape||'rect',schemaVersion:o.schemaVersion||1};journalOnce(s,`shelter-family:${family}`,`${o.name||'Shelter'} is a ${family.replace(/([A-Z])/g,' $1').toLowerCase()} structure shaped as ${o.shape||'a rectangle'}, adapted to the ${theme.replace(/-/g,' ')}. Similar sites may contain merchants, creatures, recoverable goods, hazards, or displacement mechanisms.`,'Shelter field notes');return{ok:true,message:`Recorded ${o.name}: ${family.replace(/([A-Z])/g,' $1')} · ${o.shape||'rect'} · ${theme.replace(/-/g,' ')}.`,transition:'shack'};}
 if(o.kind==='architecturalDistrict'&&a==='inspect'){const descriptions={city:'Apartment shells surround a plaza where something dragged the streetlights into a circle.',arcology:'A silent transit lattice still routes power toward rooms that no longer exist.',cloister:'Weathered sanctums face an empty court; their carved saints have been turned toward the Corridor.'},text=descriptions[o.districtStyle]||'The district keeps the shape of lives that vanished.';o.state='read';gainAperture(s,1,'district:'+context+':'+o.id,'Architecture becomes another language of the Corridor.');journalOnce(s,'district:'+context+':'+o.id,text,o.name||'Architectural ruin');return{ok:true,message:text+' Aperture +1.',transition:'district'};}
 const n=applyNarrative(o,a,s,context+':'+o.id+':'+a);if(n){if(o.kind!=='npc')o.state='used';return{...n,transition:o.kind}}
 const key=o.id+':'+a;if(o.kind==='tree'&&a==='cut'){o.state='fallen';s.worldFlags[key]=true;return{ok:true,message:o.crossingTiles?.length?'The trunk crashes across the gap, making a lasting log crossing.':o.environmental?'The tree falls and clears the ground around it.':'The ashwood falls across the fissure.'}}if(o.kind==='tree'&&a==='ignite'){o.state='charred';s.worldFlags[key]=true;return{ok:true,message:'Fire runs through the dry crown. A blackened landmark remains.'}}if(o.kind==='tree'&&a==='climb')return{ok:true,message:'You cross the high roots.'};if(o.kind==='rock'){o.state=a==='break'?'broken':'moved';s.worldFlags[key]=true;if(o.id==='rock-1')s.worldFlags['rock-1:opened']=true;return{ok:true,message:o.environmental?(a==='break'?'The boulder fractures into low rubble.':'The boulder rolls aside with a deep scrape.'):'The stone shifts. A cache glints beyond.'}}
 s.worldFlags[key]=true;return{ok:true,message:a[0].toUpperCase()+a.slice(1)+' complete.',transition:o.kind};
}
