import{rng,pick}from'./random.ts';
export const ITEM_TABLE={primary:[['Cinder Pike','reach'],['Verge Cleaver','impact']],secondary:[['Lumen Spindle','focus'],['Needle Caster','quick'],['Rift Bombard','blast']],armor:[['Kiln Mantle','guard'],['Glassweave Coat','stamina']],charm:[['Quiet Compass','discovery']]};
export const ITEM_TIERS=['common','rare','epic','relic'];
export const RANGED_WEAPONS={'spark-coil':{name:'Spark Coil',damage:8,speed:12,lifetime:1.6,damageType:'magic',path:'straight'},'secondary-lumen-spindle':{name:'Lumen Spindle',damage:11,speed:10,lifetime:1.8,turnAfter:.8,damageType:'magic',path:'boomerang'},'secondary-needle-caster':{name:'Needle Caster',damage:10,speed:15,lifetime:1.25,damageType:'physical',path:'straight'},'secondary-rift-bombard':{name:'Rift Bombard',damage:16,speed:8,lifetime:1.4,radius:2.15,damageType:'magic',path:'grenade'}};
export const PRIMARY_PROFILES={'salvage-blade':{shape:'cone',range:1.7,arc:100,damage:7},'primary-cinder-pike':{shape:'thrust',range:2.45,arc:32,damage:8},'primary-verge-cleaver':{shape:'arc',range:1.75,arc:180,damage:9}};
export const SPELLS={'cinder-dart':{id:'cinder-dart',name:'Cinder Dart',cooldown:2.5,lifetime:.8,radius:1.25,pulse:.4,damage:7,maxRange:6},'ember-ring':{id:'ember-ring',name:'Ember Ring',cooldown:6,lifetime:3,radius:2.35,pulse:.75,damage:5,maxRange:4.5},'grave-sun':{id:'grave-sun',name:'Grave Sun',cooldown:12,lifetime:4,radius:3.15,pulse:1,damage:11,maxRange:3.5}};
export const UPGRADE_CAPS={common:3,rare:4,epic:5,relic:6};
export const APERTURE_SKILLS={
 'ember-form':{id:'ember-form',name:'Ember Form',branch:'Form',threshold:6,maxRank:3,cooldown:18,duration:5,description:'Grow into a guarded striking form with greater melee reach and impact.'},
 'quickening':{id:'quickening',name:'Quickening',branch:'Motion',threshold:6,maxRank:3,cooldown:14,duration:6,description:'Move faster and lengthen the ordinary leap.'},
 'veil-guard':{id:'veil-guard',name:'Veil Guard',branch:'Veil',threshold:18,maxRank:3,cooldown:20,duration:6,description:'Harden a veil that reduces incoming damage.'},
 'force-channel':{id:'force-channel',name:'Force Channel',branch:'Force',threshold:18,maxRank:3,cooldown:16,duration:6,description:'Empower weapons, projectiles, and spell pulses.'},
 'aerial-step':{id:'aerial-step',name:'Aerial Step',branch:'Motion',threshold:36,maxRank:1,cooldown:22,duration:3.5,description:'Briefly cross water, canyons, and pits without granting true flight.'},
};
export const APERTURE_BANDS=[{id:'dormant',name:'Dormant',threshold:0},{id:'stirring',name:'Stirring',threshold:6},{id:'open',name:'Open',threshold:18},{id:'resonant',name:'Resonant',threshold:36}];
export function primaryProfile(item){if(!item)return PRIMARY_PROFILES['salvage-blade'];if(PRIMARY_PROFILES[item.id])return PRIMARY_PROFILES[item.id];if(item.name==='Cinder Pike')return PRIMARY_PROFILES['primary-cinder-pike'];if(item.name==='Verge Cleaver')return PRIMARY_PROFILES['primary-verge-cleaver'];return PRIMARY_PROFILES['salvage-blade']}
export function rangedWeapon(item){if(!item)return null;if(RANGED_WEAPONS[item.id])return RANGED_WEAPONS[item.id];if(item.name==='Lumen Spindle')return RANGED_WEAPONS['secondary-lumen-spindle'];if(item.name==='Needle Caster')return RANGED_WEAPONS['secondary-needle-caster'];if(item.name==='Rift Bombard')return RANGED_WEAPONS['secondary-rift-bombard'];return null}
export function itemTier(item){if(ITEM_TIERS.includes(item?.tier))return item.tier;const p=Math.max(1,Number(item?.power)||1);return ITEM_TIERS[Math.min(3,Math.floor((p-1)/5))]}
export function affixValue(item,id){return(item?.affixes||[]).filter(a=>a.id===id).reduce((n,a)=>n+(Number(a.value)||0),0)}
export function itemScore(item){const tier=ITEM_TIERS.indexOf(itemTier(item));return(Math.max(1,Number(item?.power)||1)*10)+tier*18+(item?.affixes||[]).reduce((n,a)=>n+Math.round((Number(a.value)||0)*10),0)+(Number(item?.upgradeRank)||0)*12}
export function describeAffixes(item){return(item?.affixes||[]).map(a=>a.id==='attack'?'+'+a.value+' attack':a.id==='reach'?'+ '+Math.round(a.value*100)+'% reach':a.id==='movement'?'+ '+Math.round(a.value*100)+'% movement speed':a.id==='ward'?'+ '+Math.round(a.value*100)+'% resistance':'+'+a.value+' '+a.id)}
export function itemMechanicalStats(item){if(!item)return{};const ranged=rangedWeapon(item),primary=primaryProfile(item),stats={power:Number(item.power)||0,attack:affixValue(item,'attack'),reach:affixValue(item,'reach'),movement:affixValue(item,'movement'),ward:affixValue(item,'ward')};if(item.slot==='primary')Object.assign(stats,{damage:primary.damage,attackRange:primary.range,attackArc:primary.arc});if(item.slot==='secondary'&&ranged)Object.assign(stats,{damage:ranged.damage,cooldown:.36,projectileSpeed:ranged.speed,projectileRange:ranged.speed*ranged.lifetime,blastRadius:ranged.radius||0});return stats}
export function compareItemStats(item,equipped){const next=itemMechanicalStats(item),current=itemMechanicalStats(equipped),ids=[...new Set([...Object.keys(next),...Object.keys(current)])],labels={power:'Power',attack:'Attack',reach:'Reach',movement:'Movement speed',ward:'Resistance',damage:'Base damage',attackRange:'Attack range',attackArc:'Attack arc',cooldown:'Cooldown',projectileSpeed:'Projectile speed',projectileRange:'Projectile range',blastRadius:'Blast radius'},percent=new Set(['reach','movement','ward']);return ids.map(id=>{const value=Number(next[id])||0,prior=Number(current[id])||0,difference=Math.round((value-prior)*100)/100,direction=!equipped?'empty':difference>0?'up':difference<0?'down':'same',formatted=percent.has(id)?Math.round(value*100)+'%':String(Math.round(value*100)/100);return{id,label:labels[id]||id,value,current:prior,difference,direction,formatted}})}
export function normalizeItemUpgrade(item){if(!item)return item;const rank=Math.max(0,Math.floor(Number(item.upgradeRank)||0)),cap=UPGRADE_CAPS[itemTier(item)],upgradeRank=Math.min(rank,cap),savedPower=Math.max(1,Math.floor(Number(item.power)||1)),recordedBase=Math.max(1,Math.floor(Number(item.basePower??savedPower)||1)),basePower=recordedBase+upgradeRank===savedPower?recordedBase:Math.max(1,savedPower-upgradeRank);return{...item,basePower,upgradeRank,power:basePower+upgradeRank}}
export function upgradeCost(item){const normalized=normalizeItemUpgrade(item),rank=normalized?.upgradeRank||0,cap=UPGRADE_CAPS[itemTier(normalized)]||3;return{kind:normalized?.slot==='armor'||normalized?.slot==='charm'?'armorSphere':'weaponSphere',amount:rank+1,rank,cap,eligible:!!normalized&&rank<cap}}
export function upgradeEquipment(save,slot){const item=save?.equipment?.[slot];if(!item)return{ok:false,message:'No compatible equipment is fitted in that slot.'};const normalized=normalizeItemUpgrade(item),cost=upgradeCost(normalized);if(!cost.eligible)return{ok:false,message:`${normalized.name} is already at its ${itemTier(normalized)} upgrade limit.`};if((save.materials?.[cost.kind]||0)<cost.amount)return{ok:false,message:`${cost.amount} ${cost.kind==='weaponSphere'?'Weapon':'Armor'} Sphere${cost.amount===1?'':'s'} required.`};save.materials[cost.kind]-=cost.amount;save.equipment[slot]=normalizeItemUpgrade({...normalized,power:normalized.power+1,upgradeRank:normalized.upgradeRank+1});return{ok:true,item:save.equipment[slot],cost,message:`${normalized.name} strengthened to +${normalized.upgradeRank+1}.`}}
export function apertureBand(value){const n=Math.max(0,Number(value)||0);return[...APERTURE_BANDS].reverse().find(b=>n>=b.threshold)||APERTURE_BANDS[0]}
export function availableApertureSkills(value){return Object.values(APERTURE_SKILLS).filter(s=>Number(value)>=s.threshold)}
export function skillRank(save,id){return Math.max(0,Math.min(APERTURE_SKILLS[id]?.maxRank||0,Number(save?.magicSkills?.learned?.[id])||0))}
export function learnApertureSkill(save,id){const skill=APERTURE_SKILLS[id];if(!skill)return{ok:false,message:'That Aperture discipline is unknown.'};if((save.perception?.aperture||0)<skill.threshold)return{ok:false,message:`Aperture ${skill.threshold} is required.`};save.magicSkills||={schema:1,learned:{},selected:null,active:null,cooldowns:{},lastSafe:null};const rank=skillRank(save,id);if(rank>=skill.maxRank)return{ok:false,message:`${skill.name} is fully learned.`};save.magicSkills.learned[id]=rank+1;save.magicSkills.selected=id;return{ok:true,rank:rank+1,message:`${skill.name} rank ${rank+1} learned.`}}
function rollAffixes(r,slot,tier){const pools={primary:['attack','reach'],secondary:['attack','reach'],armor:['ward'],charm:['movement','reach']}[slot],out=[];for(let i=0;i<tier;i++){const id=pools[i%pools.length];if(out.some(a=>a.id===id))continue;const value=id==='attack'?1+Math.floor(r()*3)+tier:id==='reach'?.08+r()*.05*tier:id==='movement'?.03+r()*.025*tier:.02+r()*.015*tier;out.push({id,value:Math.round(value*100)/100})}return out}
export function generateItem(seed,level=1){const r=rng(seed),slot=pick(r,Object.keys(ITEM_TABLE)),pair=pick(r,ITEM_TABLE[slot]),name=pair[0],property=pair[1],tier=Math.min(3,Math.floor((Math.max(1,level)+r()*5)/5));return{id:slot+'-'+Math.floor(r()*1e8),name,slot,power:Math.max(1,level+Math.floor(r()*3)),property,tier:ITEM_TIERS[tier],affixes:rollAffixes(r,slot,tier)}}
export function isValidItem(item){return !!Object.values(ITEM_TABLE).flat().find(([n,p])=>n===item.name&&p===item.property)&&['primary','secondary','armor','charm'].includes(item.slot)&&Number.isInteger(item.power)&&item.power>0&&ITEM_TIERS.includes(itemTier(item))}
