import{rng,pick}from'./random.js?v=73';
export const ITEM_TABLE={primary:[['Cinder Pike','reach'],['Verge Cleaver','impact']],secondary:[['Lumen Spindle','focus'],['Needle Caster','quick'],['Rift Bombard','blast']],armor:[['Kiln Mantle','guard'],['Glassweave Coat','stamina']],charm:[['Quiet Compass','discovery']]};
export const RANGED_WEAPONS={'spark-coil':{name:'Spark Coil',damage:8,speed:12,lifetime:1.6,damageType:'magic',path:'straight'},'secondary-lumen-spindle':{name:'Lumen Spindle',damage:11,speed:10,lifetime:1.8,turnAfter:.8,damageType:'magic',path:'boomerang'},'secondary-needle-caster':{name:'Needle Caster',damage:10,speed:15,lifetime:1.25,damageType:'physical',path:'straight'},'secondary-rift-bombard':{name:'Rift Bombard',damage:16,speed:8,lifetime:1.4,radius:2.15,damageType:'magic',path:'grenade'}};
export const PRIMARY_PROFILES={'salvage-blade':{shape:'cone',range:1.7,arc:100,damage:7},'primary-cinder-pike':{shape:'thrust',range:2.45,arc:32,damage:8},'primary-verge-cleaver':{shape:'arc',range:1.75,arc:180,damage:9}};
export const SPELLS={'cinder-dart':{id:'cinder-dart',name:'Cinder Dart',cooldown:2.5,lifetime:.8,radius:1.25,pulse:.4,damage:7,maxRange:6},'ember-ring':{id:'ember-ring',name:'Ember Ring',cooldown:6,lifetime:3,radius:2.35,pulse:.75,damage:5,maxRange:4.5},'grave-sun':{id:'grave-sun',name:'Grave Sun',cooldown:12,lifetime:4,radius:3.15,pulse:1,damage:11,maxRange:3.5}};
export function primaryProfile(item){if(!item)return PRIMARY_PROFILES['salvage-blade'];if(PRIMARY_PROFILES[item.id])return PRIMARY_PROFILES[item.id];if(item.name==='Cinder Pike')return PRIMARY_PROFILES['primary-cinder-pike'];if(item.name==='Verge Cleaver')return PRIMARY_PROFILES['primary-verge-cleaver'];return PRIMARY_PROFILES['salvage-blade']}
export function rangedWeapon(item){if(!item)return null;if(RANGED_WEAPONS[item.id])return RANGED_WEAPONS[item.id];if(item.name==='Lumen Spindle')return RANGED_WEAPONS['secondary-lumen-spindle'];if(item.name==='Needle Caster')return RANGED_WEAPONS['secondary-needle-caster'];if(item.name==='Rift Bombard')return RANGED_WEAPONS['secondary-rift-bombard'];return null}
export function generateItem(seed,level=1){const r=rng(seed),slot=pick(r,Object.keys(ITEM_TABLE)),[name,property]=pick(r,ITEM_TABLE[slot]);return{id:`${slot}-${Math.floor(r()*1e8)}`,name,slot,power:Math.max(1,level+Math.floor(r()*3)),property}}
export function isValidItem(item){return !!Object.values(ITEM_TABLE).flat().find(([n,p])=>n===item.name&&p===item.property)&&['primary','secondary','armor','charm'].includes(item.slot)&&Number.isInteger(item.power)&&item.power>0}
