import{rng,pick}from'./random.js?v=86';
export const ITEM_TABLE={primary:[['Cinder Pike','reach'],['Verge Cleaver','impact']],secondary:[['Lumen Spindle','focus'],['Needle Caster','quick'],['Rift Bombard','blast']],armor:[['Kiln Mantle','guard'],['Glassweave Coat','stamina']],charm:[['Quiet Compass','discovery']]};
export const ITEM_TIERS=['common','rare','epic','relic'];
export const RANGED_WEAPONS={'spark-coil':{name:'Spark Coil',damage:8,speed:12,lifetime:1.6,damageType:'magic',path:'straight'},'secondary-lumen-spindle':{name:'Lumen Spindle',damage:11,speed:10,lifetime:1.8,turnAfter:.8,damageType:'magic',path:'boomerang'},'secondary-needle-caster':{name:'Needle Caster',damage:10,speed:15,lifetime:1.25,damageType:'physical',path:'straight'},'secondary-rift-bombard':{name:'Rift Bombard',damage:16,speed:8,lifetime:1.4,radius:2.15,damageType:'magic',path:'grenade'}};
export const PRIMARY_PROFILES={'salvage-blade':{shape:'cone',range:1.7,arc:100,damage:7},'primary-cinder-pike':{shape:'thrust',range:2.45,arc:32,damage:8},'primary-verge-cleaver':{shape:'arc',range:1.75,arc:180,damage:9}};
export const SPELLS={'cinder-dart':{id:'cinder-dart',name:'Cinder Dart',cooldown:2.5,lifetime:.8,radius:1.25,pulse:.4,damage:7,maxRange:6},'ember-ring':{id:'ember-ring',name:'Ember Ring',cooldown:6,lifetime:3,radius:2.35,pulse:.75,damage:5,maxRange:4.5},'grave-sun':{id:'grave-sun',name:'Grave Sun',cooldown:12,lifetime:4,radius:3.15,pulse:1,damage:11,maxRange:3.5}};
export function primaryProfile(item){if(!item)return PRIMARY_PROFILES['salvage-blade'];if(PRIMARY_PROFILES[item.id])return PRIMARY_PROFILES[item.id];if(item.name==='Cinder Pike')return PRIMARY_PROFILES['primary-cinder-pike'];if(item.name==='Verge Cleaver')return PRIMARY_PROFILES['primary-verge-cleaver'];return PRIMARY_PROFILES['salvage-blade']}
export function rangedWeapon(item){if(!item)return null;if(RANGED_WEAPONS[item.id])return RANGED_WEAPONS[item.id];if(item.name==='Lumen Spindle')return RANGED_WEAPONS['secondary-lumen-spindle'];if(item.name==='Needle Caster')return RANGED_WEAPONS['secondary-needle-caster'];if(item.name==='Rift Bombard')return RANGED_WEAPONS['secondary-rift-bombard'];return null}
export function itemTier(item){if(ITEM_TIERS.includes(item?.tier))return item.tier;const p=Math.max(1,Number(item?.power)||1);return ITEM_TIERS[Math.min(3,Math.floor((p-1)/5))]}
export function affixValue(item,id){return(item?.affixes||[]).filter(a=>a.id===id).reduce((n,a)=>n+(Number(a.value)||0),0)}
export function itemScore(item){const tier=ITEM_TIERS.indexOf(itemTier(item));return(Math.max(1,Number(item?.power)||1)*10)+tier*18+(item?.affixes||[]).reduce((n,a)=>n+Math.round((Number(a.value)||0)*10),0)}
export function describeAffixes(item){return(item?.affixes||[]).map(a=>a.id==='attack'?'+'+a.value+' attack':a.id==='reach'?'+ '+Math.round(a.value*100)+'% reach':a.id==='movement'?'+ '+Math.round(a.value*100)+'% movement speed':a.id==='ward'?'+ '+Math.round(a.value*100)+'% resistance':'+'+a.value+' '+a.id)}
export function compareItemStats(item,equipped){const ids=['power',...new Set([...(item?.affixes||[]).map(a=>a.id),...(equipped?.affixes||[]).map(a=>a.id)])],labels={power:'Power',attack:'Attack',reach:'Reach',movement:'Movement',ward:'Resistance'},percent=new Set(['reach','movement','ward']);return ids.map(id=>{const value=id==='power'?Number(item?.power)||0:affixValue(item,id),current=id==='power'?Number(equipped?.power)||0:affixValue(equipped,id),difference=Math.round((value-current)*100)/100,direction=difference>0?'up':difference<0?'down':'same',formatted=percent.has(id)?Math.round(value*100)+'%':String(value);return{id,label:labels[id]||id,value,current,difference,direction,formatted}})}
function rollAffixes(r,slot,tier){const pools={primary:['attack','reach'],secondary:['attack','reach'],armor:['ward'],charm:['movement','reach']}[slot],out=[];for(let i=0;i<tier;i++){const id=pools[i%pools.length];if(out.some(a=>a.id===id))continue;const value=id==='attack'?1+Math.floor(r()*3)+tier:id==='reach'?.08+r()*.05*tier:id==='movement'?.03+r()*.025*tier:.02+r()*.015*tier;out.push({id,value:Math.round(value*100)/100})}return out}
export function generateItem(seed,level=1){const r=rng(seed),slot=pick(r,Object.keys(ITEM_TABLE)),pair=pick(r,ITEM_TABLE[slot]),name=pair[0],property=pair[1],tier=Math.min(3,Math.floor((Math.max(1,level)+r()*5)/5));return{id:slot+'-'+Math.floor(r()*1e8),name,slot,power:Math.max(1,level+Math.floor(r()*3)),property,tier:ITEM_TIERS[tier],affixes:rollAffixes(r,slot,tier)}}
export function isValidItem(item){return !!Object.values(ITEM_TABLE).flat().find(([n,p])=>n===item.name&&p===item.property)&&['primary','secondary','armor','charm'].includes(item.slot)&&Number.isInteger(item.power)&&item.power>0&&ITEM_TIERS.includes(itemTier(item))}
