import { hashSeed } from "./random.js?v=91";

export const SCENE_SCHEMA = "infinite-corridor-scene/1.0.0";
export const SCENE_DEFINITIONS = Object.freeze({
  "rift-arrival": { id:"rift-arrival", version:1, title:"The Shape Beyond Glass", kind:"illustrated", trigger:"first-singular-monster", replay:true, skippable:true, commit:{fact:"scene.riftArrival"}, shots:[{panel:0,duration:2600,camera:"push",effect:"distortion",caption:"The breach does not open. It remembers being open."},{panel:0,duration:2400,camera:"pan",effect:"embers",caption:"Something vast teaches the glass its outline."}] },
  "memorial-release": { id:"memorial-release", version:1, title:"Embers That Remember", kind:"illustrated", trigger:"deep-story-resolution", replay:true, skippable:true, commit:{fact:"scene.memorialRelease"}, shots:[{panel:1,duration:2800,camera:"still",effect:"apparition",caption:"The dead wait where the roots cannot forget them."},{panel:1,duration:2600,camera:"push",effect:"fade",caption:"At last, one memory is permitted to end."}] },
  "relay-awakening": { id:"relay-awakening", version:1, title:"The Relay Answers", kind:"illustrated", trigger:"relay-chain", replay:true, skippable:true, commit:{fact:"scene.relayAwakening"}, shots:[{panel:2,duration:2500,camera:"pan",effect:"signal",caption:"A line of amber fire crosses the ruined sky."},{panel:2,duration:2200,camera:"push",effect:"fog",caption:"Far machinery answers with an impossible coordinate."}] },
  "aperture-rite": { id:"aperture-rite", version:2, title:"Rite at the Aperture", kind:"in-world", trigger:"aperture-ritual-object", replay:true, skippable:true, commit:{fact:"scene.apertureRite"}, actors:[{id:"wayfarer",label:"Wayfarer"},{id:"witness",label:"Array Witness"}], shots:[{panel:3,duration:2400,camera:"push",effect:"roots",caption:"Two figures repeat a gesture older than the gate.",choreography:[{actor:"wayfarer",cue:"enter-left",to:[42,62]},{actor:"witness",cue:"approach",to:[61,55]}]},{panel:3,duration:2300,camera:"shake",effect:"aperture",caption:"The Corridor makes room for their answer.",choreography:[{actor:"wayfarer",cue:"raise",to:[45,57]},{actor:"witness",cue:"answer",to:[58,52]}]},{panel:3,duration:1800,camera:"still",effect:"fade",caption:"The witness departs. The changed route remains.",choreography:[{actor:"wayfarer",cue:"hold",to:[46,57]},{actor:"witness",cue:"vanish",to:[72,46]}]}] },
});

export function freshSceneState(){return{schema:SCENE_SCHEMA,witnessed:{},pending:null,completed:{}}}
export function ensureSceneState(save){const b=freshSceneState(),s=save.scenes||{};save.scenes={...b,...s,witnessed:{...s.witnessed},completed:{...s.completed},pending:s.pending&&SCENE_DEFINITIONS[s.pending.sceneId]?{...s.pending}:null};return save.scenes}
export function sceneDefinition(id){return SCENE_DEFINITIONS[id]||null}
export function sceneVariant(save,id,encounter="default"){const def=sceneDefinition(id);return def?hashSeed(`${save.seed}:${id}:${encounter}:${def.version}`)%3:null}
export function queueScene(save,id,encounter="default"){const state=ensureSceneState(save),def=sceneDefinition(id);if(!def||state.pending||state.witnessed[id])return false;state.pending={sceneId:id,variant:sceneVariant(save,id,encounter),shot:0,elapsed:0,encounter};return true}
export function commitScene(save,id){const state=ensureSceneState(save),def=sceneDefinition(id);if(!def)return false;const first=!state.completed[id];state.witnessed[id]=true;state.completed[id]=true;if(first&&def.commit?.fact)save.narrative.facts[def.commit.fact]=true;if(first&&id==="aperture-rite"&&!save.narrative.journal.some(q=>q.recordId==="scene:aperture-rite"))save.narrative.journal.push({recordId:"scene:aperture-rite",instanceKey:"record:scene:aperture-rite",title:"Rite at the Aperture",text:"At Ember Refuge, an Array witness answered the Wayfarer's gesture. The Corridor made room for a changed route.",provenance:"original"});if(state.pending?.sceneId===id)state.pending=null;return first}
export function sceneFinalState(save,id){return{witnessed:!!ensureSceneState(save).witnessed[id],fact:!!save.narrative?.facts?.[SCENE_DEFINITIONS[id]?.commit?.fact]}}
export function scenePlaybackPlan(save,id,{reduceMotion=false,quality="high",replay=false}={}){const state=ensureSceneState(save),def=sceneDefinition(id);if(!def||(!replay&&state.witnessed[id]))return null;const limited=reduceMotion||quality==="low"||quality==="safe",pending=!replay&&state.pending?.sceneId===id?state.pending:null;return{...def,variant:pending?.variant??sceneVariant(save,id,replay?"replay":"live"),replay,startShot:pending?.shot||0,layers:limited?1:quality==="medium"?2:3,shots:def.shots.map(s=>({...s,duration:reduceMotion?Math.max(1600,s.duration*.7):s.duration,camera:limited?"still":s.camera,effect:limited?"fade":s.effect,choreography:(s.choreography||[]).slice(0,4).map(c=>({...c,cue:limited?"hold":c.cue}))}))}}
export function apertureRitualState(save){const completed=!!ensureSceneState(save).completed["aperture-rite"],aperture=Number(save.perception?.aperture)||0,relay=!!save.narrative?.facts?.["crossing.complete"],hunt=Object.values(save.viewport?.contracts||{}).some(q=>q.status==="completed");return{completed,aperture,relay,hunt,ready:!completed&&aperture>=12&&relay&&hunt}}
export function requestApertureRitual(save){const state=apertureRitualState(save);if(state.completed)return{ok:true,queued:false,message:"The Aperture plinth remembers the completed rite. Its scene can be replayed from the Journal."};if(!state.ready){const missing=[];if(state.aperture<12)missing.push("a wider Aperture");if(!state.relay)missing.push("a resolved Relay");if(!state.hunt)missing.push("one completed Viewport hunt");return{ok:false,queued:false,message:`The plinth answers, but the rite cannot begin. It requires ${missing.join(", ")}.`}}const queued=queueScene(save,"aperture-rite","ember-refuge-plinth");return queued?{ok:true,queued:true,message:"The Aperture plinth answers. A witness steps out of the Array's light."}:{ok:false,queued:false,message:"Another memory is already unfolding. The rite remains available when it ends."}}
export function recoverInterruptedScene(save){const state=ensureSceneState(save);if(!state.pending)return null;const id=state.pending.sceneId,def=sceneDefinition(id);if(!def){state.pending=null;return null}state.pending.shot=Math.max(0,Math.min(def.shots.length-1,Number(state.pending.shot)||0));state.pending.elapsed=0;return state.pending}
export function replayableScenes(save){const state=ensureSceneState(save);return Object.values(SCENE_DEFINITIONS).filter(q=>q.replay&&state.witnessed[q.id])}
