import { hashSeed } from "./random.ts";

export const SCENE_SCHEMA = "infinite-corridor-scene/1.0.0";
export const SCENE_DEFINITIONS = Object.freeze({
  "rift-arrival": { id:"rift-arrival", version:1, title:"The Shape Beyond Glass", kind:"illustrated", trigger:"first-singular-monster", replay:true, skippable:true, commit:{fact:"scene.riftArrival"}, shots:[{panel:0,duration:2600,camera:"push",effect:"distortion",caption:"The breach does not open. It remembers being open."},{panel:0,duration:2400,camera:"pan",effect:"embers",caption:"Something vast teaches the glass its outline."}] },
  "memorial-release": { id:"memorial-release", version:1, title:"Embers That Remember", kind:"illustrated", trigger:"deep-story-resolution", replay:true, skippable:true, commit:{fact:"scene.memorialRelease"}, shots:[{panel:1,duration:2800,camera:"still",effect:"apparition",caption:"The dead wait where the roots cannot forget them."},{panel:1,duration:2600,camera:"push",effect:"fade",caption:"At last, one memory is permitted to end."}] },
  "relay-awakening": { id:"relay-awakening", version:1, title:"The Relay Answers", kind:"illustrated", trigger:"relay-chain", replay:true, skippable:true, commit:{fact:"scene.relayAwakening"}, shots:[{panel:2,duration:2500,camera:"pan",effect:"signal",caption:"A line of amber fire crosses the ruined sky."},{panel:2,duration:2200,camera:"push",effect:"fog",caption:"Far machinery answers with an impossible coordinate."}] },
  "aperture-rite": { id:"aperture-rite", version:1, title:"Rite at the Aperture", kind:"in-world", trigger:"story-actor", replay:true, skippable:true, commit:{fact:"scene.apertureRite"}, actors:[{id:"wayfarer",pose:"raise-sigil"},{id:"witness",pose:"answer"}], shots:[{panel:3,duration:2400,camera:"still",effect:"roots",caption:"Two figures repeat a gesture older than the gate."},{panel:3,duration:2300,camera:"shake",effect:"aperture",caption:"The Corridor makes room for their answer."}] },
});

export function freshSceneState(){return{schema:SCENE_SCHEMA,witnessed:{},pending:null,completed:{}}}
export function ensureSceneState(save){const b=freshSceneState(),s=save.scenes||{};save.scenes={...b,...s,witnessed:{...s.witnessed},completed:{...s.completed},pending:s.pending&&SCENE_DEFINITIONS[s.pending.sceneId]?{...s.pending}:null};return save.scenes}
export function sceneDefinition(id){return SCENE_DEFINITIONS[id]||null}
export function sceneVariant(save,id,encounter="default"){const def=sceneDefinition(id);return def?hashSeed(`${save.seed}:${id}:${encounter}:${def.version}`)%3:null}
export function queueScene(save,id,encounter="default"){const state=ensureSceneState(save),def=sceneDefinition(id);if(!def||state.pending||state.witnessed[id])return false;state.pending={sceneId:id,variant:sceneVariant(save,id,encounter),shot:0,elapsed:0,encounter};return true}
export function commitScene(save,id){const state=ensureSceneState(save),def=sceneDefinition(id);if(!def)return false;const first=!state.completed[id];state.witnessed[id]=true;state.completed[id]=true;if(first&&def.commit?.fact)save.narrative.facts[def.commit.fact]=true;if(state.pending?.sceneId===id)state.pending=null;return first}
export function sceneFinalState(save,id){return{witnessed:!!ensureSceneState(save).witnessed[id],fact:!!save.narrative?.facts?.[SCENE_DEFINITIONS[id]?.commit?.fact]}}
export function scenePlaybackPlan(save,id,{reduceMotion=false,quality="high",replay=false}={}){const def=sceneDefinition(id);if(!def||(!replay&&ensureSceneState(save).witnessed[id]))return null;return{...def,variant:sceneVariant(save,id,replay?"replay":"live"),replay,layers:quality==="low"||quality==="safe"?1:quality==="medium"?2:3,shots:def.shots.map(s=>({...s,duration:reduceMotion?Math.max(1600,s.duration*.7):s.duration,camera:reduceMotion?"still":s.camera,effect:reduceMotion?"fade":s.effect}))}}
export function recoverInterruptedScene(save){const state=ensureSceneState(save);if(!state.pending)return null;const id=state.pending.sceneId,def=sceneDefinition(id);if(!def){state.pending=null;return null}state.pending.shot=Math.max(0,Math.min(def.shots.length-1,Number(state.pending.shot)||0));state.pending.elapsed=0;return state.pending}
export function replayableScenes(save){const state=ensureSceneState(save);return Object.values(SCENE_DEFINITIONS).filter(q=>q.replay&&state.witnessed[q.id])}
