import{hashSeed}from'./random.ts';
export const CORRIDOR_STORY_SCHEMA='corridor-revelations/1.0.0',STEWARD_SCHEMA='world-steward/1.0.0';
const bounded=(o,n=32)=>Object.fromEntries(Object.entries(o||{}).slice(-n));
const journal=(s,id,title,text,category='observation')=>{if(!s.narrative.journal.some(q=>q.recordId===id))s.narrative.journal.push({recordId:id,instanceKey:'record:'+id,title,text,category,provenance:'original'})};
export function freshCorridorStory(){return{schema:CORRIDOR_STORY_SCHEMA,arcs:{cartographersEcho:{id:'cartographers-echo-v1',status:'dormant',leads:{},rewardClaimed:false,completed:false,delayed:false,unlockedAtSections:null,site:null}},tendencies:{connection:0,stability:0,autonomy:0,preservation:0,visibility:0}}}
export function freshWorldSteward(){return{schema:STEWARD_SCHEMA,sections:0,maxDepth:0,lastSection:null,encounters:{ordinary:0,passive:0,elite:0,guardian:0,boss:0,singular:0,foundry:0},defeats:{ordinary:0,elite:0,guardian:0,boss:0,foundry:0},creatureKinds:{},foundryCandidates:{},systems:{wayglasses:0,arrays:0,shelters:0,dungeons:0,waterBarriers:0,canyonBarriers:0},storyBeats:0,lastMajorDiscoverySection:0}}
export function ensureCorridorSystems(s){const bs=freshCorridorStory(),old=s.story||{},bw=freshWorldSteward(),w=s.worldSteward||{};s.story={...bs,...old,arcs:{...bs.arcs,...old.arcs,cartographersEcho:{...bs.arcs.cartographersEcho,...old.arcs?.cartographersEcho,leads:{...old.arcs?.cartographersEcho?.leads}}},tendencies:{...bs.tendencies,...old.tendencies}};s.worldSteward={...bw,...w,encounters:{...bw.encounters,...w.encounters},defeats:{...bw.defeats,...w.defeats},creatureKinds:bounded(w.creatureKinds),foundryCandidates:bounded(w.foundryCandidates),systems:{...bw.systems,...w.systems}};return s}
export function revelationTarget(seed){const n=hashSeed(`${seed}:story:cartographers-echo:site`),sx=n&1?1:-1,sy=n&2?1:-1;return{rx:sx*(6+n%4),ry:sy*(5+(n>>>4)%4),x:16,y:16}}
export function recordRevelationLead(s,kind,context='world'){ensureCorridorSystems(s);const arc=s.story.arcs.cartographersEcho;if(arc.completed||arc.leads[kind])return false;arc.leads[kind]={context};arc.status='discovered';s.worldSteward.storyBeats++;journal(s,`cartographers-echo:${kind}`,'An impossible correspondence',{signal:'The signal contains a route measured from a place the Atlas has never recorded.',hunt:'The creature carried a glass filament etched with the same coordinate grammar as a Wayglass.',displacement:'For an instant, the displacement crossing showed a city arranged around your own path.'}[kind]||'Another unrelated discovery repeats the same impossible coordinate.','observation');if(Object.keys(arc.leads).length>=2&&!arc.site){arc.site=revelationTarget(s.seed);arc.status='site-revealed';s.worldSteward.lastMajorDiscoverySection=s.worldSteward.sections;journal(s,'cartographers-echo:site','The Cartographer’s Echo','Two unrelated traces reconcile into one remote coordinate. The Atlas can now recognize its violet signal, but not what waits there.','unresolved-pattern')}return true}
export function storySiteFor(s,rx,ry){ensureCorridorSystems(s);const arc=s.story.arcs.cartographersEcho,q=arc.site;if(!q||arc.completed||q.rx!==rx||q.ry!==ry)return null;return{id:'cartographers-echo-site',kind:'storyEcho',name:'The Unwritten Meridian',x:q.x,y:q.y,state:'unread',actions:['inspect'],landmark:true,storyArc:arc.id}}
export function completeRevelationArc(s){ensureCorridorSystems(s);const arc=s.story.arcs.cartographersEcho;if(arc.completed)return{ok:true,message:'The Meridian repeats the route it already entrusted to you.'};arc.completed=true;arc.status='locally-resolved';arc.unlockedAtSections=Object.keys(s.explored||{}).length+4;if(!arc.rewardClaimed){arc.rewardClaimed=true;const item={id:'echo-compass',name:'Echo Compass',slot:'charm',power:5,property:'reach',affixes:{attackReach:.08,moveSpeed:.03}};if(!s.inventory.some(q=>q.id===item.id)&&s.equipment.charm?.id!==item.id)s.inventory.push(item);s.materials.weaponSphere=(s.materials.weaponSphere||0)+1}s.codex.places['unwritten-meridian']={encountered:1,category:'confirmed',name:'The Unwritten Meridian'};s.worldSteward.storyBeats++;s.worldSteward.lastMajorDiscoverySection=s.worldSteward.sections;journal(s,'cartographers-echo:complete','The Unwritten Meridian','A chamber of obsolete maps recognizes your route as if it preceded you. It yields an Echo Compass and one weapon sphere, then erases every destination except a city that cannot occupy one location.','confirmed');return{ok:true,message:'The Meridian resolves locally — Echo Compass and weapon sphere recovered. One impossible city remains unplaced.',transition:'storyArc'}}
export function recordSectionVisit(s,rx,ry,region){ensureCorridorSystems(s);const w=s.worldSteward,key=`${rx},${ry}`;w.sections=Math.max(w.sections,Object.keys(s.explored||{}).length);w.maxDepth=Math.max(w.maxDepth,Math.abs(rx)+Math.abs(ry));w.lastSection=key;const kinds=new Set((region?.objects||[]).map(o=>o.kind));if(kinds.has('checkpoint'))w.systems.wayglasses++;if(kinds.has('shrine'))w.systems.arrays++;if(kinds.has('shack'))w.systems.shelters++;if(kinds.has('dungeon'))w.systems.dungeons++;if(region?.environment?.kind==='river')w.systems.waterBarriers++;if(region?.environment?.kind==='canyon')w.systems.canyonBarriers++;const arc=s.story.arcs.cartographersEcho;if(arc.completed&&!arc.delayed&&Object.keys(s.explored||{}).length>=arc.unlockedAtSections){arc.delayed=true;arc.status='echo-propagating';s.story.tendencies.visibility++;w.storyBeats++;w.lastMajorDiscoverySection=w.sections;journal(s,'cartographers-echo:delayed','The route answers back','Four crossings later, an unknown Wayglass speaks in your own voice: “The city is not ahead of you. It is assembling from the paths you preserve.” No destination accompanies the message.','unresolved-pattern')}return w}
export function recordCreatureEncounter(s,e){ensureCorridorSystems(s);const w=s.worldSteward,kind=e.kind||'unknown';w.creatureKinds[kind]=(w.creatureKinds[kind]||0)+1;const tier=e.foundryId?'foundry':e.ambient?'passive':e.eliteId?'elite':e.dungeonRole?'guardian':e.boss?'boss':'ordinary';w.encounters[tier]=(w.encounters[tier]||0)+1;if(e.foundryId)w.foundryCandidates[e.foundryId]={role:e.foundryRole,name:e.foundryName,encountered:(w.foundryCandidates[e.foundryId]?.encountered||0)+1,defeated:w.foundryCandidates[e.foundryId]?.defeated||0};return tier}
export function recordCreatureDefeat(s,e){ensureCorridorSystems(s);const w=s.worldSteward,tier=e.foundryId?'foundry':e.eliteId?'elite':e.dungeonRole?'guardian':e.boss?'boss':'ordinary';w.defeats[tier]=(w.defeats[tier]||0)+1;if(e.foundryId){const q=w.foundryCandidates[e.foundryId]||{role:e.foundryRole,name:e.foundryName,encountered:1,defeated:0};q.defeated++;w.foundryCandidates[e.foundryId]=q}return tier}
export function worldStewardReport(s){ensureCorridorSystems(s);const w=s.worldSteward,recommendations=[],known=Object.keys(w.creatureKinds).length,gap=w.sections-w.lastMajorDiscoverySection;if(w.sections>=20&&known<8)recommendations.push({category:'ecology',reason:'few creature families across sustained exploration',suggestion:'add a bounded regional species'});if(gap>=18)recommendations.push({category:'story',reason:`${gap} explored sections since a major discovery`,suggestion:'add or surface one revelation entry point'});if(w.systems.waterBarriers>=6&&!s.capabilities?.swim)recommendations.push({category:'traversal',reason:'repeated water barriers without a traversal answer',suggestion:'prepare the first water-survival progression quest'});if(w.encounters.foundry>=4&&Object.keys(w.foundryCandidates).length<2)recommendations.push({category:'foundry',reason:'experimental ecology is repeating',suggestion:'review a new validated candidate family'});return{schema:STEWARD_SCHEMA,progressionBand:Math.min(9,Math.floor((s.level||1)/5)),sections:w.sections,maxDepth:w.maxDepth,knownCreatureKinds:known,recommendations:recommendations.slice(0,4)}}
