import{freshEliteState,ensureEliteState}from'./elites.js?v=72';
export const SAVE_VERSION=10,WORLD_GENERATION=1,LEGACY_WORLD_GENERATION=0,STATS=['Might','Finesse','Focus','Vigor','Resolve'];
const perception=()=>({schema:1,aperture:0,passiveSeconds:0,awarded:{},announcedTier:0,discoveries:{memories:0,doors:0,relics:0}});const runtime=()=>({hp:60,stamina:50,attackCooldown:0,attackMotion:0,meleeMotion:0,meleeAim:null,meleeStrike:null,dodgeCooldown:0,invulnerability:0,dodgeMotion:0,jump:0,guard:0,traversal:null});const session=()=>({area:'overworld',rx:0,ry:0,x:16,y:16,message:'The refuge beacon speaks your name before you arrive: “Wayfarer. Crossing incomplete.”',paused:false,savedAt:Date.now(),playerRuntime:runtime(),areas:{},dungeonReturn:null,veilReturn:null,activeDungeonId:null});const narrative=()=>({schema:'infinite-corridor-narrative/1.0.0',journal:[{recordId:'crossing-beacon',instanceKey:'record:crossing-beacon',title:'The Missing Crossing',text:'The beacon knew me before I arrived. It called the crossing incomplete.',provenance:'original'}],facts:{'crossing.beacon':true},appliedInstanceKeys:{'record:crossing-beacon':true},selectedVariants:{}});
const codex=()=>({creatures:{},places:{},features:{},variants:{}});
export function freshSave(){return{version:10,worldGeneration:1,name:'Wayfarer',seed:'CINDER-VERGE-47',level:1,xp:0,nextXp:30,statPoints:0,stats:{Might:1,Finesse:1,Focus:1,Vigor:1,Resolve:1},hp:60,maxHp:60,stamina:50,maxStamina:50,currency:8,consumables:{restorativeDraught:3,ironbarkTonic:1,lumenPhial:1,crossingSigil:0,clearrootAmpoule:0},materials:{cinderIron:0,lumenDust:0,weaponSphere:0,armorSphere:0},equipment:{primary:{id:'salvage-blade',name:'Salvage Blade',slot:'primary',power:6,property:'steady'},secondary:{id:'spark-coil',name:'Spark Coil',slot:'secondary',power:3,property:'focus'},armor:{id:'ash-wrap',name:'Ash Wrap',slot:'armor',power:1,property:'guard'},charm:null},inventory:[],weaponLevel:0,activeWeaponSlot:'primary',equippedTool:'secondary',toolMode:false,equippedSpell:'ember-ring',spellCooldown:0,lastAim:{x:0,y:1},pendingAim:null,magicBuff:0,dropCounter:0,worldFlags:{},position:{area:'overworld',rx:0,ry:0,x:16,y:16},session:session(),explored:{'0,0':true},checkpoints:{'0,0':{rx:0,ry:0,x:16,y:16,name:'Ember Refuge'}},activeCheckpoint:{rx:0,ry:0,x:16,y:16,name:'Ember Refuge'},waypoint:null,codex:codex(),elites:freshEliteState(),consequences:freshConsequences(),narrative:narrative(),updatedAt:Date.now()}}
function moveKeys(s,seed,g){for(const[a,b]of[['overworld:0:0',`overworld:0:0:g${g}`],[`dungeon:${seed}`,`dungeon:${seed}:g${g}`]])if(s.areas[a]&&!s.areas[b]){s.areas[b]=s.areas[a];delete s.areas[a]}}
function migrateLegacySave(raw){if(!raw||typeof raw!=='object')return freshSave();const b=freshSave(),old=raw.session||{},pos=raw.position||{},legacy=raw.version<3,g=legacy?0:(raw.worldGeneration??1),aim=raw.lastAim||b.lastAim,m=Math.hypot(Number(aim.x)||0,Number(aim.y)||0)||1,s={...session(),...old,area:old.area||pos.area||'overworld',rx:old.rx||0,ry:old.ry||0,x:Number.isFinite(old.x)?old.x:(pos.x??16),y:Number.isFinite(old.y)?old.y:(pos.y??16),playerRuntime:{...runtime(),...old.playerRuntime,hp:old.playerRuntime?.hp??raw.hp??60,stamina:old.playerRuntime?.stamina??raw.stamina??50},areas:{...old.areas}};moveKeys(s,raw.seed||b.seed,g);if(raw.version>=1&&raw.version<=9){if(s.area==='dungeon'&&!s.activeDungeonId)s.activeDungeonId=`dungeon:${raw.seed||b.seed}:g${g}`;return{...b,...raw,version:9,worldGeneration:g,activeWeaponSlot:raw.activeWeaponSlot==='secondary'?'secondary':'primary',equippedTool:raw.equippedTool||'secondary',toolMode:!!raw.toolMode,equippedSpell:raw.equippedSpell||'ember-ring',spellCooldown:Math.max(0,Number(raw.spellCooldown)||0),lastAim:{x:(Number(aim.x)||0)/m,y:(Number(aim.y)||0)/m},pendingAim:raw.pendingAim&&Number.isFinite(raw.pendingAim.x)&&Number.isFinite(raw.pendingAim.y)?{x:raw.pendingAim.x,y:raw.pendingAim.y}:null,magicBuff:Math.max(0,Number(raw.magicBuff)||0),dropCounter:Math.max(0,Number(raw.dropCounter)||0),consumables:{...b.consumables,...raw.consumables},session:s,narrative:{...narrative(),...raw.narrative,journal:[...(raw.narrative?.journal||[])],facts:{...raw.narrative?.facts},appliedInstanceKeys:{...raw.narrative?.appliedInstanceKeys},selectedVariants:{...raw.narrative?.selectedVariants}},position:{area:s.area,rx:s.rx,ry:s.ry,x:s.x,y:s.y},stats:{...b.stats,...raw.stats},worldFlags:{...raw.worldFlags},explored:{'0,0':true,...raw.explored},checkpoints:{...b.checkpoints,...raw.checkpoints},codex:{creatures:{...raw.codex?.creatures},places:{...raw.codex?.places},features:{...raw.codex?.features}}}}return b}
export const REFUGE_NPCS=[
 {id:'vendor-vela',name:'Vela Quen',role:'Quartermaster',x:17,y:15,actions:['speak','trade','attack','standDown']},
 {id:'warden-oren',name:'Oren Vale',role:'Refuge Warden',x:14,y:15,actions:['speak','attack','standDown']},
 {id:'keeper-sela',name:'Sela Rook',role:'Beacon Keeper',x:16,y:18,actions:['speak','attack','standDown']}
];
export const WAYSTATION_NPCS=[
 {id:'vendor-iona',name:'Iona Vey',role:'Glasshaven Factor',x:16,y:15,settlement:'glasshaven',actions:['speak','trade','attack','standDown']},
 {id:'resident-tarn',name:'Tarn Coil',role:'Glasswright',x:14,y:17,settlement:'glasshaven',actions:['speak','attack','standDown']},
 {id:'vendor-mora',name:'Mora Kest',role:'Coilmarket Provisioner',x:16,y:15,settlement:'coilmarket',actions:['speak','trade','attack','standDown']},
 {id:'resident-esh',name:'Esh Nine',role:'Signal Cartographer',x:18,y:17,settlement:'coilmarket',actions:['speak','attack','standDown']}
];
export function freshConsequences(){const all=[...REFUGE_NPCS,...WAYSTATION_NPCS];return{schema:1,npcs:Object.fromEntries(all.map(n=>[n.id,{hp:36,status:'alive',disposition:'neutral'}])),settlements:{'ember-refuge':{status:'standing',reputation:0},glasshaven:{status:'standing',reputation:0},coilmarket:{status:'standing',reputation:0}},choices:{},threads:{'ember-refuge':{status:'open',ending:null},'missing-crossing':{status:'open',ending:null}},dungeons:{}}}
export function migrateSave(raw){
 const input=raw?.version===10?{...raw,version:9}:raw,s=migrateLegacySave(input),base=freshConsequences(),old=s.consequences||{};
 s.codex={...codex(),...s.codex,creatures:{...s.codex?.creatures},places:{...s.codex?.places},features:{...s.codex?.features},variants:{...s.codex?.variants}};
 s.consequences={...base,...old,npcs:{...base.npcs,...old.npcs},settlements:{...base.settlements,...old.settlements},choices:{...old.choices},threads:{...base.threads,...old.threads},dungeons:{...old.dungeons}};
 for(const n of REFUGE_NPCS){const prior=s.consequences.npcs[n.id];s.consequences.npcs[n.id]={...base.npcs[n.id],...prior};if(s.worldFlags[n.id+':dead'])Object.assign(s.consequences.npcs[n.id],{hp:0,status:'dead'});}
 if((s.narrative.facts['crossing.restored']||s.narrative.facts['crossing.complete'])&&!s.narrative.facts['crossing.severed']&&!s.consequences.choices.relay)s.consequences.choices.relay='restore';
 const canonical='dungeon:'+s.seed+':g'+s.worldGeneration;
 for(const[id,area]of Object.entries(s.session.areas)){if(!id.startsWith('dungeon:'))continue;const defeated=(area.enemies||[]).some(e=>e.kind==='hollowMarshal'&&e.dead);if(!s.consequences.dungeons[id])s.consequences.dungeons[id]={discovered:true,bypassed:false,visits:1,abandoned:0,guardianDefeated:defeated,resolved:id===canonical?!!s.consequences.choices.relay:defeated,visitOpen:false};}
 if(s.session.area==='dungeon'&&s.session.activeDungeonId){const id=s.session.activeDungeonId;s.consequences.dungeons[id]||={discovered:true,bypassed:false,visits:1,abandoned:0,guardianDefeated:false,resolved:false};if(s.consequences.dungeons[id].visitOpen===undefined)s.consequences.dungeons[id].visitOpen=true;}
 if(s.consequences.choices.relay){s.consequences.dungeons[canonical]||={discovered:true,bypassed:false,visits:1,abandoned:0};Object.assign(s.consequences.dungeons[canonical],{guardianDefeated:true,resolved:true});}
 if(REFUGE_NPCS.every(n=>s.consequences.npcs[n.id].status==='dead'))s.consequences.settlements['ember-refuge'].status='fallen';
 if(s.consequences.settlements['ember-refuge'].status==='fallen')s.consequences.threads['ember-refuge']={status:'resolved',ending:'fallen'};
 if(s.consequences.choices.relay)s.consequences.threads['missing-crossing']={status:'resolved',ending:s.consequences.choices.relay};
 s.version=10;ensureEliteState(s);return ensurePerception(s);
}
export function ensurePerception(s){const b=perception(),p=s.perception||{};s.perception={...b,...p,aperture:Math.max(0,Number(p.aperture)||0),passiveSeconds:Math.max(0,Number(p.passiveSeconds)||0),awarded:{...p.awarded},discoveries:{...b.discoveries,...p.discoveries}};if(s.session&&s.session.veilReturn===undefined)s.session.veilReturn=null;return s}
