import{REFUGE_NPCS,WAYSTATION_NPCS}from'./types.ts';
import{rng,pick}from'./random.ts';export const SECTION_SIZE=32,PASSAGE_WIDTH=3;const terrain=['ash','glass','ember'];
function passage(seed,axis,a,b){const r=rng(`${seed}:edge:${axis}:${a}:${b}`);return 5+Math.floor(r()*22)}export function sectionExits(seed,rx,ry){return{north:passage(seed,'h',rx,ry),south:passage(seed,'h',rx,ry+1),west:passage(seed,'v',rx,ry),east:passage(seed,'v',rx+1,ry)}}
function carve(tiles,x,y,kind='ash'){if(kind==='refuge'&&x===12&&y===17)return;if(x>=0&&x<32&&y>=0&&y<32)tiles[y*32+x]={...tiles[y*32+x],x,y,kind,blocked:false}}
function supply(seed,rx,ry,tiles,w=32){const r=rng(`${seed}:supplies:v2:${rx}:${ry}`),rare=w===32&&r()<.06,types=['restorativeDraught','ironbarkTonic','lumenPhial','secondary'],spots=w===24?[[6,6],[7,6],[6,7]]:[[15,17],[17,17],[15,18],[17,18]],[x,y]=spots[Math.floor(r()*spots.length)],supplyType=rare?'crossingSigil':types[Math.floor(r()*types.length)];return{id:`supply-${rx}-${ry}`,kind:supplyType==='secondary'?'weaponCache':'supplyCache',supplyType,x,y,state:'ready',actions:['collect']}}
export function generateLegacyOrigin(seed){const r=rng(`${seed}:region:0:0`),tiles=[];for(let y=0;y<32;y++)for(let x=0;x<32;x++){const edge=r(),kind=edge<.16?'blocked':pick(r,terrain);tiles.push({x,y,kind,blocked:kind==='blocked'})}for(let y=13;y<20;y++)for(let x=13;x<20;x++)tiles[y*32+x]={x,y,kind:'refuge',blocked:false};return{seed,rx:0,ry:0,dominant:'ash',exits:null,legacy:true,tiles,objects:[{id:'tree-1',kind:'tree',x:8,y:15,state:'standing',actions:['cut','climb']},{id:'rock-1',kind:'rock',x:23,y:18,state:'sealed',actions:['move','break']},{id:'shrine-1',kind:'shrine',x:19,y:8,state:'quiet',actions:['inspect']},{id:'door-ruin',kind:'door',x:27,y:8,state:'closed',actions:['open','force']},{id:'dungeon-gate',kind:'dungeon',x:5,y:5,state:'open',actions:['enter']},{id:'vendor-vela',kind:'npc',x:17,y:15,state:'calm',actions:['speak','trade','attack']},{id:'cache-1',kind:'cache',x:24,y:18,state:'hidden',actions:['open']},{id:'world-boss',kind:'bossCue',x:28,y:27,state:'dormant',actions:['challenge']},supply(seed,0,0,tiles)],enemySpawns:[{kind:'ashling',x:11,y:7},{kind:'glassMite',x:20,y:23},{kind:'sparkWarden',x:25,y:12}]}}
function structured(seed,rx,ry,generation){const r=rng(`${seed}:region:g${generation}:${rx}:${ry}`),dominant=pick(r,terrain),tiles=[];for(let y=0;y<32;y++)for(let x=0;x<32;x++){const patch=(Math.floor(x/7)+Math.floor(y/6)+Math.floor(r()*2))%3,kind=r()<.76?dominant:terrain[patch];tiles.push({x,y,kind,blocked:x===0||y===0||x===31||y===31,detail:Math.floor(r()*4)})}const ruins=2+Math.floor(r()*2);for(let i=0;i<ruins;i++){const ox=3+Math.floor(r()*19),oy=3+Math.floor(r()*19),w=5+Math.floor(r()*5),h=4+Math.floor(r()*6),door=1+Math.floor(r()*(w-2));for(let y=oy;y<oy+h;y++)for(let x=ox;x<ox+w;x++)if((x===ox||x===ox+w-1||y===oy||y===oy+h-1)&&!(y===oy+h-1&&x===ox+door))tiles[y*32+x]={...tiles[y*32+x],kind:'blocked',blocked:true,ruin:i}}const exits=sectionExits(seed,rx,ry);for(let d=-1;d<=1;d++){for(let y=0;y<=16;y++)carve(tiles,exits.north+d,y,dominant);for(let y=16;y<32;y++)carve(tiles,exits.south+d,y,dominant);for(let x=0;x<=16;x++)carve(tiles,x,exits.west+d,dominant);for(let x=16;x<32;x++)carve(tiles,x,exits.east+d,dominant)}for(let y=14;y<=18;y++)for(let x=14;x<=18;x++)carve(tiles,x,y,rx===0&&ry===0?'refuge':dominant);const prefix=`${rx},${ry}`,objects=[];if(rx===0&&ry===0)objects.push({id:'tree-1',kind:'tree',x:8,y:15,state:'standing',actions:['cut','climb']},{id:'rock-1',kind:'rock',x:23,y:18,state:'sealed',actions:['move','break']},{id:'shrine-1',kind:'shrine',x:19,y:8,state:'quiet',actions:['inspect']},{id:'door-ruin',kind:'door',x:27,y:8,state:'closed',actions:['open','force']},{id:'dungeon-gate',kind:'dungeon',x:5,y:5,state:'open',actions:['enter']},{id:'vendor-vela',kind:'npc',x:17,y:15,state:'calm',actions:['speak','trade','attack']},{id:'cache-1',kind:'cache',x:24,y:18,state:'hidden',actions:['open']},{id:'world-boss',kind:'bossCue',x:28,y:27,state:'dormant',actions:['challenge']});else{const roll=r(),kind=roll<.07?'checkpoint':roll<.54?'shrine':'ruinMarker',x=12+Math.floor(r()*8),y=12+Math.floor(r()*8);objects.push({id:`landmark-${prefix}`,kind,x,y,state:'quiet',actions:kind==='checkpoint'?['activate']:['inspect'],landmark:true,name:kind==='checkpoint'?'Wayglass Beacon':kind==='shrine'?'Singing Array':'Broken Observatory'})}const pools={ash:['ashling','ashenHound','cinderWisp'],glass:['glassMite','coilStalker','veilMoth'],ember:['sparkWarden','rootBrute','cinderWisp']}[dominant],enemySpawns=[{kind:pick(r,pools),x:7+Math.floor(r()*7),y:6+Math.floor(r()*6)},{kind:pick(r,pools),x:18+Math.floor(r()*7),y:20+Math.floor(r()*6)},{kind:pick(r,[...pools,'sparkWarden']),x:22+Math.floor(r()*5),y:8+Math.floor(r()*7)}];if(Math.abs(rx)+Math.abs(ry)>3)enemySpawns.push({kind:pick(r,pools),x:8+Math.floor(r()*16),y:10+Math.floor(r()*12)});for(const e of [...objects,...enemySpawns])carve(tiles,e.x,e.y,dominant);return{seed,rx,ry,dominant,exits,legacy:false,ruinCount:ruins,tiles,objects,enemySpawns}}
function bandOffset(seed,band,segment){return Math.floor(rng(`${seed}:environment:v1:band:${band}:${segment}`)()*9)-4}
function bandCenter(seed,band,gx){const segment=Math.floor(gx/32),t=(gx-segment*32)/32,a=bandOffset(seed,band,segment),b=bandOffset(seed,band,segment+1);return band*96+48+Math.round(a+(b-a)*t)}
function addEnvironment(region,seed,rx,ry,generation){
 const weatherRoll=rng(`${seed}:weather:v1:g${generation}:${rx}:${ry}`)();region.weather=weatherRoll<.24?'rain':weatherRoll<.39?'snow':weatherRoll<.58?'sunbreak':'still';
 if(generation===0||region.settlement||rx===0&&ry===0)return;
 const protectedCells=[...region.objects,...region.enemySpawns],globalMidY=ry*32+16,band=Math.round((globalMidY-48)/96),feature=rng(`${seed}:environment:v1:type:${band}`)()<.55?'river':'canyon',width=feature==='river'?1:2;
 let touched=false;
 for(let y=0;y<32;y++)for(let x=0;x<32;x++){const gx=rx*32+x,gy=ry*32+y,tile=region.tiles[y*32+x];if(Math.abs(gy-bandCenter(seed,band,gx))<=width){region.tiles[y*32+x]={...tile,kind:feature,blocked:true,environment:feature};touched=true}}
 if(touched){
  for(let x=15;x<=17;x++)for(let y=1;y<31;y++)if(region.tiles[y*32+x]?.environment)region.tiles[y*32+x]={...region.tiles[y*32+x],kind:'bridge',blocked:false,bridgeOver:feature};
  for(const p of protectedCells)for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const t=region.tiles[(p.y+oy)*32+p.x+ox];if(t?.environment)region.tiles[(p.y+oy)*32+p.x+ox]={...t,kind:'bridge',blocked:false,bridgeOver:feature}}
  region.environment={kind:feature,band,bridgeX:16};
 }
 const r=rng(`${seed}:environment:v1:props:g${generation}:${rx}:${ry}`),occupied=new Set(protectedCells.map(o=>`${o.x},${o.y}`)),place=(kind,count)=>{for(let made=0,tries=0;made<count&&tries<160;tries++){const x=3+Math.floor(r()*26),y=3+Math.floor(r()*26),tile=region.tiles[y*32+x],key=`${x},${y}`;if(tile.blocked||tile.kind==='bridge'||occupied.has(key)||Math.hypot(x-16,y-16)<4)continue;occupied.add(key);region.objects.push({id:`env-${kind}-${rx}-${ry}-${made}`,kind,x,y,state:kind==='tree'?'standing':'sealed',actions:kind==='tree'?['cut','ignite']:['move','break'],environmental:true});made++}};
 if(touched){const crossX=r()<.5?7:24,ys=[];for(let y=1;y<31;y++)if(region.tiles[y*32+crossX]?.environment)ys.push(y);if(ys.length){const north=Math.min(...ys)-1,south=Math.max(...ys)+1,treeY=region.tiles[north*32+crossX]&&!region.tiles[north*32+crossX].blocked?north:south;if(treeY>1&&treeY<30&&!region.tiles[treeY*32+crossX].blocked){occupied.add(`${crossX},${treeY}`);region.objects.push({id:`crossing-tree-${rx}-${ry}`,kind:'tree',x:crossX,y:treeY,state:'standing',actions:['cut','ignite'],environmental:true,crossingTiles:ys.map(y=>({x:crossX,y}))})}}}
 place('tree',8+Math.floor(r()*5));place('rock',3+Math.floor(r()*4));
 if(r()<.3){for(let tries=0;tries<40;tries++){const sw=6+Math.floor(r()*4),sh=5+Math.floor(r()*3),sx=3+Math.floor(r()*(27-sw)),sy=3+Math.floor(r()*(27-sh)),doorX=sx+Math.floor((sw-1)/2),cells=[];for(let y=sy;y<sy+sh;y++)for(let x=sx;x<sx+sw;x++)cells.push(region.tiles[y*32+x]);if(cells.some(t=>t.blocked||t.kind==='bridge')||sx<=18&&sx+sw-1>=14||sy<=18&&sy+sh-1>=14||protectedCells.some(p=>p.x>=sx-1&&p.x<=sx+sw&&p.y>=sy-1&&p.y<=sy+sh))continue;const facadeStyle=pick(r,['pilgrim','relay','chapel','workshop']),roofProfile=pick(r,['gable','shed','stepped']),condition=pick(r,['weathered','patched','collapsed','overgrown','kept']),entranceWidth=sw>=8&&r()<.65?2:1,entrances=[];for(let q=0;q<entranceWidth;q++)entrances.push({x:doorX+q,y:sy+sh-1,side:'south'});if(sw>=7&&sh>=6&&r()<.55){const side=pick(r,['north','east','west']);entrances.push(side==='north'?{x:sx+1+Math.floor(r()*(sw-2)),y:sy,side}:{x:side==='east'?sx+sw-1:sx,y:sy+1+Math.floor(r()*(sh-2)),side})}if(condition==='collapsed'&&r()<.6)entrances.push({x:sx,y:sy,side:'corner'});const opening=new Set(entrances.map(e=>`${e.x},${e.y}`));for(let y=sy;y<sy+sh;y++)for(let x=sx;x<sx+sw;x++){const wall=x===sx||x===sx+sw-1||y===sy||y===sy+sh-1,door=opening.has(`${x},${y}`);region.tiles[y*32+x]={...region.tiles[y*32+x],kind:wall&&!door?'blocked':region.dominant,blocked:wall&&!door,structure:door?'shackDoor':'shack',buildingId:`shack-${rx}-${ry}`,doorSide:entrances.find(e=>e.x===x&&e.y===y)?.side}}region.objects.push({id:`shack-${rx}-${ry}`,kind:'shack',name:facadeStyle==='chapel'?'Wayside Chapel':facadeStyle==='relay'?'Relay Shelter':facadeStyle==='workshop'?'Salvager Workshop':'Wayfarer Shack',x:sx+Math.floor(sw/2),y:sy+Math.floor(sh/2),state:'quiet',actions:['inspect'],environmental:true,bounds:{x:sx,y:sy,w:sw,h:sh},door:{x:doorX,y:sy+sh-1,side:'south',width:entranceWidth},entrances,facadeStyle,roofProfile,condition,signGlyph:Math.floor(r()*6)});break}}
}
function thinShelterWalls(region){
 const ordinary=region.objects.find(o=>o.kind==='checkpoint'&&String(o.id).startsWith('landmark-'));
 if(ordinary&&rng(`${region.seed}:wayglass-sparsity:v1:${region.rx}:${region.ry}`)()>=.36){ordinary.kind='shrine';ordinary.name='Singing Array';ordinary.actions=['inspect']}
 for(const shelter of region.objects.filter(o=>o.kind==='shack')){
  const b=shelter.bounds,openings=new Set((shelter.entrances||[]).map(e=>`${e.x},${e.y}`));
  for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++){
   const tile=region.tiles[y*32+x],door=openings.has(`${x},${y}`),wall=x===b.x||x===b.x+b.w-1||y===b.y||y===b.y+b.h-1,wallSides=[];
   if(wall&&!door){if(x===b.x)wallSides.push('west');if(x===b.x+b.w-1)wallSides.push('east');if(y===b.y)wallSides.push('north');if(y===b.y+b.h-1)wallSides.push('south')}
   region.tiles[y*32+x]={...tile,kind:region.dominant,blocked:false,structure:door?'shackDoor':wall?'shackWall':'shackInterior',wallSides,buildingId:shelter.id};
  }
 }
 const shelter=region.objects.find(o=>o.kind==='shack');if(!shelter)return;
 const r=rng(String(region.seed)+':shelter-surprise:v1:'+region.rx+':'+region.ry);if(r()>=.28)return;
 const b=shelter.bounds,spots=[];for(let y=b.y+1;y<b.y+b.h-1;y++)for(let x=b.x+1;x<b.x+b.w-1;x++)if(!region.tiles[y*32+x].blocked)spots.push({x,y});
 if(!spots.length)return;const spot=spots[Math.floor(r()*spots.length)],roll=r(),id='shelter-surprise-'+region.rx+'-'+region.ry;
 if(roll<.34)region.objects.push({id,kind:'shelterMerchant',name:pick(r,['The Lantern Broker','Moss-Cloaked Factor','The Quiet Provisioner']),role:'Wandering specialist',...spot,state:'calm',actions:['speak','trade'],shelterId:shelter.id});
 else if(roll<.68)region.objects.push({id,kind:'shelterCreature',name:pick(r,['Hearth Moth','Pilgrim Coil','Velvet Scavenger']),...spot,state:'watching',gift:pick(r,['marks','aperture','lumen']),actions:['commune'],shelterId:shelter.id});
 else if(roll<.84)region.objects.push({id,kind:'displacementDevice',name:'Mislaid Threshold',...spot,state:'armed',actions:['enter'],shelterId:shelter.id,landmark:true});
 else region.enemySpawns.push({kind:pick(r,['ashling','glassMite','ashenHound','coilStalker']),...spot,shelterAmbush:true});
}
function annotateVegetation(region){for(const o of region.objects.filter(q=>q.kind==='tree')){const r=rng(`${region.seed}:vegetation:v1:${o.id}`);o.vegetationForm=o.crossingTiles?.length?'canopy':pick(r,['canopy','shrub','spindle']);o.scale=o.vegetationForm==='canopy'?1.25:o.vegetationForm==='shrub'?.72:1.05}}
function addAmbientFauna(region,seed,rx,ry,generation){if(region.settlement||rx===0&&ry===0)return;const r=rng(`${seed}:ambient-fauna:v1:g${generation}:${rx}:${ry}`);if(r()>.42)return;const open=region.tiles.filter(t=>!t.blocked&&!t.structure&&t.x>3&&t.x<28&&t.y>3&&t.y<28),species=[['mossGrazer','graze'],['lanternDoe','follow'],['hushling','vanish']],count=r()<.24?2:1;for(let i=0;i<count&&open.length;i++){const at=open.splice(Math.floor(r()*open.length),1)[0],[kind,passiveBehavior]=pick(r,species);region.enemySpawns.push({kind,x:at.x,y:at.y,ambient:true,passiveBehavior})}}
const ROADSIDE_FORMS=[
 {style:'pilgrim',name:'Wayfarer Shack'},
 {style:'relay',name:'Relay Shelter'},
 {style:'chapel',name:'Wayside Chapel'},
 {style:'workshop',name:'Salvager Workshop'},
 {style:'stoneCottage',name:'Abandoned Stone House'},
 {style:'ruinedKeep',name:'Dilapidated Keep',roof:'stepped'},
 {style:'gatehouse',name:'Broken Gatehouse',roof:'stepped'},
 {style:'shrineHouse',name:'Forgotten Shrine House'},
];
function diversifyShelters(region){
 const r=rng(`${region.seed}:roadside-form:v2:${region.rx}:${region.ry}`);
 for(const shelter of region.objects.filter(o=>o.kind==='shack')){
  const form=pick(r,ROADSIDE_FORMS);shelter.facadeStyle=form.style;shelter.name=form.name;
  if(form.roof)shelter.roofProfile=form.roof;
 }
}
const DISTRICT_STYLES={city:{name:'Hollow Ward',floor:'cityFloor',wall:'cityWall',enemy:'ashenHound'},arcology:{name:'Lumen Arcology',floor:'arcologyFloor',wall:'arcologyWall',enemy:'coilStalker'},cloister:{name:'Thorn Cloister',floor:'cloisterFloor',wall:'cloisterWall',enemy:'veilMoth'},fortress:{name:'Broken Citadel',floor:'cityFloor',wall:'cityWall',enemy:'rootBrute'}};
const BUILDING_USES={city:['market','infirmary','tenement','apartments','civic-hall'],arcology:['signal-lab','transit-archive','defense-post','reactor-house','habitat'],cloister:['cathedral','abbey','scriptorium','reliquary','chapter-house'],fortress:['ruined-keep','gatehouse','watch-fort','fallen-palace','bastion']};
function addArchitecturalDistrict(region,seed,rx,ry,generation){
 if(generation===0||rx===0&&ry===0||region.settlement)return;
 const r=rng(`${seed}:district:v3:g${generation}:${rx}:${ry}`);if(r()>=.32)return;
 const style=pick(r,Object.keys(DISTRICT_STYLES)),meta=DISTRICT_STYLES[style],protectedCells=[...region.objects.filter(o=>!o.environmental),...region.enemySpawns],routes=region.exits,
 candidates=[{corner:'nw',door:'south',edges:['north','west']},{corner:'ne',door:'south',edges:['north','east']},{corner:'sw',door:'north',edges:['south','west']},{corner:'se',door:'north',edges:['south','east']}].map(q=>{const w=9+Math.floor(r()*4),h=8+Math.floor(r()*4),x=q.corner.endsWith('e')?29-w:3,y=q.corner.startsWith('s')?29-h:3,shape=pick(r,style==='fortress'?['keep','courtyard','lshape','hshape']:style==='cloister'?['cross','courtyard','lshape']:['rect','lshape','hshape','cross']);return{...q,x,y,w,h,shape}}),buildings=[];
 const crossesRoute=b=>routes&&b.edges.some(edge=>(edge==='north'||edge==='south')?routes[edge]>=b.x-1&&routes[edge]<=b.x+b.w:routes[edge]>=b.y-1&&routes[edge]<=b.y+b.h),occupied=b=>protectedCells.some(p=>p.x>=b.x&&p.x<b.x+b.w&&p.y>=b.y&&p.y<b.y+b.h),badTerrain=b=>{for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++){const t=region.tiles[y*32+x];if(footprint(b,x,y)&&(t?.environment||t?.kind==='bridge'))return true}return false};
 const footprint=(b,x,y)=>{const lx=x-b.x,ly=y-b.y;if(lx<0||ly<0||lx>=b.w||ly>=b.h)return false;if(b.shape==='lshape')return lx<4||ly>=b.h-4||(b.door==='north'&&ly<2);if(b.shape==='cross')return Math.abs(lx-(b.w-1)/2)<2||Math.abs(ly-(b.h-1)/2)<2;if(b.shape==='hshape')return lx<3||lx>=b.w-3||Math.abs(ly-(b.h-1)/2)<1.5||(b.door==='south'?ly>=b.h-2:ly<2);if(b.shape==='courtyard')return lx<3||lx>=b.w-3||ly<3||ly>=b.h-3;return true};
 for(const b of candidates){if(crossesRoute(b)||occupied(b)||badTerrain(b))continue;const doorX=b.x+Math.floor((b.w-1)/2),doorY=b.door==='south'?b.y+b.h-1:b.y,cells=[];for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++)if(footprint(b,x,y))cells.push({x,y});const set=new Set(cells.map(c=>`${c.x},${c.y}`)),entranceWidth=b.w>=9&&r()<.7?2:1,entrances=[];for(let q=0;q<entranceWidth;q++)if(set.has(`${doorX+q},${doorY}`))entrances.push({x:doorX+q,y:doorY,side:b.door});if((b.w>=9||b.h>=8)&&r()<.7){const side=pick(r,['east','west']),x=side==='east'?b.x+b.w-1:b.x;for(let d=0;d<b.h-2;d++){const y=b.y+1+(Math.floor(b.h/2)+d)%(b.h-2);if(set.has(`${x},${y}`)){entrances.push({x,y,side});break}}}buildings.push({...b,doorX,doorY,id:`district-building-${rx}-${ry}-${buildings.length}`,cells,entrances});if(buildings.length===3)break}
 if(buildings.length<2)return;
 region.objects=region.objects.filter(o=>!o.environmental||!buildings.some(b=>o.x>=b.x&&o.x<b.x+b.w&&o.y>=b.y&&o.y<b.y+b.h));
 for(const [i,b] of buildings.entries()){const set=new Set(b.cells.map(c=>`${c.x},${c.y}`)),openings=new Map(b.entrances.map(e=>[`${e.x},${e.y}`,e])),inside=[];for(const c of b.cells){const edge=[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>!set.has(`${c.x+dx},${c.y+dy}`)),opening=openings.get(`${c.x},${c.y}`),wall=edge&&!opening,structure=opening?'districtDoor':wall?'districtWall':'districtInterior';region.tiles[c.y*32+c.x]={...region.tiles[c.y*32+c.x],kind:wall?meta.wall:meta.floor,blocked:wall,structure,districtStyle:style,buildingId:b.id,doorSide:opening?.side};if(!wall)inside.push({x:c.x,y:c.y})}b.interior=inside;for(const e of b.entrances){const ox=e.side==='east'?1:e.side==='west'?-1:0,oy=e.side==='south'?1:e.side==='north'?-1:0;carve(region.tiles,e.x+ox,e.y+oy,meta.floor)}}
 region.district={style,name:meta.name,buildingCount:buildings.length};region.objects.push({id:`district-${rx}-${ry}`,kind:'architecturalDistrict',name:meta.name,x:16,y:16,state:'unread',actions:['inspect'],landmark:true,districtStyle:style});
 for(const [i,b] of buildings.entries()){const use=pick(r,BUILDING_USES[style]),roofProfile=style==='fortress'?pick(r,['flat','stepped']):pick(r,['gable','flat','stepped','spire']),facadeRhythm=pick(r,['paired','narrow','broad']),accent=pick(r,['copper','ivory','oxide','violet']),signGlyph=Math.floor(r()*8),anchor=b.interior[Math.floor(b.interior.length/2)]||b.cells[0];region.objects.push({id:b.id,kind:'architecturalBuilding',name:`${meta.name} ${use.replace('-',' ')}`,x:anchor.x,y:anchor.y,state:'quiet',actions:[],bounds:{x:b.x,y:b.y,w:b.w,h:b.h},door:{x:b.doorX,y:b.doorY,side:b.door,width:b.entrances.filter(e=>e.side===b.door).length},entrances:b.entrances,districtStyle:style,facadeHeight:1+i%3,shape:b.shape,footprint:b.cells,buildingUse:use,roofProfile,facadeRhythm,accent,signGlyph})}
 const den=buildings[0],denSpot=den.interior.find(c=>Math.abs(c.x-den.doorX)+Math.abs(c.y-den.doorY)>2)||den.interior[den.interior.length-1];region.enemySpawns.push({kind:meta.enemy,x:denSpot.x,y:denSpot.y,districtResident:true});
}
function addDungeonLandmark(region,seed,rx,ry,generation){if(rx===0&&ry===0||generation===0)return;const r=rng(`${seed}:dungeon-entrance:v1:g${generation}:${rx}:${ry}`);if(r()>=.28)return;const spots=[];for(let y=4;y<28;y++)for(let x=4;x<28;x++)if(!region.tiles[y*32+x].blocked&&Math.hypot(x-16,y-16)>5)spots.push([x,y]);if(!spots.length)return;const[x,y]=spots[Math.floor(r()*spots.length)],id=`dungeon-g${generation}-${rx}-${ry}-${Math.floor(r()*1e6)}`,d=dungeonDescriptor(dungeonId(seed,generation,rx,ry,id));region.objects.push({id,kind:'dungeon',x,y,state:'open',actions:['enter'],landmark:true,name:d.name,identity:d.identity});carve(region.tiles,x,y,region.dominant)}
function addSettlement(region,rx,ry){const key=`${rx},${ry}`,config=key==='4,-2'?{id:'glasshaven',name:'Glasshaven',people:['vendor-iona','resident-tarn']}:key==='-5,3'?{id:'coilmarket',name:'Coilmarket',people:['vendor-mora','resident-esh']}:null;if(!config)return;region.settlement=config;for(let y=12;y<=19;y++)for(let x=12;x<=20;x++)carve(region.tiles,x,y,'refuge');region.objects=region.objects.filter(o=>!o.landmark);region.objects.push({id:`beacon-${config.id}`,kind:'checkpoint',x:16,y:18,state:'quiet',actions:['activate'],landmark:true,name:config.name+' Wayglass'});for(const id of config.people){const n=WAYSTATION_NPCS.find(q=>q.id===id);region.objects.push({...n,kind:'npc',state:'calm',maxHp:36})}region.enemySpawns=region.enemySpawns.filter(e=>Math.hypot(e.x-16,e.y-16)>7)}
function addCreatureTraits(region,seed,rx,ry,generation){const r=rng(`${seed}:traits:v2:g${generation}:${rx}:${ry}`),sr=rng(`${seed}:void-sentinel:v1:g${generation}:${rx}:${ry}`),depth=Math.abs(rx)+Math.abs(ry),ranged=new Set(['sparkWarden','veilMoth','coilStalker','cinderWisp','voidSentinel']);for(const e of region.enemySpawns){if(depth>7&&sr()<.018)e.kind='voidSentinel';e.traits=[];const pool=['plated','feral','swift','vital','keen',...(ranged.has(e.kind)?['farcasting']:[]),...(depth>5&&r()<.18?['orbital']:[])],count=depth>6&&r()<.55?2:depth>1&&r()<.7?1:0;while(e.traits.length<count){const trait=pick(r,pool);if(e.traits.includes(trait)||trait==='feral'&&e.traits.includes('plated')||trait==='plated'&&e.traits.includes('feral'))continue;e.traits.push(trait)}}}
export function generateRegion(seed,rx,ry,generation=1){const region=generation===0&&rx===0&&ry===0?generateLegacyOrigin(seed):structured(seed,rx,ry,generation);addCreatureTraits(region,seed,rx,ry,generation);addSettlement(region,rx,ry);addDungeonLandmark(region,seed,rx,ry,generation);if(rx===0&&ry===0){for(const n of REFUGE_NPCS){const existing=region.objects.find(o=>o.id===n.id);if(existing)Object.assign(existing,n,{settlement:'ember-refuge',maxHp:36});else region.objects.push({...n,kind:'npc',state:'calm',settlement:'ember-refuge',maxHp:36});carve(region.tiles,n.x,n.y,'refuge');}}if(region.settlement||rx===0&&ry===0){region.objects.push({id:'signal-ledger-'+rx+'-'+ry,kind:'questBoard',name:'Signal Ledger',x:12,y:17,state:'ready',actions:['inspect']});carve(region.tiles,12,17,'refuge');region.enemySpawns=region.enemySpawns.filter(e=>Math.hypot(e.x-16,e.y-16)>9)}for(const o of region.objects)if(o.kind==='dungeon')o.actions=['enter','bypass'];if(!region.objects.some(o=>o.id===`supply-${rx}-${ry}`))region.objects.push(supply(seed,rx,ry,region.tiles));addEnvironment(region,seed,rx,ry,generation);diversifyShelters(region);thinShelterWalls(region);addArchitecturalDistrict(region,seed,rx,ry,generation);annotateVegetation(region);addAmbientFauna(region,seed,rx,ry,generation);return region}
const SITE_KINDS=new Set(['checkpoint','dungeon','shrine','ruinMarker','shack','bossCue','architecturalDistrict']);
export function sectionSites(seed,rx,ry,generation=1,save=null){const r=generateRegion(seed,rx,ry,generation),sites=r.objects.filter(o=>SITE_KINDS.has(o.kind)).map(o=>({kind:o.kind,name:o.name||({checkpoint:'Wayglass Beacon',dungeon:'Buried Crossing',shrine:'Singing Array',ruinMarker:'Broken Observatory',shack:'Wayfarer Shack',bossCue:'Major Threat',architecturalDistrict:'Architectural Ruin'}[o.kind]||o.kind),x:o.x,y:o.y})),remembered=save?.checkpoints?.[`${rx},${ry}`];if(remembered&&!sites.some(o=>o.kind==='checkpoint'))sites.push({kind:'checkpoint',name:remembered.name||'Remembered Wayglass',x:Number.isFinite(remembered.x)?remembered.x:16,y:Number.isFinite(remembered.y)?remembered.y:16,remembered:true});return sites}
export function sectionSummary(seed,rx,ry,generation=1,save=null){const r=generateRegion(seed,rx,ry,generation),sites=sectionSites(seed,rx,ry,generation,save),l=r.objects.find(o=>o.landmark)||r.objects.find(o=>['dungeon','shrine','door'].includes(o.kind));return{rx,ry,terrain:r.dominant,landmark:l?.name||({dungeon:'Hollow Relay Gate',shrine:'Quiet Array',door:'Abandoned Relay'}[l?.kind]||'No recorded landmark'),sites,checkpoint:!!save?.checkpoints?.[`${rx},${ry}`],current:save?.session?.rx===rx&&save?.session?.ry===ry,waypoint:save?.waypoint?.rx===rx&&save?.waypoint?.ry===ry}}
export function wayfindingCues(seed,rx,ry,generation=1,save=null,region=null){
  const targets=[],seen=new Set(),add=(kind,x,y,name)=>{const key=`${kind}:${x},${y}`;if((x!==rx||y!==ry)&&!seen.has(key)){seen.add(key);targets.push({kind,rx:x,ry:y,name})}};
  for(const c of Object.values(save?.checkpoints||{}))if(Number.isFinite(c?.rx)&&Number.isFinite(c?.ry))add('beacon',c.rx,c.ry,c.name||'Wayglass');
  if(!save?.worldFlags?.worldBossDead)add('danger',0,0,'a great enemy');
  for(let radius=1;radius<=4;radius++)for(let oy=-radius;oy<=radius;oy++)for(let ox=-radius;ox<=radius;ox++){
    if(Math.abs(ox)+Math.abs(oy)!==radius)continue;
    const q=generateRegion(seed,rx+ox,ry+oy,generation);
    if(q.objects.some(o=>o.kind==='dungeon'))add('crossing',rx+ox,ry+oy,'a buried crossing');
    if(q.objects.some(o=>o.kind==='shrine'||o.kind==='ruinMarker'))add('event',rx+ox,ry+oy,'an unusual site');
  }
  const chosen=[];
  for(const kind of ['beacon','crossing','danger','event']){
    const matches=targets.filter(t=>t.kind===kind).sort((a,b)=>(Math.abs(a.rx-rx)+Math.abs(a.ry-ry))-(Math.abs(b.rx-rx)+Math.abs(b.ry-ry)));
    if(matches[0])chosen.push(matches[0]);
  }
  const map=region||generateRegion(seed,rx,ry,generation),spots=[[14,13],[17,13],[19,16],[17,19],[13,18],[11,15],[20,19]];
  return chosen.slice(0,4).map((target,i)=>{
    const spot=spots.slice(i).concat(spots.slice(0,i)).find(([x,y])=>!map.tiles[y*32+x]?.blocked)||[16,16],dx=Math.sign(target.rx-rx),dy=Math.sign(target.ry-ry);
    return{id:`waymark-${target.kind}`,kind:'wayfindingCue',signalKind:target.kind,x:spot[0],y:spot[1],dirX:dx,dirY:dy,targetRx:target.rx,targetRy:target.ry,name:target.name,state:'quiet',actions:[]};
  });
}
export function dungeonId(seed,generation=1,rx=0,ry=0,objectId='dungeon-gate'){return rx===0&&ry===0&&objectId==='dungeon-gate'?`dungeon:${seed}:g${generation}`:`dungeon:${seed}:g${generation}:${rx}:${ry}:${objectId}`}
export function dungeonRecipe(id){if(!id||!/:[^:]+:[^:]+:[^:]+$/.test(id))return'hollow';const n=[...id].reduce((a,c)=>(a*33+c.charCodeAt(0))>>>0,5381)%3;return['hollow','cistern','kiln'][n]}
export const APERTURE_THRESHOLDS=[6,18,36];
export function apertureTier(value){const n=Math.max(0,Number(value)||0);return n>=36?3:n>=18?2:n>=6?1:0}
export function apertureEncounterSpawns(seed,areaId,value,tiles,width=32){const tier=apertureTier(value);if(!tier)return[];const r=rng(`${seed}:aperture-encounter:v1:${areaId}`),chance=[0,.12,.2,.3][tier];if(r()>=chance)return[];const open=tiles.filter(t=>!t.blocked&&t.x>3&&t.y>3&&t.x<width-3&&t.y<width-3),spot=open[Math.floor(r()*open.length)];if(!spot)return[];const kinds=[['ashenHound','coilStalker'],['rootBrute','sparkWarden','coilStalker'],['rootBrute','hollowMarshal','sparkWarden']][tier-1],traits=[['keen','swift'],['vital','feral','farcasting'],['vital','plated','orbital']][tier-1];return[{kind:pick(r,kinds),x:spot.x,y:spot.y,traits:traits.slice(0,tier),apertureEncounter:true,apertureTier:tier,threatMultiplier:1+.4*tier}]}
export function regionalThreat(rx=0,ry=0){const ring=Math.floor(Math.hypot(Number(rx)||0,Number(ry)||0)),near=Math.min(10,ring),far=Math.max(0,ring-10);return{ring,hpMultiplier:1+.08*near+.04*far,damageMultiplier:1+.05*near+.025*far,xpMultiplier:1+.06*ring}}
export function perceived(entity,save){if(entity?.kind==='apertureDoor'&&!save?.consequences?.dungeons?.[save?.session?.activeDungeonId]?.resolved)return false;return!entity?.apertureRequired||(save?.perception?.aperture||0)>=entity.apertureRequired}
export function perceptionOverlay(seed,areaId,tiles,width=24){const r=rng(`${seed}:aperture:v1:${areaId}`),open=tiles.filter(t=>!t.blocked&&t.x>5&&t.y>5&&t.x<width-3&&t.y<width-3),pickOpen=()=>open[Math.floor(r()*open.length)]||{x:8,y:8},memory=pickOpen(),door=pickOpen(),relic=pickOpen();return{objects:[{id:'aperture-memory',kind:'apertureMemory',name:'Veiled Inscription',x:memory.x,y:memory.y,state:'quiet',actions:['read'],apertureRequired:6,visualTier:1},{id:'aperture-door',kind:'apertureDoor',name:'Unseen Crossing',x:door.x,y:door.y,state:'closed',actions:['enter'],apertureRequired:18,visualTier:2},{id:'aperture-relic',kind:'apertureRelic',name:'Deep Lattice Relic',x:relic.x,y:relic.y,state:'quiet',actions:['attune'],apertureRequired:36,visualTier:3}]}}
export function dungeonDescriptor(id){const recipe=dungeonRecipe(id),meta={hollow:{name:'Hollow Relay',identity:'ordinary crossing',danger:'measured'},cistern:{name:'Root-Sunk Cistern',identity:'salvage vault',danger:'rich caches'},kiln:{name:'Glass Kiln',identity:'sentinel den',danger:'elite guardians'}}[recipe];return{recipe,...meta}}
export function generateDungeon(seed,id=`dungeon:${seed}:g1`){const{recipe,name,identity,danger}=dungeonDescriptor(id),r=rng(`${seed}:dungeon:v2:${id}`),tiles=[];for(let y=0;y<24;y++)for(let x=0;x<24;x++){let open;if(recipe==='hollow')open=(x>2&&x<10&&y>2&&y<10)||(x>13&&x<21&&y>3&&y<11)||(x>5&&x<19&&y>14&&y<22)||(y===7&&x>=9&&x<=14)||(x===16&&y>=10&&y<=15);else if(recipe==='cistern')open=(x>2&&x<21&&y>2&&y<8)||(x>4&&x<10&&y>7&&y<21)||(x>13&&x<21&&y>13&&y<21)||(y===16&&x>=9&&x<=14);else open=(x>2&&x<21&&y>2&&y<9)||(x>2&&x<8&&y>8&&y<21)||(x>11&&x<21&&y>13&&y<21)||(y===16&&x>=7&&x<=12);tiles.push({x,y,kind:open?'floor':'wall',blocked:!open,detail:(x+y)%4})}const objects=[{id:'dungeon-chest',kind:'chest',x:18,y:recipe==='hollow'?7:5,state:'closed',actions:['open'],rewardSource:`${recipe}-cache`},{id:'dungeon-exit',kind:'exit',x:4,y:5,state:'open',actions:['exit']},supply(seed,id,0,tiles,24)];if(recipe==='cistern')objects.push({id:'vault-cache',kind:'supplyCache',supplyType:'restorativeDraught',x:15,y:18,state:'ready',actions:['collect']});if(id===dungeonId(seed,Number(id.match(/:g(\d+)/)?.[1]||1)))objects.push({id:'relay-terminal',kind:'relayTerminal',name:'Crossing Terminal',x:17,y:19,state:'ready',actions:['inspect','restore','sever']});if(recipe==='cistern')objects.push({id:'cistern-vine',kind:'vine',x:8,y:16,toX:15,toY:16,state:'ready',actions:['swing']});if(recipe==='kiln')objects.push({id:'kiln-vent',kind:'trap',trapType:'fire',x:12,y:16,dirX:1,dirY:0,phase:'armed',timer:0,hits:{},clue:'scorch'});else if(recipe!=='hollow')objects.push({id:'crossing-spikes',kind:'trap',trapType:'spikes',x:15,y:16,phase:'armed',timer:0,hits:{},clue:'seams'});const enemySpawns=[{kind:'ashling',x:8,y:8},{kind:'sparkWarden',x:16,y:16},{kind:'hollowMarshal',x:10+Math.floor(r()*5),y:18,boss:true}];if(recipe==='kiln')enemySpawns.push({kind:'sparkWarden',x:18,y:6,elite:true});return{seed,id,recipe,name,identity,danger,tiles,objects,enemySpawns}}
