import{REFUGE_NPCS,WAYSTATION_NPCS}from'./types.js?v=90';
import{deepV2Id,isDeepV2Id,deepV2Descriptor,generateDeepV2Dungeon}from'./deep-dungeons.js?v=90';export{deepV2Id,isDeepV2Id,deepV2Descriptor,generateDeepV2Dungeon}from'./deep-dungeons.js?v=90';
export{generateVariedDungeon,generateBespokeArena}from'./arenas.js?v=90';
import{arenaEligible}from'./arenas.js?v=90';
import{hashSeed,rng,pick}from'./random.js?v=90';import{storySiteFor}from'./story.js?v=90';export const SECTION_SIZE=32,PASSAGE_WIDTH=3;const terrain=['ash','glass','ember'];
function passage(seed,axis,a,b){const r=rng(`${seed}:edge:${axis}:${a}:${b}`);return 5+Math.floor(r()*22)}export function sectionExits(seed,rx,ry){return{north:passage(seed,'h',rx,ry),south:passage(seed,'h',rx,ry+1),west:passage(seed,'v',rx,ry),east:passage(seed,'v',rx+1,ry)}}
function carve(tiles,x,y,kind='ash'){if(kind==='refuge'&&x===12&&y===17)return;if(x>=0&&x<32&&y>=0&&y<32)tiles[y*32+x]={...tiles[y*32+x],x,y,kind,blocked:false}}
function supply(seed,rx,ry,tiles,w=32){const r=rng(`${seed}:supplies:v2:${rx}:${ry}`),rare=w===32&&r()<.06,types=['restorativeDraught','ironbarkTonic','lumenPhial','secondary'],spots=w===24?[[6,6],[7,6],[6,7]]:[[15,17],[17,17],[15,18],[17,18]],[x,y]=spots[Math.floor(r()*spots.length)],supplyType=rare?'crossingSigil':types[Math.floor(r()*types.length)];return{id:`supply-${rx}-${ry}`,kind:supplyType==='secondary'?'weaponCache':'supplyCache',supplyType,x,y,state:'ready',actions:['collect']}}
function addPersistentArenaEntrance(region,seed,rx,ry){if(Math.abs(rx)+Math.abs(ry)<8||region.settlement||!arenaEligible(seed,rx,ry,'persistent'))return;const id=`arena:v1:${seed}:${rx},${ry}`,start=hashSeed(`${id}:entrance`);for(let n=0;n<region.tiles.length;n++){const t=region.tiles[(start+n*19)%region.tiles.length];if(t&&!t.blocked&&t.x>4&&t.y>4&&t.x<27&&t.y<27&&!region.objects.some(o=>Math.hypot(o.x-t.x,o.y-t.y)<3)){region.objects.push({id:`arena-entrance-${rx}-${ry}`,kind:'arenaEntrance',name:'World-Threat Arena',x:t.x,y:t.y,state:'open',actions:['enter'],dungeonId:id,arenaId:id,landmark:true});return}}}
export function generateLegacyOrigin(seed){const r=rng(`${seed}:region:0:0`),tiles=[];for(let y=0;y<32;y++)for(let x=0;x<32;x++){const edge=r(),kind=edge<.16?'blocked':pick(r,terrain);tiles.push({x,y,kind,blocked:kind==='blocked'})}for(let y=13;y<20;y++)for(let x=13;x<20;x++)tiles[y*32+x]={x,y,kind:'refuge',blocked:false};return{seed,rx:0,ry:0,dominant:'ash',exits:null,legacy:true,tiles,objects:[{id:'tree-1',kind:'tree',x:8,y:15,state:'standing',actions:['cut','climb']},{id:'rock-1',kind:'rock',x:23,y:18,state:'sealed',actions:['move','break']},{id:'shrine-1',kind:'shrine',x:19,y:8,state:'quiet',actions:['inspect']},{id:'door-ruin',kind:'door',x:27,y:8,state:'closed',actions:['open','force']},{id:'dungeon-gate',kind:'dungeon',x:5,y:5,state:'open',actions:['enter']},{id:'vendor-vela',kind:'npc',x:17,y:15,state:'calm',actions:['speak','trade','attack']},{id:'cache-1',kind:'cache',x:24,y:18,state:'hidden',actions:['open']},{id:'world-boss',kind:'bossCue',x:28,y:27,state:'dormant',actions:['challenge']},supply(seed,0,0,tiles)],enemySpawns:[{kind:'ashling',x:11,y:7},{kind:'glassMite',x:20,y:23},{kind:'sparkWarden',x:25,y:12}]}}
function structured(seed,rx,ry,generation){const r=rng(`${seed}:region:g${generation}:${rx}:${ry}`),dominant=pick(r,terrain),tiles=[];for(let y=0;y<32;y++)for(let x=0;x<32;x++){const patch=(Math.floor(x/7)+Math.floor(y/6)+Math.floor(r()*2))%3,kind=r()<.76?dominant:terrain[patch];tiles.push({x,y,kind,blocked:x===0||y===0||x===31||y===31,detail:Math.floor(r()*4)})}const ruins=2+Math.floor(r()*2);for(let i=0;i<ruins;i++){const ox=3+Math.floor(r()*19),oy=3+Math.floor(r()*19),w=5+Math.floor(r()*5),h=4+Math.floor(r()*6),door=1+Math.floor(r()*(w-2));for(let y=oy;y<oy+h;y++)for(let x=ox;x<ox+w;x++)if((x===ox||x===ox+w-1||y===oy||y===oy+h-1)&&!(y===oy+h-1&&x===ox+door))tiles[y*32+x]={...tiles[y*32+x],kind:'blocked',blocked:true,ruin:i}}const exits=sectionExits(seed,rx,ry);for(let d=-1;d<=1;d++){for(let y=0;y<=16;y++)carve(tiles,exits.north+d,y,dominant);for(let y=16;y<32;y++)carve(tiles,exits.south+d,y,dominant);for(let x=0;x<=16;x++)carve(tiles,x,exits.west+d,dominant);for(let x=16;x<32;x++)carve(tiles,x,exits.east+d,dominant)}for(let y=14;y<=18;y++)for(let x=14;x<=18;x++)carve(tiles,x,y,rx===0&&ry===0?'refuge':dominant);const prefix=`${rx},${ry}`,objects=[];if(rx===0&&ry===0)objects.push({id:'tree-1',kind:'tree',x:8,y:15,state:'standing',actions:['cut','climb']},{id:'rock-1',kind:'rock',x:23,y:18,state:'sealed',actions:['move','break']},{id:'shrine-1',kind:'shrine',x:19,y:8,state:'quiet',actions:['inspect']},{id:'door-ruin',kind:'door',x:27,y:8,state:'closed',actions:['open','force']},{id:'dungeon-gate',kind:'dungeon',x:5,y:5,state:'open',actions:['enter']},{id:'vendor-vela',kind:'npc',x:17,y:15,state:'calm',actions:['speak','trade','attack']},{id:'cache-1',kind:'cache',x:24,y:18,state:'hidden',actions:['open']},{id:'world-boss',kind:'bossCue',x:28,y:27,state:'dormant',actions:['challenge']});else{const roll=r(),kind=roll<.07?'checkpoint':roll<.54?'shrine':'ruinMarker',x=12+Math.floor(r()*8),y=12+Math.floor(r()*8);objects.push({id:`landmark-${prefix}`,kind,x,y,state:'quiet',actions:kind==='checkpoint'?['activate']:['inspect'],landmark:true,name:kind==='checkpoint'?'Wayglass Beacon':kind==='shrine'?'Singing Array':'Broken Observatory'})}const pools={ash:['ashling','ashenHound','cinderWisp'],glass:['glassMite','coilStalker','veilMoth'],ember:['sparkWarden','rootBrute','cinderWisp']}[dominant],enemySpawns=[{kind:pick(r,pools),x:7+Math.floor(r()*7),y:6+Math.floor(r()*6)},{kind:pick(r,pools),x:18+Math.floor(r()*7),y:20+Math.floor(r()*6)},{kind:pick(r,[...pools,'sparkWarden']),x:22+Math.floor(r()*5),y:8+Math.floor(r()*7)}];if(Math.abs(rx)+Math.abs(ry)>3)enemySpawns.push({kind:pick(r,pools),x:8+Math.floor(r()*16),y:10+Math.floor(r()*12)});for(const e of [...objects,...enemySpawns])carve(tiles,e.x,e.y,dominant);return{seed,rx,ry,dominant,exits,legacy:false,ruinCount:ruins,tiles,objects,enemySpawns}}
function bandOffset(seed,band,segment){return Math.floor(rng(`${seed}:environment:v1:band:${band}:${segment}`)()*9)-4}
function bandCenter(seed,band,gx){const segment=Math.floor(gx/32),t=(gx-segment*32)/32,a=bandOffset(seed,band,segment),b=bandOffset(seed,band,segment+1);return band*96+48+Math.round(a+(b-a)*t)}
function addEnvironment(region,seed,rx,ry,generation){
 const weatherRoll=rng(`${seed}:weather:v1:g${generation}:${rx}:${ry}`)();region.weather=weatherRoll<.24?'rain':weatherRoll<.39?'snow':weatherRoll<.58?'sunbreak':'still';
 if(generation===0||region.settlement||rx===0&&ry===0)return;
 const protectedCells=[...region.objects,...region.enemySpawns],globalMidY=ry*32+16,band=Math.round((globalMidY-48)/96),feature=rng(`${seed}:environment:v1:type:${band}`)()<.55?'river':'canyon',width=feature==='river'?1:2;
 let touched=false;
 for(let y=0;y<32;y++)for(let x=0;x<32;x++){const gx=rx*32+x,gy=ry*32+y,tile=region.tiles[y*32+x];if(Math.abs(gy-bandCenter(seed,band,gx))<=width){region.tiles[y*32+x]={...tile,kind:feature,blocked:true,environment:feature};touched=true}}
 if(touched){
  for(let x=15;x<=17;x++)for(let y=1;y<31;y++)if(region.tiles[y*32+x]?.environment)region.tiles[y*32+x]={...region.tiles[y*32+x],kind:'bridge',blocked:false,bridgeOver:feature};
  for(const p of protectedCells)for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const t=region.tiles[(p.y+oy)*32+p.x+ox];if(t?.environment)region.tiles[(p.y+oy)*32+p.x+ox]={...t,kind:'bridge',blocked:false,bridgeOver:feature}}
  region.environment={kind:feature,band,bridgeX:16};
 }
 const r=rng(`${seed}:environment:v1:props:g${generation}:${rx}:${ry}`),occupied=new Set(protectedCells.map(o=>`${o.x},${o.y}`)),place=(kind,count)=>{for(let made=0,tries=0;made<count&&tries<160;tries++){const x=3+Math.floor(r()*26),y=3+Math.floor(r()*26),tile=region.tiles[y*32+x],key=`${x},${y}`;if(tile.blocked||tile.kind==='bridge'||occupied.has(key)||Math.hypot(x-16,y-16)<4)continue;occupied.add(key);region.objects.push({id:`env-${kind}-${rx}-${ry}-${made}`,kind,x,y,state:kind==='tree'?'standing':'sealed',actions:kind==='tree'?['cut','ignite']:['move','break'],environmental:true});made++}};
 if(touched){const crossX=r()<.5?7:24,ys=[];for(let y=1;y<31;y++)if(region.tiles[y*32+crossX]?.environment)ys.push(y);if(ys.length){const north=Math.min(...ys)-1,south=Math.max(...ys)+1,treeY=region.tiles[north*32+crossX]&&!region.tiles[north*32+crossX].blocked?north:south;if(treeY>1&&treeY<30&&!region.tiles[treeY*32+crossX].blocked){occupied.add(`${crossX},${treeY}`);region.objects.push({id:`crossing-tree-${rx}-${ry}`,kind:'tree',x:crossX,y:treeY,state:'standing',actions:['cut','ignite'],environmental:true,crossingTiles:ys.map(y=>({x:crossX,y}))})}}}
 place('tree',8+Math.floor(r()*5));place('rock',3+Math.floor(r()*4));
 if(r()<.3){for(let tries=0;tries<40;tries++){const sw=6+Math.floor(r()*4),sh=5+Math.floor(r()*3),sx=3+Math.floor(r()*(27-sw)),sy=3+Math.floor(r()*(27-sh)),doorX=sx+Math.floor((sw-1)/2),cells=[];for(let y=sy;y<sy+sh;y++)for(let x=sx;x<sx+sw;x++)cells.push(region.tiles[y*32+x]);if(cells.some(t=>t.blocked||t.kind==='bridge')||sx<=18&&sx+sw-1>=14||sy<=18&&sy+sh-1>=14||protectedCells.some(p=>p.x>=sx-1&&p.x<=sx+sw&&p.y>=sy-1&&p.y<=sy+sh))continue;const facadeStyle=pick(r,['pilgrim','relay','chapel','workshop']),roofProfile=pick(r,['gable','shed','stepped']),condition=pick(r,['weathered','patched','collapsed','overgrown','kept']),entranceWidth=sw>=8&&r()<.65?2:1,entrances=[];for(let q=0;q<entranceWidth;q++)entrances.push({x:doorX+q,y:sy+sh-1,side:'south'});if(sw>=7&&sh>=6&&r()<.55){const side=pick(r,['north','east','west']);entrances.push(side==='north'?{x:sx+1+Math.floor(r()*(sw-2)),y:sy,side}:{x:side==='east'?sx+sw-1:sx,y:sy+1+Math.floor(r()*(sh-2)),side})}if(condition==='collapsed'&&r()<.6)entrances.push({x:sx,y:sy,side:'corner'});const opening=new Set(entrances.map(e=>`${e.x},${e.y}`));for(let y=sy;y<sy+sh;y++)for(let x=sx;x<sx+sw;x++){const wall=x===sx||x===sx+sw-1||y===sy||y===sy+sh-1,door=opening.has(`${x},${y}`);region.tiles[y*32+x]={...region.tiles[y*32+x],kind:wall&&!door?'blocked':region.dominant,blocked:wall&&!door,structure:door?'shackDoor':'shack',buildingId:`shack-${rx}-${ry}`,doorSide:entrances.find(e=>e.x===x&&e.y===y)?.side}}region.objects.push({id:`shack-${rx}-${ry}`,kind:'shack',name:facadeStyle==='chapel'?'Wayside Chapel':facadeStyle==='relay'?'Relay Shelter':facadeStyle==='workshop'?'Salvager Workshop':'Wayfarer Shack',x:sx+Math.floor(sw/2),y:sy+Math.floor(sh/2),state:'quiet',actions:['inspect'],environmental:true,bounds:{x:sx,y:sy,w:sw,h:sh},door:{x:doorX,y:sy+sh-1,side:'south',width:entranceWidth},entrances,facadeStyle,roofProfile,condition,signGlyph:Math.floor(r()*6)});break}}
}
export const SHELTER_SCHEMA_VERSION=2;
export const SHELTER_FAMILIES=['timber','masonry','ruinedGatehouse','cyberRelay','alienGeometric','biomechanical'];
export const SHELTER_THEMES=['ash-road','glass-marsh','ember-steppe','river-verge','canyon-rim','old-kingdom','signal-waste','living-lattice'];
const SHELTER_FORMS={
 timber:{styles:['pilgrim','chapel','workshop'],names:['Wayfarer Shack','Wayside Chapel','Salvager Workshop'],shapes:['rect','lshape','twinPod']},
 masonry:{styles:['stoneCottage','shrineHouse'],names:['Abandoned Stone House','Forgotten Shrine House'],shapes:['rect','lshape','cross']},
 ruinedGatehouse:{styles:['ruinedKeep','gatehouse'],names:['Dilapidated Keep','Broken Gatehouse'],shapes:['gatehouse','cross','lshape'],roof:'stepped'},
 cyberRelay:{styles:['neonKiosk','relayBunker'],names:['Signal Kiosk','Neon Relay'],shapes:['rect','twinPod','cross'],roof:'flat'},
 alienGeometric:{styles:['prismVault','orbitalPod'],names:['Prismatic Refuge','Orbital Pod'],shapes:['diamond','cross','twinPod'],roof:'faceted'},
 biomechanical:{styles:['ribNest','carapace'],names:['Ribbed Sanctuary','Carapace Shelter'],shapes:['oval','cross','lshape'],roof:'carapace'}
};
function shelterCell(shape,lx,ly,w,h){
 if(shape==='lshape')return lx<Math.max(3,Math.floor(w/2))||ly>=h-3;
 if(shape==='cross')return Math.abs(lx-(w-1)/2)<2||Math.abs(ly-(h-1)/2)<2;
 if(shape==='twinPod')return ly>=h-3||lx<3||lx>=w-3;
 if(shape==='gatehouse')return ly>=h-3||lx<3||lx>=w-3;
 if(shape==='diamond')return Math.abs(lx-(w-1)/2)/Math.max(1,w/2)+Math.abs(ly-(h-1)/2)/Math.max(1,h/2)<=1.15||ly>=h-2;
 if(shape==='oval')return Math.pow((lx-(w-1)/2)/Math.max(1,w/2),2)+Math.pow((ly-(h-1)/2)/Math.max(1,h/2),2)<=1.12||ly>=h-2;
 return true;
}
function diversifyShelters(region){
 const r=rng(`${region.seed}:shelter-schema:v${SHELTER_SCHEMA_VERSION}:${region.rx}:${region.ry}`),depth=Math.abs(region.rx)+Math.abs(region.ry);
 for(const shelter of region.objects.filter(o=>o.kind==='shack')){
  const roll=r(),family=roll<.29?'timber':roll<.53?'masonry':roll<.7?'ruinedGatehouse':roll<.84?'cyberRelay':roll<.94?'alienGeometric':'biomechanical',form=SHELTER_FORMS[family],shape=pick(r,form.shapes),b=shelter.bounds,cells=[];
  for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++){const old=region.tiles[y*32+x];region.tiles[y*32+x]={...old,kind:region.dominant,blocked:false,structure:undefined,buildingId:undefined,doorSide:undefined,wallSides:undefined};if(shelterCell(shape,x-b.x,y-b.y,b.w,b.h))cells.push({x,y})}
  const set=new Set(cells.map(c=>`${c.x},${c.y}`)),south=cells.filter(c=>!set.has(`${c.x},${c.y+1}`)).sort((a,b)=>Math.abs(a.x-(shelter.x||16))-Math.abs(b.x-(shelter.x||16))),primary=south[0]||cells[cells.length-1],entrances=[{...primary,side:'south'}];
  if(b.w>=8&&south[1]&&Math.abs(south[1].x-primary.x)===1)entrances.push({...south[1],side:'south'});
  const styleIndex=Math.floor(r()*form.styles.length),themeRoll=r(),theme=region.environment?.kind==='river'?'river-verge':region.environment?.kind==='canyon'?'canyon-rim':family==='biomechanical'?'living-lattice':family==='cyberRelay'?'signal-waste':family==='ruinedGatehouse'?'old-kingdom':region.dominant==='glass'?'glass-marsh':region.dominant==='ember'?'ember-steppe':'ash-road';
  Object.assign(shelter,{schemaVersion:SHELTER_SCHEMA_VERSION,family,theme,shape,footprint:cells,entrances,door:{...primary,width:entrances.length,side:'south'},facadeStyle:form.styles[styleIndex],name:form.names[styleIndex%form.names.length],roofProfile:form.roof||shelter.roofProfile,depthBand:Math.floor(depth/4),incomplete:shelter.condition==='collapsed'||themeRoll<.13});
 }
}
function shelterInterior(region,shelter){return(shelter.footprint||[]).filter(c=>region.tiles[c.y*32+c.x]?.structure==='shackInterior')}
const STRUCTURE_DIRECTIONS={north:[0,-1],south:[0,1],west:[-1,0],east:[1,0]};
export function structureOccupancy(tiles,width,x,y,preferredId=null){
 const left=x+.24,right=x+.76,top=y+.5,bottom=y+.88,scores=new Map();
 for(let ty=Math.floor(top);ty<=Math.floor(bottom-1e-6);ty++)for(let tx=Math.floor(left);tx<=Math.floor(right-1e-6);tx++){
  const tile=tiles?.[ty*width+tx],id=tile?.buildingId;if(!id||preferredId&&id!==preferredId)continue;let x0=tx,x1=tx+1,y0=ty,y1=ty+1;
  for(const side of tile.wallSides||[]){if(side==='west')x0+=.22;else if(side==='east')x1-=.22;else if(side==='north')y0+=.22;else if(side==='south')y1-=.22}
  const area=Math.max(0,Math.min(right,x1)-Math.max(left,x0))*Math.max(0,Math.min(bottom,y1)-Math.max(top,y0));if(area>.01)scores.set(id,(scores.get(id)||0)+area);
 }
 return[...scores].sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])))[0]?.[0]||null;
}
function reachableExterior(region){const seen=new Set(),queue=[];for(let n=0;n<32;n++)for(const[x,y]of[[n,0],[n,31],[0,n],[31,n]]){const t=region.tiles[y*32+x],key=`${x},${y}`;if(t&&!t.blocked&&!t.buildingId&&!seen.has(key)){seen.add(key);queue.push([x,y])}}for(let i=0;i<queue.length;i++){const[x,y]=queue[i];for(const[dx,dy]of Object.values(STRUCTURE_DIRECTIONS)){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`,t=region.tiles[ny*32+nx];if(nx>=0&&ny>=0&&nx<32&&ny<32&&t&&!t.blocked&&!t.buildingId&&!['canyon','river','dungeonWater'].includes(t.kind)&&!seen.has(key)){seen.add(key);queue.push([nx,ny])}}}return seen}
export function validateEnterableStructures(region){
 const reachable=reachableExterior(region),diagnostic={validated:0,repaired:0,invalid:0};
 for(const building of region.objects.filter(o=>o.kind==='shack'||o.kind==='architecturalBuilding')){
  const cells=building.footprint||[],set=new Set(cells.map(c=>`${c.x},${c.y}`)),prefix=building.kind==='shack'?'shack':'district',candidates=[];
  for(const c of cells)for(const[side,[dx,dy]]of Object.entries(STRUCTURE_DIRECTIONS)){const outside={x:c.x+dx,y:c.y+dy},inside={x:c.x-dx,y:c.y-dy};if(set.has(`${outside.x},${outside.y}`)||!set.has(`${inside.x},${inside.y}`)||!reachable.has(`${outside.x},${outside.y}`))continue;candidates.push({x:c.x,y:c.y,side,outside,inside})}
  const old=(building.entrances||[]).map(e=>`${e.x},${e.y},${e.side}`),rank=e=>old.includes(`${e.x},${e.y},${e.side}`)?0:1,candidateByKey=new Map(candidates.map(e=>[`${e.x},${e.y},${e.side}`,e]));let entrances=(building.entrances||[]).map(e=>candidateByKey.get(`${e.x},${e.y},${e.side}`)).filter(Boolean);
  if(!entrances.length&&candidates.length){const contents=region.objects.filter(o=>o.shelterId===building.id),safe=candidates.filter(e=>contents.every(o=>Math.hypot(o.x-e.x,o.y-e.y)>=2)),pool=safe.length?safe:candidates,start=hashSeed(`${region.seed}:structure-repair:v1:${building.id}`)%pool.length;entrances=[pool[start]];diagnostic.repaired++}
  entrances=[...new Map(entrances.sort((a,b)=>rank(a)-rank(b)||a.y-b.y||a.x-b.x).map(e=>[`${e.x},${e.y}`,e])).values()];if(!entrances.length){building.enterable=false;diagnostic.invalid++;continue}
  const opening=new Map(entrances.map(e=>[`${e.x},${e.y}`,e]));for(const c of cells){const tile=region.tiles[c.y*32+c.x],entry=opening.get(`${c.x},${c.y}`),wallSides=Object.entries(STRUCTURE_DIRECTIONS).filter(([, [dx,dy]])=>!set.has(`${c.x+dx},${c.y+dy}`)).map(([side])=>side),wall=wallSides.length&&!entry;region.tiles[c.y*32+c.x]={...tile,blocked:false,structure:entry?`${prefix}Door`:wall?`${prefix}Wall`:`${prefix}Interior`,buildingId:building.id,doorSide:entry?.side,wallSides:wall?wallSides:[]}}
  for(const e of entrances){const t=region.tiles[e.outside.y*32+e.outside.x];region.tiles[e.outside.y*32+e.outside.x]={...t,kind:t.bridgeOver?'bridge':region.dominant,blocked:false,environment:t.bridgeOver?t.environment:undefined,structure:undefined,buildingId:undefined,wallSides:undefined};region.objects=region.objects.filter(o=>!o.environmental||o.id===building.id||Math.hypot(o.x-e.outside.x,o.y-e.outside.y)>1)}
  const primary=entrances[0],same=entrances.filter(e=>e.side===primary.side).sort((a,b)=>primary.side==='north'||primary.side==='south'?a.x-b.x:a.y-b.y),run=[same[0]];for(let i=1;i<same.length;i++){const prior=run.at(-1),next=same[i],adjacent=primary.side==='north'||primary.side==='south'?next.x===prior.x+1:next.y===prior.y+1;if(adjacent)run.push(next);else break}const origin=run[0]||primary;
  building.entrances=entrances.map(({x,y,side})=>({x,y,side}));building.door={x:origin.x,y:origin.y,side:origin.side,width:run.length};building.interior=cells.filter(c=>region.tiles[c.y*32+c.x].structure===`${prefix}Interior`);building.boundary=cells.filter(c=>region.tiles[c.y*32+c.x].structure===`${prefix}Wall`);building.entranceApproaches=entrances.map(e=>({x:e.outside.x,y:e.outside.y,side:e.side}));building.enterable=true;building.geometryVersion=1;diagnostic.validated++;
 }
 region.structureDiagnostics=diagnostic;return diagnostic;
}
function thinShelterWalls(region){
 const ordinary=region.objects.find(o=>o.kind==='checkpoint'&&String(o.id).startsWith('landmark-'));
 if(ordinary&&rng(`${region.seed}:wayglass-sparsity:v1:${region.rx}:${region.ry}`)()>=.36){ordinary.kind='shrine';ordinary.name='Singing Array';ordinary.actions=['inspect']}
 for(const shelter of region.objects.filter(o=>o.kind==='shack')){
  const b=shelter.bounds,cells=shelter.footprint||Array.from({length:b.w*b.h},(_,i)=>({x:b.x+i%b.w,y:b.y+Math.floor(i/b.w)})),set=new Set(cells.map(c=>`${c.x},${c.y}`)),openings=new Map((shelter.entrances||[]).map(e=>[`${e.x},${e.y}`,e])),sides=[[1,0,'east'],[-1,0,'west'],[0,1,'south'],[0,-1,'north']];shelter.footprint=cells;
  for(const c of cells){const tile=region.tiles[c.y*32+c.x],opening=openings.get(`${c.x},${c.y}`),wallSides=sides.filter(([dx,dy])=>!set.has(`${c.x+dx},${c.y+dy}`)).map(q=>q[2]),wall=wallSides.length&&!opening;region.tiles[c.y*32+c.x]={...tile,kind:region.dominant,blocked:false,structure:opening?'shackDoor':wall?'shackWall':'shackInterior',wallSides:wall?wallSides:[],buildingId:shelter.id,doorSide:opening?.side,shelterFamily:shelter.family,shelterTheme:shelter.theme}}
 }
 const shelter=region.objects.find(o=>o.kind==='shack');if(!shelter)return;const spots=shelterInterior(region,shelter).filter(c=>!shelter.entrances.some(e=>Math.hypot(c.x-e.x,c.y-e.y)<2));if(!spots.length)return;
 const hazardR=rng(String(region.seed)+':shelter-hazard:v2:'+region.rx+':'+region.ry);if(hazardR()<.18){const spot=spots[Math.floor(hazardR()*spots.length)],hazardType=pick(hazardR,['flameJet','shockPlate','toxicVent','graspingTendril','moltenFissure']);region.objects.push({id:'shelter-hazard-'+region.rx+'-'+region.ry,kind:'shelterHazard',name:{flameJet:'Scorched Vent',shockPlate:'Charge Plate',toxicVent:'Spore Vent',graspingTendril:'Grasping Seam',moltenFissure:'Molten Crack'}[hazardType],hazardType,...spot,state:'armed',actions:['inspect'],shelterId:shelter.id,telegraphed:true,damage:10})}
 const hidden=rng(String(region.seed)+':hidden-displacement:v2:'+region.rx+':'+region.ry);if(hidden()<.014){const spot=spots[Math.floor(hidden()*spots.length)];region.objects.push({id:'hidden-displacement-'+region.rx+'-'+region.ry,kind:'displacementTrap',name:'Folded Seam',...spot,state:'armed',actions:[],shelterId:shelter.id,hidden:true,consumed:false})}
 const r=rng(String(region.seed)+':shelter-surprise:v1:'+region.rx+':'+region.ry);if(r()>=.28)return;const spot=spots[Math.floor(r()*spots.length)],roll=r(),id='shelter-surprise-'+region.rx+'-'+region.ry;
 if(roll<.34)region.objects.push({id,kind:'shelterMerchant',name:pick(r,['The Lantern Broker','Moss-Cloaked Factor','The Quiet Provisioner']),role:'Wandering specialist',...spot,state:'calm',actions:['speak','trade'],shelterId:shelter.id});
 else if(roll<.68)region.objects.push({id,kind:'shelterCreature',name:pick(r,['Hearth Moth','Pilgrim Coil','Velvet Scavenger']),...spot,state:'watching',gift:pick(r,['marks','aperture','lumen']),actions:['commune'],shelterId:shelter.id});
 else if(roll<.87)region.objects.push({id,kind:'displacementDevice',name:'Mislaid Threshold',...spot,state:'armed',actions:['enter'],shelterId:shelter.id,landmark:true,signaled:true});
 else region.enemySpawns.push({kind:pick(r,['ashling','glassMite','ashenHound','coilStalker']),...spot,shelterAmbush:true});
}
function annotateVegetation(region){for(const o of region.objects.filter(q=>q.kind==='tree')){const r=rng(`${region.seed}:vegetation:v1:${o.id}`);o.vegetationForm=o.crossingTiles?.length?'canopy':pick(r,['canopy','shrub','spindle']);o.scale=o.vegetationForm==='canopy'?1.25:o.vegetationForm==='shrub'?.72:1.05}}
function addAmbientFauna(region,seed,rx,ry,generation){if(region.settlement||rx===0&&ry===0)return;const r=rng(`${seed}:ambient-fauna:v1:g${generation}:${rx}:${ry}`);if(r()>.42)return;const open=region.tiles.filter(t=>!t.blocked&&!t.structure&&t.x>3&&t.x<28&&t.y>3&&t.y<28),species=[['mossGrazer','graze'],['lanternDoe','follow'],['hushling','vanish']],count=r()<.24?2:1;for(let i=0;i<count&&open.length;i++){const at=open.splice(Math.floor(r()*open.length),1)[0],[kind,passiveBehavior]=pick(r,species);region.enemySpawns.push({kind,x:at.x,y:at.y,ambient:true,passiveBehavior})}}
const DISTRICT_STYLES={city:{name:'Hollow Ward',floor:'cityFloor',wall:'cityWall',enemy:'ashenHound'},arcology:{name:'Lumen Arcology',floor:'arcologyFloor',wall:'arcologyWall',enemy:'coilStalker'},cloister:{name:'Thorn Cloister',floor:'cloisterFloor',wall:'cloisterWall',enemy:'veilMoth'},fortress:{name:'Broken Citadel',floor:'cityFloor',wall:'cityWall',enemy:'rootBrute'}};
const BUILDING_USES={city:['market','infirmary','tenement','apartments','civic-hall'],arcology:['signal-lab','transit-archive','defense-post','reactor-house','habitat'],cloister:['cathedral','abbey','scriptorium','reliquary','chapter-house'],fortress:['ruined-keep','gatehouse','watch-fort','fallen-palace','bastion']};
function addArchitecturalDistrict(region,seed,rx,ry,generation){
 if(generation===0||rx===0&&ry===0||region.settlement)return;
 const r=rng(`${seed}:district:v3:g${generation}:${rx}:${ry}`);if(r()>=.32)return;
 const protectedObjects=region.objects.filter(o=>!o.environmental||o.kind==='shack'),protectedCells=[...protectedObjects.flatMap(o=>o.kind==='shack'&&o.footprint?.length?o.footprint:[o]),...region.enemySpawns],
 style=pick(r,Object.keys(DISTRICT_STYLES)),meta=DISTRICT_STYLES[style],routes=region.exits,
 candidates=[{corner:'nw',door:'south',edges:['north','west']},{corner:'ne',door:'south',edges:['north','east']},{corner:'sw',door:'north',edges:['south','west']},{corner:'se',door:'north',edges:['south','east']}].map(q=>{const w=9+Math.floor(r()*4),h=8+Math.floor(r()*4),x=q.corner.endsWith('e')?29-w:3,y=q.corner.startsWith('s')?29-h:3,shape=pick(r,style==='fortress'?['keep','courtyard','lshape','hshape']:style==='cloister'?['cross','courtyard','lshape']:['rect','lshape','hshape','cross']);return{...q,x,y,w,h,shape}}),buildings=[];
 const crossesRoute=b=>routes&&b.edges.some(edge=>(edge==='north'||edge==='south')?routes[edge]>=b.x-1&&routes[edge]<=b.x+b.w:routes[edge]>=b.y-1&&routes[edge]<=b.y+b.h),occupied=b=>protectedCells.some(p=>p.x>=b.x&&p.x<b.x+b.w&&p.y>=b.y&&p.y<b.y+b.h),badTerrain=b=>{for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++){const t=region.tiles[y*32+x];if(footprint(b,x,y)&&(t?.environment||t?.kind==='bridge'))return true}return false};
 const footprint=(b,x,y)=>{const lx=x-b.x,ly=y-b.y;if(lx<0||ly<0||lx>=b.w||ly>=b.h)return false;if(b.shape==='lshape')return lx<4||ly>=b.h-4||(b.door==='north'&&ly<2);if(b.shape==='cross')return Math.abs(lx-(b.w-1)/2)<2||Math.abs(ly-(b.h-1)/2)<2;if(b.shape==='hshape')return lx<3||lx>=b.w-3||Math.abs(ly-(b.h-1)/2)<1.5||(b.door==='south'?ly>=b.h-2:ly<2);if(b.shape==='courtyard')return lx<3||lx>=b.w-3||ly<3||ly>=b.h-3;return true};
 for(const b of candidates){if(crossesRoute(b)||occupied(b)||badTerrain(b))continue;const doorX=b.x+Math.floor((b.w-1)/2),doorY=b.door==='south'?b.y+b.h-1:b.y,cells=[];for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++)if(footprint(b,x,y))cells.push({x,y});const set=new Set(cells.map(c=>`${c.x},${c.y}`)),entranceWidth=b.w>=9&&r()<.7?2:1,entrances=[];for(let q=0;q<entranceWidth;q++)if(set.has(`${doorX+q},${doorY}`))entrances.push({x:doorX+q,y:doorY,side:b.door});if((b.w>=9||b.h>=8)&&r()<.7){const side=pick(r,['east','west']),x=side==='east'?b.x+b.w-1:b.x;for(let d=0;d<b.h-2;d++){const y=b.y+1+(Math.floor(b.h/2)+d)%(b.h-2);if(set.has(`${x},${y}`)){entrances.push({x,y,side});break}}}buildings.push({...b,doorX,doorY,id:`district-building-${rx}-${ry}-${buildings.length}`,cells,entrances});if(buildings.length===3)break}
 if(buildings.length<2)return;
 region.objects=region.objects.filter(o=>!o.environmental||!buildings.some(b=>o.x>=b.x&&o.x<b.x+b.w&&o.y>=b.y&&o.y<b.y+b.h));
 for(const [i,b] of buildings.entries()){const set=new Set(b.cells.map(c=>`${c.x},${c.y}`)),openings=new Map(b.entrances.map(e=>[`${e.x},${e.y}`,e])),inside=[],sides=[[1,0,'east'],[-1,0,'west'],[0,1,'south'],[0,-1,'north']];for(const c of b.cells){const wallSides=sides.filter(([dx,dy])=>!set.has(`${c.x+dx},${c.y+dy}`)).map(([, ,side])=>side),opening=openings.get(`${c.x},${c.y}`),wall=wallSides.length>0&&!opening,structure=opening?'districtDoor':wall?'districtWall':'districtInterior';region.tiles[c.y*32+c.x]={...region.tiles[c.y*32+c.x],kind:wall?meta.wall:meta.floor,blocked:false,structure,districtStyle:style,buildingId:b.id,doorSide:opening?.side,wallSides:wall?wallSides:[]};if(!wall)inside.push({x:c.x,y:c.y})}b.interior=inside;for(const e of b.entrances){const ox=e.side==='east'?1:e.side==='west'?-1:0,oy=e.side==='south'?1:e.side==='north'?-1:0;carve(region.tiles,e.x+ox,e.y+oy,meta.floor)}}
 region.district={style,name:meta.name,buildingCount:buildings.length};region.objects.push({id:`district-${rx}-${ry}`,kind:'architecturalDistrict',name:meta.name,x:16,y:16,state:'unread',actions:['inspect'],landmark:true,districtStyle:style});
 for(const [i,b] of buildings.entries()){const use=pick(r,BUILDING_USES[style]),roofProfile=style==='fortress'?pick(r,['flat','stepped']):pick(r,['gable','flat','stepped','spire']),facadeRhythm=pick(r,['paired','narrow','broad']),accent=pick(r,['copper','ivory','oxide','violet']),signGlyph=Math.floor(r()*8),anchor=b.interior[Math.floor(b.interior.length/2)]||b.cells[0];region.objects.push({id:b.id,kind:'architecturalBuilding',name:`${meta.name} ${use.replace('-',' ')}`,x:anchor.x,y:anchor.y,state:'quiet',actions:[],bounds:{x:b.x,y:b.y,w:b.w,h:b.h},door:{x:b.doorX,y:b.doorY,side:b.door,width:b.entrances.filter(e=>e.side===b.door).length},entrances:b.entrances,districtStyle:style,facadeHeight:1+i%3,shape:b.shape,footprint:b.cells,buildingUse:use,roofProfile,facadeRhythm,accent,signGlyph})}
 const den=buildings[0],denSpot=den.interior.find(c=>Math.abs(c.x-den.doorX)+Math.abs(c.y-den.doorY)>2)||den.interior[den.interior.length-1];region.enemySpawns.push({kind:meta.enemy,x:denSpot.x,y:denSpot.y,districtResident:true});
}
function addDungeonLandmark(region,seed,rx,ry,generation){if(rx===0&&ry===0||generation===0)return;const r=rng(`${seed}:dungeon-entrance:v1:g${generation}:${rx}:${ry}`);if(r()>=.28)return;const spots=[];for(let y=4;y<28;y++)for(let x=4;x<28;x++)if(!region.tiles[y*32+x].blocked&&Math.hypot(x-16,y-16)>5)spots.push([x,y]);if(!spots.length)return;const[x,y]=spots[Math.floor(r()*spots.length)],id=`dungeon-g${generation}-${rx}-${ry}-${Math.floor(r()*1e6)}`,d=dungeonDescriptor(dungeonId(seed,generation,rx,ry,id));region.objects.push({id,kind:'dungeon',x,y,state:'open',actions:['enter'],landmark:true,name:d.name,identity:d.identity});carve(region.tiles,x,y,region.dominant)}
function addDeepDungeonLandmark(region,seed,rx,ry,generation){if(generation===0||rx===0&&ry===0||region.settlement)return;const r=rng(`${seed}:deep-dungeon-entrance:v1:g${generation}:${rx}:${ry}`);if(r()>=.04)return;const spots=[];for(let y=4;y<28;y++)for(let x=4;x<28;x++){const tile=region.tiles[y*32+x];if(!tile.blocked&&!tile.structure&&!tile.environment&&Math.hypot(x-16,y-16)>6&&!region.objects.some(o=>Math.hypot(o.x-x,o.y-y)<2))spots.push([x,y])}if(!spots.length)return;const[x,y]=spots[Math.floor(r()*spots.length)],id=`dungeon-deep-v1-g${generation}-${rx}-${ry}`,deepId=deepDungeonId(seed,generation,rx,ry),d=dungeonDescriptor(deepId);region.objects.push({id,kind:'dungeon',dungeonId:deepId,dungeonType:'deep-v1',x,y,state:'open',actions:['enter','bypass'],landmark:true,name:d.name,identity:d.identity,depth:d.depth});carve(region.tiles,x,y,region.dominant)}
function addDeepV2Landmark(region,seed,rx,ry,generation){if(generation===0||rx===0&&ry===0||region.settlement||region.objects.some(o=>o.dungeonType==='deep-v1'))return;const r=rng(`${seed}:deep-dungeon-entrance:v2:g${generation}:${rx}:${ry}`);if(r()>=.01)return;const spots=[];for(let y=4;y<28;y++)for(let x=4;x<28;x++){const tile=region.tiles[y*32+x];if(!tile.blocked&&!tile.structure&&!tile.environment&&Math.hypot(x-16,y-16)>6&&!region.objects.some(o=>Math.hypot(o.x-x,o.y-y)<2))spots.push([x,y])}if(!spots.length)return;const[x,y]=spots[Math.floor(r()*spots.length)],deepId=deepV2Id(seed,generation,rx,ry),d=dungeonDescriptor(deepId),id=`dungeon-${d.recipe}-${d.archetype}-g${generation}-${rx}-${ry}`;region.objects.push({id,kind:'dungeon',dungeonId:deepId,dungeonType:'deep-v2',archetype:d.archetype,x,y,state:'open',actions:['enter','bypass'],landmark:true,name:d.name,identity:d.identity,depth:d.depth});carve(region.tiles,x,y,region.dominant)}
function addSettlement(region,rx,ry){const key=`${rx},${ry}`,config=key==='4,-2'?{id:'glasshaven',name:'Glasshaven',people:['vendor-iona','resident-tarn']}:key==='-5,3'?{id:'coilmarket',name:'Coilmarket',people:['vendor-mora','resident-esh']}:null;if(!config)return;region.settlement=config;for(let y=12;y<=19;y++)for(let x=12;x<=20;x++)carve(region.tiles,x,y,'refuge');region.objects=region.objects.filter(o=>!o.landmark);region.objects.push({id:`beacon-${config.id}`,kind:'checkpoint',x:16,y:18,state:'quiet',actions:['activate'],landmark:true,name:config.name+' Wayglass'});for(const id of config.people){const n=WAYSTATION_NPCS.find(q=>q.id===id);region.objects.push({...n,kind:'npc',state:'calm',maxHp:36})}region.enemySpawns=region.enemySpawns.filter(e=>Math.hypot(e.x-16,e.y-16)>7)}
function addCreatureTraits(region,seed,rx,ry,generation){const r=rng(`${seed}:traits:v2:g${generation}:${rx}:${ry}`),sr=rng(`${seed}:void-sentinel:v1:g${generation}:${rx}:${ry}`),depth=Math.abs(rx)+Math.abs(ry),ranged=new Set(['sparkWarden','veilMoth','coilStalker','cinderWisp','voidSentinel']);for(const e of region.enemySpawns){if(depth>7&&sr()<.018)e.kind='voidSentinel';e.traits=[];const pool=['plated','feral','swift','vital','keen',...(ranged.has(e.kind)?['farcasting']:[]),...(depth>5&&r()<.18?['orbital']:[])],count=depth>6&&r()<.55?2:depth>1&&r()<.7?1:0;while(e.traits.length<count){const trait=pick(r,pool);if(e.traits.includes(trait)||trait==='feral'&&e.traits.includes('plated')||trait==='plated'&&e.traits.includes('feral'))continue;e.traits.push(trait)}}}
export function generateRegion(seed,rx,ry,generation=1){const region=generation===0&&rx===0&&ry===0?generateLegacyOrigin(seed):structured(seed,rx,ry,generation);addCreatureTraits(region,seed,rx,ry,generation);addSettlement(region,rx,ry);addDungeonLandmark(region,seed,rx,ry,generation);if(rx===0&&ry===0){for(const n of REFUGE_NPCS){const existing=region.objects.find(o=>o.id===n.id);if(existing)Object.assign(existing,n,{settlement:'ember-refuge',maxHp:36});else region.objects.push({...n,kind:'npc',state:'calm',settlement:'ember-refuge',maxHp:36});carve(region.tiles,n.x,n.y,'refuge');}region.objects.push({id:'ember-aperture-plinth',kind:'apertureRitual',name:'Aperture Plinth',x:14,y:17,state:'dormant',actions:['inspect','perform'],landmark:true,settlement:'ember-refuge'});carve(region.tiles,14,17,'refuge');}if(region.settlement||rx===0&&ry===0){region.objects.push({id:'viewport-'+rx+'-'+ry,kind:'viewport',name:'Viewport',x:12,y:17,state:'ready',actions:['inspect'],settlement:region.settlement?.id||'ember-refuge'});carve(region.tiles,12,17,'refuge');region.enemySpawns=region.enemySpawns.filter(e=>Math.hypot(e.x-16,e.y-16)>9)}for(const o of region.objects)if(o.kind==='dungeon')o.actions=['enter','bypass'];if(!region.objects.some(o=>o.id===`supply-${rx}-${ry}`))region.objects.push(supply(seed,rx,ry,region.tiles));addEnvironment(region,seed,rx,ry,generation);diversifyShelters(region);thinShelterWalls(region);addArchitecturalDistrict(region,seed,rx,ry,generation);annotateVegetation(region);addAmbientFauna(region,seed,rx,ry,generation);addDeepDungeonLandmark(region,seed,rx,ry,generation);addDeepV2Landmark(region,seed,rx,ry,generation);addPersistentArenaEntrance(region,seed,rx,ry);validateEnterableStructures(region);return region}
const SITE_KINDS=new Set(['checkpoint','dungeon','arenaEntrance','shrine','ruinMarker','shack','bossCue','architecturalDistrict','supplyCache','storyEcho']);
export function sectionSites(seed,rx,ry,generation=1,save=null){const r=generateRegion(seed,rx,ry,generation),echo=save?storySiteFor(save,rx,ry):null;if(echo)r.objects.push(echo);const sites=r.objects.filter(o=>SITE_KINDS.has(o.kind)).map(o=>({kind:o.kind,name:o.name||({checkpoint:'Wayglass Beacon',dungeon:'Buried Crossing',arenaEntrance:'World-Threat Arena',shrine:'Singing Array',ruinMarker:'Broken Observatory',shack:'Wayfarer Shack',bossCue:'Major Threat',architecturalDistrict:'Architectural Ruin',supplyCache:'Supply Cache',storyEcho:'Story signal'}[o.kind]||o.kind),x:o.x,y:o.y})),remembered=save?.checkpoints?.[`${rx},${ry}`];if(remembered&&!sites.some(o=>o.kind==='checkpoint'))sites.push({kind:'checkpoint',name:remembered.name||'Remembered Wayglass',x:Number.isFinite(remembered.x)?remembered.x:16,y:Number.isFinite(remembered.y)?remembered.y:16,remembered:true});return sites}
export function sectionSummary(seed,rx,ry,generation=1,save=null){const r=generateRegion(seed,rx,ry,generation),sites=sectionSites(seed,rx,ry,generation,save),l=r.objects.find(o=>o.landmark)||r.objects.find(o=>['dungeon','shrine','door'].includes(o.kind));return{rx,ry,terrain:r.dominant,landmark:l?.name||({dungeon:'Hollow Relay Gate',shrine:'Quiet Array',door:'Abandoned Relay'}[l?.kind]||'No recorded landmark'),sites,checkpoint:!!save?.checkpoints?.[`${rx},${ry}`],current:save?.session?.rx===rx&&save?.session?.ry===ry,waypoint:save?.manualWaypoint?.rx===rx&&save?.manualWaypoint?.ry===ry}}
const WAYFINDING_SIGNAL_CACHE_LIMIT=96,wayfindingSignalCache=new Map();let wayfindingSignalHits=0,wayfindingSignalMisses=0;
function cachedRegionSignals(seed,rx,ry,generation){const key=`${seed}:g${generation}:${rx},${ry}`;if(wayfindingSignalCache.has(key)){const value=wayfindingSignalCache.get(key);wayfindingSignalCache.delete(key);wayfindingSignalCache.set(key,value);wayfindingSignalHits++;return value}const region=generateRegion(seed,rx,ry,generation),value=Object.freeze({crossing:region.objects.some(o=>o.kind==='dungeon'),event:region.objects.some(o=>o.kind==='shrine'||o.kind==='ruinMarker')});wayfindingSignalCache.set(key,value);wayfindingSignalMisses++;while(wayfindingSignalCache.size>WAYFINDING_SIGNAL_CACHE_LIMIT)wayfindingSignalCache.delete(wayfindingSignalCache.keys().next().value);return value}
export function wayfindingCacheStats(){return{size:wayfindingSignalCache.size,limit:WAYFINDING_SIGNAL_CACHE_LIMIT,hits:wayfindingSignalHits,misses:wayfindingSignalMisses}}
export function clearWayfindingCache(){wayfindingSignalCache.clear();wayfindingSignalHits=wayfindingSignalMisses=0}
export function wayfindingCues(seed,rx,ry,generation=1,save=null,region=null){
  const targets=[],seen=new Set(),add=(kind,x,y,name)=>{const key=`${kind}:${x},${y}`;if((x!==rx||y!==ry)&&!seen.has(key)){seen.add(key);targets.push({kind,rx:x,ry:y,name})}};
  const hunt=save?.viewport?.contracts?.[save?.viewport?.activeHuntId],huntTarget=hunt?.target;if(huntTarget&&['accepted','tracking','target-located'].includes(hunt.status))add(hunt.kind==='trial'||hunt.domain?'danger':'story',huntTarget.rx,huntTarget.ry,hunt.title);
  const echo=save?.story?.arcs?.cartographersEcho?.site;if(echo&&!save.story.arcs.cartographersEcho.completed)add('story',echo.rx,echo.ry,'the Unwritten Meridian');
  for(const c of Object.values(save?.checkpoints||{}))if(Number.isFinite(c?.rx)&&Number.isFinite(c?.ry))add('beacon',c.rx,c.ry,c.name||'Wayglass');
  if(!save?.worldFlags?.worldBossDead)add('danger',0,0,'a great enemy');
  for(let radius=1;radius<=4;radius++)for(let oy=-radius;oy<=radius;oy++)for(let ox=-radius;ox<=radius;ox++){
    if(Math.abs(ox)+Math.abs(oy)!==radius)continue;
    const signals=cachedRegionSignals(seed,rx+ox,ry+oy,generation);
    if(signals.crossing)add('crossing',rx+ox,ry+oy,'a buried crossing');
    if(signals.event)add('event',rx+ox,ry+oy,'an unusual site');
  }
  const chosen=[];
  for(const kind of ['story','beacon','crossing','danger','event']){
    const matches=targets.filter(t=>t.kind===kind).sort((a,b)=>(Math.abs(a.rx-rx)+Math.abs(a.ry-ry))-(Math.abs(b.rx-rx)+Math.abs(b.ry-ry)));
    if(matches[0])chosen.push(matches[0]);
  }
  const map=region||generateRegion(seed,rx,ry,generation),spots=[[14,13],[17,13],[19,16],[17,19],[13,18],[11,15],[20,19]];
  return chosen.slice(0,4).map((target,i)=>{
    const spot=spots.slice(i).concat(spots.slice(0,i)).find(([x,y])=>!map.tiles[y*32+x]?.blocked)||[16,16],dx=Math.sign(target.rx-rx),dy=Math.sign(target.ry-ry);
    return{id:`waymark-${target.kind}`,kind:'wayfindingCue',signalKind:target.kind,x:spot[0],y:spot[1],dirX:dx,dirY:dy,targetRx:target.rx,targetRy:target.ry,name:target.name,state:'quiet',actions:[]};
  });
}
export function dungeonId(seed,generation=1,rx=0,ry=0,objectId='dungeon-gate'){return rx===0&&ry===0&&objectId==='dungeon-gate'?`dungeon:${seed}:g${generation}`:`dungeon:${seed}:g${generation}:${rx}:${ry}:${objectId}`}
export function deepDungeonId(seed,generation=1,rx=0,ry=0){return`dungeon:${seed}:g${generation}:${rx}:${ry}:deep-v1`}
export function isDeepDungeonId(id){return typeof id==='string'&&(id.endsWith(':deep-v1')||isDeepV2Id(id))}
export function dungeonRecipe(id){if(!id||!/:[^:]+:[^:]+:[^:]+$/.test(id))return'hollow';const n=[...id].reduce((a,c)=>(a*33+c.charCodeAt(0))>>>0,5381)%3;return['hollow','cistern','kiln'][n]}
export const APERTURE_THRESHOLDS=[6,18,36];
export function apertureTier(value){const n=Math.max(0,Number(value)||0);return n>=36?3:n>=18?2:n>=6?1:0}
export function apertureEncounterSpawns(seed,areaId,value,tiles,width=32){const tier=apertureTier(value);if(!tier)return[];const r=rng(`${seed}:aperture-encounter:v1:${areaId}`),chance=[0,.12,.2,.3][tier];if(r()>=chance)return[];const open=tiles.filter(t=>!t.blocked&&t.x>3&&t.y>3&&t.x<width-3&&t.y<width-3),spot=open[Math.floor(r()*open.length)];if(!spot)return[];const kinds=[['ashenHound','coilStalker'],['rootBrute','sparkWarden','coilStalker'],['rootBrute','hollowMarshal','sparkWarden']][tier-1],traits=[['keen','swift'],['vital','feral','farcasting'],['vital','plated','orbital']][tier-1];return[{kind:pick(r,kinds),x:spot.x,y:spot.y,traits:traits.slice(0,tier),apertureEncounter:true,apertureTier:tier,threatMultiplier:1+.4*tier}]}
export function regionalThreat(rx=0,ry=0){const ring=Math.floor(Math.hypot(Number(rx)||0,Number(ry)||0)),near=Math.min(10,ring),far=Math.max(0,ring-10);return{ring,hpMultiplier:1+.08*near+.04*far,damageMultiplier:1+.05*near+.025*far,xpMultiplier:1+.06*ring}}
export function perceived(entity,save){if(entity?.kind==='apertureDoor'&&!save?.consequences?.dungeons?.[save?.session?.activeDungeonId]?.resolved)return false;return!entity?.apertureRequired||(save?.perception?.aperture||0)>=entity.apertureRequired}
export function perceptionOverlay(seed,areaId,tiles,width=24){const r=rng(`${seed}:aperture:v1:${areaId}`),open=tiles.filter(t=>!t.blocked&&t.x>5&&t.y>5&&t.x<width-3&&t.y<width-3),pickOpen=()=>open[Math.floor(r()*open.length)]||{x:8,y:8},memory=pickOpen(),door=pickOpen(),relic=pickOpen();return{objects:[{id:'aperture-memory',kind:'apertureMemory',name:'Veiled Inscription',x:memory.x,y:memory.y,state:'quiet',actions:['read'],apertureRequired:6,visualTier:1},{id:'aperture-door',kind:'apertureDoor',name:'Unseen Crossing',x:door.x,y:door.y,state:'closed',actions:['enter'],apertureRequired:18,visualTier:2},{id:'aperture-relic',kind:'apertureRelic',name:'Deep Lattice Relic',x:relic.x,y:relic.y,state:'quiet',actions:['attune'],apertureRequired:36,visualTier:3}]}}
export function dungeonDescriptor(id){if(isDeepV2Id(id))return deepV2Descriptor(id);if(isDeepDungeonId(id))return{recipe:'deep-v1',name:'The Threefold Deep',identity:'sealed deep dungeon',danger:'three wing wardens',depth:'deep'};const recipe=dungeonRecipe(id),meta={hollow:{name:'Hollow Relay',identity:'ordinary crossing',danger:'measured'},cistern:{name:'Root-Sunk Cistern',identity:'salvage vault',danger:'rich caches'},kiln:{name:'Glass Kiln',identity:'sentinel den',danger:'elite guardians'}}[recipe];return{recipe,...meta}}
export function generateDeepDungeon(seed,id=deepDungeonId(seed),options={}){
 if(isDeepV2Id(id))return generateDeepV2Dungeon(seed,id,options);
 const width=64,height=64,gateOpen=options.gateOpen===true,r=rng(`${seed}:deep-dungeon:v1:${id}`),tiles=[];
 for(let y=0;y<height;y++)for(let x=0;x<width;x++)tiles.push({x,y,kind:'deepWall',blocked:true,detail:(x*3+y*5)%4});
 const floor=(x,y,extra={})=>{if(x>0&&y>0&&x<width-1&&y<height-1)tiles[y*width+x]={x,y,kind:'deepFloor',blocked:false,detail:(x+y)%4,...extra}},rect=(x0,y0,x1,y1)=>{for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)floor(x,y)},hall=(x0,y0,x1,y1)=>{let x=x0,y=y0;for(;;){for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++)floor(x+ox,y+oy);if(x===x1&&y===y1)break;if(x!==x1)x+=Math.sign(x1-x);else y+=Math.sign(y1-y)}};
 rect(27,27,37,38);rect(28,56,35,62);hall(31,58,31,35);rect(3,25,16,40);hall(27,32,14,32);rect(47,25,60,40);hall(37,32,49,32);rect(9,43,23,55);hall(29,37,21,47);rect(23,3,41,17);hall(32,27,32,15);
 const pits=[{wingId:'west',axis:'vertical',at:10,from:26,to:39,bridge:32},{wingId:'east',axis:'vertical',at:53,from:26,to:39,bridge:32},{wingId:'south',axis:'horizontal',at:49,from:10,to:22,bridge:17}];
 for(const pit of pits){if(pit.axis==='vertical')for(let y=pit.from;y<=pit.to;y++)for(let x=pit.at-1;x<=pit.at+1;x++)tiles[y*width+x]={x,y,kind:'canyon',blocked:true,environment:'canyon',pit:true,wingId:pit.wingId};else for(let x=pit.from;x<=pit.to;x++)for(let y=pit.at-1;y<=pit.at+1;y++)tiles[y*width+x]={x,y,kind:'canyon',blocked:true,environment:'canyon',pit:true,wingId:pit.wingId};if(pit.axis==='vertical')for(let x=pit.at-1;x<=pit.at+1;x++)tiles[pit.bridge*width+x]={x,y:pit.bridge,kind:'bridge',blocked:false,bridgeOver:'canyon',permanent:true,wingId:pit.wingId};else for(let y=pit.at-1;y<=pit.at+1;y++)tiles[y*width+pit.bridge]={x:pit.bridge,y,kind:'bridge',blocked:false,bridgeOver:'canyon',permanent:true,wingId:pit.wingId}}
 const entry={x:31,y:59},hub={x:32,y:33},returns=[{id:'deep-v1-return-west',wingId:'west',x:15,y:34},{id:'deep-v1-return-east',wingId:'east',x:48,y:34},{id:'deep-v1-return-south',wingId:'south',x:21,y:46}],gate={id:'deep-v1-final-gate',kind:'sealedGate',x:32,y:24,state:gateOpen?'open':'sealed',blocked:!gateOpen,actions:gateOpen?['enter']:['inspect'],requires:['deep-v1-miniboss-west','deep-v1-miniboss-east','deep-v1-miniboss-south'],opensWhen:'allWingMinibossesDefeated',seals:'deep-v1-final-arena'};
 for(let x=30;x<=34;x++)tiles[24*width+x]={...tiles[24*width+x],kind:gateOpen?'deepFloor':'sealedGate',blocked:!gateOpen,gateId:gate.id};
 const finalGateTiles=[];for(let x=30;x<=34;x++)finalGateTiles.push({x,y:24});
 const objects=[{id:'deep-v1-exit',kind:'exit',...entry,state:'open',actions:['exit']},{id:'deep-v1-entry-anchor',kind:'entryAnchor',...entry,state:'stable',actions:[]},{id:'deep-v1-hub-anchor',kind:'hubAnchor',...hub,state:'stable',actions:[]},...returns.map(q=>({...q,kind:'deepReturn',toX:hub.x,toY:hub.y,state:'dormant',actions:[]})),gate];
 const variants={west:['rootBrute','hollowMarshal'],east:['sparkWarden','voidSentinel'],south:['coilStalker','ashenHound']},bosses=[{id:'deep-v1-miniboss-west',dungeonRole:'wingMiniboss',wingId:'west',x:7,y:32},{id:'deep-v1-miniboss-east',dungeonRole:'wingMiniboss',wingId:'east',x:57,y:32},{id:'deep-v1-miniboss-south',dungeonRole:'wingMiniboss',wingId:'south',x:16,y:52}],enemySpawns=bosses.map((q,i)=>({...q,kind:variants[q.wingId][Math.floor(r()*2)],boss:true,deepDungeon:true,stableOrder:i}));enemySpawns.push({id:'deep-v1-final-boss',kind:'gateRevenant',dungeonRole:'finalBoss',arenaId:'deep-v1-final-arena',x:32,y:9,boss:true,deepDungeon:true});
 return{seed,id,recipe:'deep-v1',name:'The Threefold Deep',identity:'sealed deep dungeon',danger:'three wing wardens',width,height,entry,hub,anchors:{entry,hub,returns},wings:bosses.map(q=>({id:q.wingId,minibossId:q.id,returnAnchorId:`deep-v1-return-${q.wingId}`})),finalArena:{id:'deep-v1-final-arena',sealedBy:gate.id,bossId:'deep-v1-final-boss'},finalGate:gate,finalGateId:gate.id,finalGateTiles,finalEnemyIds:enemySpawns.map(q=>q.id),pits,tiles,objects,enemySpawns};
}
export function generateDungeon(seed,id=`dungeon:${seed}:g1`,options){if(isDeepDungeonId(id))return generateDeepDungeon(seed,id,options);const{recipe,name,identity,danger}=dungeonDescriptor(id),r=rng(`${seed}:dungeon:v2:${id}`),tiles=[];for(let y=0;y<24;y++)for(let x=0;x<24;x++){let open;if(recipe==='hollow')open=(x>2&&x<10&&y>2&&y<10)||(x>13&&x<21&&y>3&&y<11)||(x>5&&x<19&&y>14&&y<22)||(y===7&&x>=9&&x<=14)||(x===16&&y>=10&&y<=15);else if(recipe==='cistern')open=(x>2&&x<21&&y>2&&y<8)||(x>4&&x<10&&y>7&&y<21)||(x>13&&x<21&&y>13&&y<21)||(y===16&&x>=9&&x<=14);else open=(x>2&&x<21&&y>2&&y<9)||(x>2&&x<8&&y>8&&y<21)||(x>11&&x<21&&y>13&&y<21)||(y===16&&x>=7&&x<=12);tiles.push({x,y,kind:open?'floor':'wall',blocked:!open,detail:(x+y)%4})}const objects=[{id:'dungeon-chest',kind:'chest',x:18,y:recipe==='hollow'?7:5,state:'closed',actions:['open'],rewardSource:`${recipe}-cache`},{id:'dungeon-exit',kind:'exit',x:4,y:5,state:'open',actions:['exit']},supply(seed,id,0,tiles,24)];if(recipe==='cistern')objects.push({id:'vault-cache',kind:'supplyCache',supplyType:'restorativeDraught',x:15,y:18,state:'ready',actions:['collect']});if(id===dungeonId(seed,Number(id.match(/:g(\d+)/)?.[1]||1)))objects.push({id:'relay-terminal',kind:'relayTerminal',name:'Crossing Terminal',x:17,y:19,state:'ready',actions:['inspect','restore','sever']});if(recipe==='cistern')objects.push({id:'cistern-vine',kind:'vine',x:8,y:16,toX:15,toY:16,state:'ready',actions:['swing']});if(recipe==='kiln')objects.push({id:'kiln-vent',kind:'trap',trapType:'fire',x:12,y:16,dirX:1,dirY:0,phase:'armed',timer:0,hits:{},clue:'scorch'});else if(recipe!=='hollow')objects.push({id:'crossing-spikes',kind:'trap',trapType:'spikes',x:15,y:16,phase:'armed',timer:0,hits:{},clue:'seams'});const enemySpawns=[{kind:'ashling',x:8,y:8},{kind:'sparkWarden',x:16,y:16},{kind:'hollowMarshal',x:10+Math.floor(r()*5),y:18,boss:true}];if(recipe==='kiln')enemySpawns.push({kind:'sparkWarden',x:18,y:6,elite:true});return{seed,id,recipe,name,identity,danger,tiles,objects,enemySpawns}}
